con = 0;
gameover_parent = instance_find(obj_gameover_minigame, 0);
tenna = -4;
init = false;
gameover_sequence = 1;
make_writer = false;
global.flag[1003]++;
times_lost = global.flag[1003];
debug_print("times lost:" + string(times_lost));
bg_colorize = false;
punishment = 0;
punished = 0;
inbattle = 0;
timer = 0;
makeangry = 0;
