flamecon = 1;
flamealph = 0.8;
thickness = 2;
wave_siner = 0;
flamesiner = 0;
flameya = view_hport[0] + sprite_get_height(spr_gameshow_stage_fire);
wave_maxa = sprite_get_height(spr_gameshow_stage_fire);
wave_maxb = sprite_get_height(spr_gameshow_stage_fire);
base_y_pos = (view_hport[0] - sprite_get_height(spr_gameshow_stage_fire)) + 10;
mysurface = surface_create(640, 160);
scr_lerpvar("flameya", flameya, base_y_pos, 15, 2, "out");
