scr_enemy_object_init();
talkmax = 90;
image_speed = 0.16666666666666666;
idlesprite = spr_maus_idle;
hurtsprite = spr_maus_hurt;
sparedsprite = spr_maus_spared;
trappingX = false;
remove = false;
trappedText = false;
basket = -4;
trapped = false;
tasque_joined = false;
fearact = 0;
complimentact = 0;
nact_count = 0;
nise_susie = -100;
