con = 0;
timer = 0;
image_alpha = 0;
depth = 1000102;
dowing = 0;
wing = -4;
init = false;
ballsurface = surface_create(640, 640);
ps = part_system_create();
part_system_automatic_draw(ps, false);
ptdebris = part_type_create();
part_type_sprite(ptdebris, 5552, false, false, true);
part_type_speed(ptdebris, 3, 8, -0.1, 0);
part_type_life(ptdebris, 30, 80);
part_type_alpha3(ptdebris, 1, 1, 0);
part_type_gravity(ptdebris, 0.1, 270);
part_type_size(ptdebris, 0.3, 1, 0, 0);
outlineColor = shader_get_uniform(shd_outline, "i_color");
outlineW = shader_get_uniform(shd_outline, "i_thickness");
pemitter = part_emitter_create(ps);
part_emitter_region(ps, pemitter, x, x + 1, y, y + 1, 0, 0);
bs = part_system_create();
part_system_automatic_draw(bs, false);
btballs = part_type_create();
part_type_sprite(btballs, 3117, false, false, true);
var lifetime = random_range(60, 60);
part_type_speed(btballs, 1, 6, -6 / lifetime, 0);
part_type_life(btballs, lifetime, lifetime);
part_type_gravity(btballs, 0.1, 90);
part_type_size(btballs, 0, 0, 1 / lifetime, 0);
btballs2 = part_type_create();
part_type_sprite(btballs2, 3117, false, false, true);
part_type_speed(btballs2, 2, 2, 0, 0);
part_type_direction(btballs2, 90, 90, 0, 0);
part_type_life(btballs2, 45, 45);
part_type_gravity(btballs2, 0.05, 90);
part_type_size(btballs2, 1, 1, -0.022222222222222223, 0);
part_type_death(btballs, 1, btballs2);
bemitter = part_emitter_create(bs);
part_emitter_region(bs, bemitter, x, x + 1, 500, 501, 0, 0);
part_system_depth(ps, depth + 1);
part_system_depth(bs, depth);
