var lightcol = image_blend;
draw_set_alpha(0.4);
draw_set_color(lightcol);
var width = 60;
var height = 30;
draw_set_alpha(0.5);
var xmod = sin(siner / 10) * 4;
var ymod = cos(siner / 23) * 2;
draw_sprite_ext(sprite_index, 0, x + xmod, y + ymod, 2, 2, 0, image_blend, 0.5);
draw_set_alpha(0.4);
xmod = sin(siner / 11) * 4;
ymod = 0;
draw_sprite_ext(sprite_index, 0, x + xmod, y + ymod, 2, 2, 0, image_blend, 0.4);
draw_set_alpha(1);
