if (con == 0)
{
    con = 1;
    alarm[0] = 1;
    global.interact = 1;
    global.facing = 0;
}
if (con == 2)
{
    con = 3;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    fu = actor_count + 1;
    if (scr_flag_get(394) == 1)
        fu_actor = instance_create(283, 480, obj_actor);
    else
        fu_actor = instance_create(304, 480, obj_actor);
    scr_actor_setup(fu, fu_actor, "furniture");
    fu_actor.sprite_index = (scr_flag_get(394) == 1) ? spr_dw_icee_cushion : bg_dw_castle_trash;
    c_sel(su);
    c_setxy(293, 280);
    c_facing("susieunhappy");
    c_facing("u");
    c_sel(ra);
    c_setxy(300, 434);
    c_facing("u");
    c_delaywalkdirect(2, 300, 345, 60);
    c_wait(10);
    c_sel(kr);
    c_setxy(303, 470);
    c_facing("u");
    c_delaywalkdirect(2, 303, 402, 60);
    c_wait(2);
    c_var_lerp_instance(blackall, "image_alpha", 1, 0, 60);
    c_wait(120);
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* It's.../%", "obj_ch4_PDC06B_slash_Step_0_gml_57_0");
    c_talk_wait();
    c_wait(15);
    c_sel(su);
    c_facing("l");
    c_imagespeed(0.25);
    c_walkdirect_wait(220, 280, 30);
    c_wait(30);
    c_facing("d");
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\ER* It's..^1. empty...?/%", "obj_ch4_PDC06B_slash_Step_0_gml_71_0");
    c_talk_wait();
    c_wait(15);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_halt();
    c_speaker("ralsei");
    c_msgsetloc(0, "\\E8* .../%", "obj_ch4_PDC06B_slash_Step_0_gml_81_0");
    c_talk_wait();
    c_sel(ra);
    c_autowalk(1);
    c_walkdirect(300, 160, 90);
    c_delaycmd(91, "halt");
    c_wait(15);
    c_sel(su);
    c_facing("r");
    c_wait(15);
    c_facing("u");
    c_wait(90);
    c_mus2("initloop", "noelle_normal.ogg", 0);
    c_wait(60);
    c_msgside("bottom");
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EQ* My own room? ..^1. I..^1. I don't need a room!/", "obj_ch4_PDC06B_slash_Step_0_gml_108_0");
    c_msgnextloc("\\Ee* .../", "obj_ch4_PDC06B_slash_Step_0_gml_109_0");
    c_msgnextloc("\\Ea* ...at least..^1. that's what I thought./", "obj_ch4_PDC06B_slash_Step_0_gml_110_0");
    c_msgnextloc("\\EQ* So..^1. So I never.../%", "obj_ch4_PDC06B_slash_Step_0_gml_111_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_halt();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up);
    c_halt();
    c_wait_box(3);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_halt();
    c_wait_talk();
    c_sel(su);
    c_imagespeed(0.25);
    c_walkdirect(220, 185, 30);
    c_halt();
    c_autowalk(1);
    c_delayfacing(46, "u");
    c_sel(kr);
    c_walkdirect_wait(302, 200, 50);
    c_walkdirect_wait(370, 200, 20);
    c_facing("u");
    c_speaker("susie");
    c_msgsetloc(0, "\\EC* ..^1. You..^1. you LIVE here. Why do WE have rooms and not you?/", "obj_ch4_PDC06B_slash_Step_0_gml_144_0");
    c_facenext("ralsei", "Q");
    c_msgnextloc("\\EQ* Making you two happy.../", "obj_ch4_PDC06B_slash_Step_0_gml_146_0");
    c_msgnextloc("\\EQ* Is..^1. my purpose./", "obj_ch4_PDC06B_slash_Step_0_gml_147_0");
    c_msgnextloc("\\Ee* I.../", "obj_ch4_PDC06B_slash_Step_0_gml_148_0");
    c_msgnextloc("\\EQ* If I think about it.../", "obj_ch4_PDC06B_slash_Step_0_gml_149_0");
    c_msgnextloc("\\Ea* There's no reason.../", "obj_ch4_PDC06B_slash_Step_0_gml_150_0");
    c_msgnextloc("\\E8* For me..^1. to have..^1. anything./%", "obj_ch4_PDC06B_slash_Step_0_gml_151_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_ralsei_turn_right_subtle);
    c_wait_box(3);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_wait_box(4);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up);
    c_wait_box(5);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_wait_box(6);
    c_sel(ra);
    c_sprite(spr_ralsei_turn_right_subtle);
    c_wait_box(7);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_wait_talk();
    c_sel(su);
    c_walkdirect_wait(220, 157, 5);
    c_facing("r");
    c_speaker("susie");
    c_msgsetloc(0, "\\EH* That's the stupidest goddamn thing I ever heard!/", "obj_ch4_PDC06B_slash_Step_0_gml_186_0");
    c_msgnextloc("\\E5* You see this stupid excuse for a room?/", "obj_ch4_PDC06B_slash_Step_0_gml_187_0");
    c_msgnextloc("\\EV* I don't care what the reason is./", "obj_ch4_PDC06B_slash_Step_0_gml_188_0");
    c_msgnextloc("\\E2* Me and Kris are gonna fill it up. Wall to wall./", "obj_ch4_PDC06B_slash_Step_0_gml_189_0");
    c_msgnextloc("\\EY* Until you have the most badass room in the castle./", "obj_ch4_PDC06B_slash_Step_0_gml_190_0");
    c_facenext("ralsei", "D");
    c_msgnextloc("\\ED* Susie.../%", "obj_ch4_PDC06B_slash_Step_0_gml_192_0");
    c_talk();
    c_wait_box(1);
    c_sel(su);
    c_facing("u");
    c_wait_box(2);
    c_sel(su);
    c_facing("r");
    c_wait_box(6);
    c_sel(ra);
    c_facing("l");
    c_wait_talk();
    c_wait(15);
    c_sel(su);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_susie_head_scratch_dw);
    c_addxy(0, -6);
    c_sel(ra);
    c_facing("l");
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* Look. You can't be the only one with an empty room./", "obj_ch4_PDC06B_slash_Step_0_gml_222_0");
    c_msgnextloc("\\ER* It's.../%", "obj_ch4_PDC06B_slash_Step_0_gml_223_0");
    c_talk_wait();
    c_sel(su);
    c_halt();
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\ET* It's too sad^1, y'know?/%", "obj_ch4_PDC06B_slash_Step_0_gml_232_0");
    c_talk_wait();
    c_sel(ra);
    c_facing("d");
    c_halt();
    c_sel(su);
    c_autowalk(1);
    c_addxy(0, 6);
    c_walkdirect_wait(220, 183, 10);
    c_facing("r");
    c_sel(kr);
    c_facing("l");
    c_wait(15);
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* Wherever we go^1, we'll keep an eye out for furniture^1,/", "obj_ch4_PDC06B_slash_Step_0_gml_252_0");
    c_msgnextloc("\\EA* Right^1, Kris?/", "obj_ch4_PDC06B_slash_Step_0_gml_253_0");
    c_msgnextloc("\\E9* C'mon./%", "obj_ch4_PDC06B_slash_Step_0_gml_254_0");
    c_talk_wait();
    c_sel(su);
    c_walkdirect_wait(296, 183, 15);
    c_walkdirect_wait(296, 480, 40);
    c_wait(25);
    c_soundplay(snd_escaped);
    c_wait(30);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EI* .../%", "obj_ch4_PDC06B_slash_Step_0_gml_268_0");
    c_talk_wait();
    c_wait(15);
    c_sel(kr);
    c_delayfacing(5, "l");
    c_sel(ra);
    c_walkdirect_wait(300, 188, 10);
    c_walkdirect_wait(320, 188, 10);
    c_wait(15);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EQ* Kris^1, Susie is so nice.../", "obj_ch4_PDC06B_slash_Step_0_gml_283_0");
    c_msgnextloc("\\Ee* It..^1. makes my heart hurt./%", "obj_ch4_PDC06B_slash_Step_0_gml_284_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_right_sad_subtle);
    c_wait_talk();
    c_wait(30);
    c_sel(ra);
    c_facing("d");
    c_wait(30);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\E5* I don't really have any hobbies^1, or interests./", "obj_ch4_PDC06B_slash_Step_0_gml_303_0");
    c_msgnextloc("\\EB* Baking^1, sewing^1, singing..^1. those are all just.../", "obj_ch4_PDC06B_slash_Step_0_gml_304_0");
    c_msgnextloc("\\EI* Things I thought to do..^1. for you two./", "obj_ch4_PDC06B_slash_Step_0_gml_305_0");
    c_msgnextloc("\\E8* .../", "obj_ch4_PDC06B_slash_Step_0_gml_306_0");
    c_msgnextloc("\\E8* But recently.../", "obj_ch4_PDC06B_slash_Step_0_gml_307_0");
    c_msgnextloc("\\Ea* I'm starting to feel like.../", "obj_ch4_PDC06B_slash_Step_0_gml_308_0");
    c_msgnextloc("\\EQ* Like I'm developing my own opinions./", "obj_ch4_PDC06B_slash_Step_0_gml_309_0");
    c_msgnextloc("\\E0* My own likes./", "obj_ch4_PDC06B_slash_Step_0_gml_310_0");
    c_msgnextloc("\\EQ* My own dislikes./", "obj_ch4_PDC06B_slash_Step_0_gml_311_0");
    c_msgnextloc("\\Ee* My own desires. My own..^1. fears./%", "obj_ch4_PDC06B_slash_Step_0_gml_312_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_down_sad_subtle);
    c_wait_box(2);
    c_sel(ra);
    c_facing("d");
    c_wait_box(4);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_down_sad_subtle);
    c_wait_box(5);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_right_sad_subtle);
    c_wait_box(6);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_wait_box(7);
    c_sel(ra);
    c_sprite(spr_ralsei_turn_left_subtle);
    c_wait_box(8);
    c_sel(ra);
    c_sprite(spr_ralsei_turn_right_subtle);
    c_wait_box(9);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_up_sad);
    c_wait_talk();
    c_wait(60);
    c_sel(ra);
    c_sprite(spr_ralsei_turn_right_subtle);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\E5* ..^1. please..^1. tell me.../", "obj_ch4_PDC06B_slash_Step_0_gml_355_0");
    c_msgnextloc("\\E0* Should I.../", "obj_ch4_PDC06B_slash_Step_0_gml_356_0");
    c_msgnextloc("\\E4* Should a..^1. Darkner..^1. be feeling like this?/%", "obj_ch4_PDC06B_slash_Step_0_gml_357_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_right_sad);
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_ralsei_sad_right_turn);
    c_wait_talk();
    c_msc(1300);
    c_talk_wait();
}
if (con == 4 && !d_ex())
{
    con = 10;
    c_wait(15);
    if (global.choice == 0)
    {
        scr_flag_set(854, 1);
        c_sel(ra);
        c_sprite(spr_ralsei_walk_down_blush);
        c_emote("!", 30);
        c_wait(30);
        c_speaker("ralsei");
        c_msgsetloc(0, "\\ED* ..^1. I.../", "obj_ch4_PDC06B_slash_Step_0_gml_391_0");
        c_msgnextloc("\\EO* I.../", "obj_ch4_PDC06B_slash_Step_0_gml_392_0");
        c_msgnextloc("\\E1* K..^1. Kris^1, hearing that from you^1, I might just.../%", "obj_ch4_PDC06B_slash_Step_0_gml_393_0");
        c_talk();
        c_wait_box(1);
        c_sel(ra);
        c_sprite(spr_ralsei_walk_right_blush);
        c_wait_talk();
    }
    else if (global.choice == 1)
    {
        scr_flag_set(854, 2);
        c_sel(ra);
        c_sprite(spr_ralsei_surprised_down_subtle);
        c_emote("!", 30);
        c_wait(30);
        c_facing("r");
        c_speaker("ralsei");
        c_msgsetloc(0, "\\EJ* Umm^1, d-did you say \"of course?\"/", "obj_ch4_PDC06B_slash_Step_0_gml_413_0");
        c_msgnextloc("\\EK* You covered up your mouth yawning^1, there.../", "obj_ch4_PDC06B_slash_Step_0_gml_414_0");
        c_msgnextloc("\\E2* Ah^1, you're nodding^1! That means^1, um^1, yes^1, doesn't it?/", "obj_ch4_PDC06B_slash_Step_0_gml_415_0");
        c_msgnextloc("\\E1* .../", "obj_ch4_PDC06B_slash_Step_0_gml_416_0");
        c_msgnextloc("\\E2* I'm sorry^1, Kris^1, I..^1. I was being.../%", "obj_ch4_PDC06B_slash_Step_0_gml_417_0");
        c_talk();
        c_wait_box(1);
        c_sel(ra);
        c_sprite(spr_ralsei_walk_right_blush);
        c_wait_box(2);
        c_sel(ra);
        c_facing("r");
        c_wait_box(3);
        c_sel(ra);
        c_facing("u");
        c_wait_box(4);
        c_sel(ra);
        c_sprite(spr_ralsei_walk_up_sad);
        c_wait_talk();
    }
    c_sel(ra);
    c_sprite(spr_ralsei_surprised_down_subtle);
    c_emote("!", 30);
    c_shakeobj();
    c_mus("free_all");
    c_soundplay(snd_doorclose);
    c_soundplay(snd_noise);
    c_soundplay(snd_paper_surf);
    c_sel(su);
    c_facing("susiedarkeyes");
    c_walkdirect(298, 280, 40);
    c_sel(fu);
    c_autowalk(0);
    c_autodepth(0);
    c_depth(97000);
    if (scr_flag_get(394) == 1)
        c_walkdirect_wait(283, 270, 40);
    else
        c_walkdirect_wait(304, 282, 40);
    c_wait(15);
    c_sel(su);
    c_facing("l");
    c_autowalk(0);
    c_imagespeed(0.25);
    c_walkdirect_wait(220, 280, 15);
    c_halt();
    c_autowalk(1);
    c_facing("u");
    var small_text = stringsetloc("(Can... you please take this back?)", "obj_ch4_PDC06B_slash_Step_0_gml_477_0");
    scr_smallface(0, "ralsei", 22, "middle", "bottom", small_text);
    c_msgside("top");
    c_speaker("susie");
    c_msgsetloc(0, "\\E9* Alright^1, furniture piece number one!/", "obj_ch4_PDC06B_slash_Step_0_gml_482_0");
    c_facenext("ralsei", 20);
    c_msgnextloc("\\EK* Th..^1. thanks^1, Susie!/", "obj_ch4_PDC06B_slash_Step_0_gml_484_0");
    c_facenext("susie", 2);
    c_msgnextloc("\\E2* Let's go^1, Kris. \\f0/%", "obj_ch4_PDC06B_slash_Step_0_gml_486_0");
    c_talk_wait();
    c_sel(su);
    c_walkdirect(220, 184, 15);
    c_delaywalkdirect(16, 314, 184, 20);
    c_delayfacing(36, "r");
    c_sel(ra);
    c_walkdirect_wait(270, 188, 15);
    c_facing("r");
    c_wait(10);
    c_panobj(kr_actor, 30);
    c_wait(31);
    c_pannable(0);
    c_sel(kr);
    c_facing("d");
    if (scr_flag_get(394) == 1)
        c_var_instance(icee_npc, "visible", 1);
    else
        c_var_instance(trash_npc, "visible", 1);
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 10 && !i_ex(obj_cutscene_master))
{
    global.interact = 0;
    global.facing = 0;
    scr_flag_set(710, 2);
    if (!snd_is_playing(global.currentsong[1]))
    {
        var recruited_all = scr_recruited_all_previous();
        var audio_file = recruited_all ? "castle_funk_long.ogg" : "castletown.ogg";
        global.currentsong[0] = snd_init(audio_file);
        global.currentsong[1] = mus_loop_ext(global.currentsong[0], 1, 1);
    }
    con = 99;
}
