timer = 0;
con = 0;
variant = 0;
scr_bullet_init();
damage = 1;
destroyonhit = 0;
grazepoints = 1;
active = 0;
image_speed = 0;
image_index = 1;
image_angle = irandom(360);
direction = image_angle;
gravity_direction = image_angle;
image_xscale = 1;
image_yscale = 1;
image_alpha = 0.5;
sprite_index = spr_ball_small_pixel_hitbox;
