scr_bullet_init();
image_xscale = 0;
image_yscale = 0;
even = false;
destroyonhit = false;
timer = 0;
con = 0;
growstart = 0;
playSound = true;
beamflicker = 0;
split = 0;
outbound = false;
splitmax = 14;
splitease = 0;
finalx = 0;
damage = 206;
element = 5;
