pivot = [];
timer = 0;
init = false;
show_debug = false;
focus = 0;
shattered = false;
shatter = false;
delay = 20;
image_speed = 0;
debug_room = scr_debug() && room == room_vfx_tester;
tip = false;
tip_time = 60;
image_xscale = 1;
image_yscale = 1;
