if (con == 0)
{
    con = 1;
    alarm[0] = 1;
    global.interact = 1;
    global.facing = 0;
}
if (con == 2)
{
    con = 3;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    c_pannable(1);
    c_pan(440, 1000, 4);
    c_wait(1);
    c_sel(ra);
    c_setxy(732, 1064);
    c_facing("u");
    c_sel(su);
    c_setxy(735, 1500);
    c_delaywalkdirect(10, 735, 1121, 70);
    c_delaywalkdirect(81, 760, 1121, 15);
    c_delayfacing(96, "u");
    c_var_lerp_instance(blackall, "image_alpha", 1, 0, 15);
    c_pan(440, 950, 60);
    c_sel(kr);
    c_setxy(742, 1440);
    c_walkdirect_wait(742, 1138, 60);
    c_walkdirect_wait(710, 1138, 15);
    c_facing("u");
    c_msgside("bottom");
    c_speaker("susie");
    c_msgsetloc(0, "\\E9* Ralsei...!/%", "obj_ch4_PDC06_slash_Step_0_gml_48_0");
    c_talk_wait();
    c_sel(ra);
    c_facing("d");
    c_emote("!", 15);
    c_wait(15);
    c_walkdirect_wait(733, 1134, 7);
    c_sel(ra);
    c_visible(0);
    c_sel(su);
    c_visible(0);
    c_sel(kr);
    c_autowalk(0);
    c_imagespeed(0);
    c_sprite(spr_ralsei_group_hug);
    c_walk("d", 3, 4);
    c_wait(5);
    c_soundplay(snd_wing);
    c_imageindex(1);
    c_wait(5);
    c_sprite(spr_ralsei_group_hug_nuzzle_alt);
    c_sel(ra);
    c_autowalk(0);
    c_sprite(spr_ralsei_nuzzle);
    c_setxy(732, 1146);
    c_var_instance(nuzzle_marker, "visible", 1);
    c_visible(1);
    c_imagespeed(0.25);
    c_var_instance(nuzzle_marker, "image_speed", 0.25);
    c_wait(30);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EH* Susie^1! Kris!^1! Welcome back!!/", "obj_ch4_PDC06_slash_Step_0_gml_89_0");
    c_msgnextloc("\\E1* I missed you.../", "obj_ch4_PDC06_slash_Step_0_gml_90_0");
    c_facenext("susie", 20);
    c_msgnextloc("\\EK* Yeah^1, yeah... hey, lemme talk about something./%", "obj_ch4_PDC06_slash_Step_0_gml_92_0");
    c_talk();
    c_wait_box(3);
    c_wait(5);
    c_halt();
    c_sel(ra);
    c_soundplay(snd_noise);
    c_autowalk(1);
    c_facing("d");
    c_setxy(734, 1134);
    c_var_instance(nuzzle_marker, "visible", 0);
    c_sel(su);
    c_setxy(760, 1134);
    c_visible(1);
    c_sel(kr);
    c_sprite(spr_krisu_dark);
    c_sel(ra);
    c_autowalk(0);
    c_imagespeed(0.25);
    c_walk_wait("u", 3, 16);
    c_halt();
    c_waittalk();
    c_wait(15);
    c_sel(su);
    c_facing("susieunhappy");
    c_speaker("susie");
    c_msgsetloc(0, "\\E0* Remember that cop last night? Undyne...?/", "obj_ch4_PDC06_slash_Step_0_gml_130_0");
    c_msgnextloc("\\ED* The Knight took her and locked her in the shelter south of town./", "obj_ch4_PDC06_slash_Step_0_gml_131_0");
    c_msgnextloc("\\E1* We gotta get her out^1, but..^1.the door's solid steel./", "obj_ch4_PDC06_slash_Step_0_gml_132_0");
    c_msgnextloc("\\ED* There's..^1. no way we can break in./", "obj_ch4_PDC06_slash_Step_0_gml_133_0");
    c_msgnextloc("\\E0* So now we're looking for the codes to the lock./", "obj_ch4_PDC06_slash_Step_0_gml_134_0");
    c_msgnextloc("\\ER* ..^1. we thought Noelle's mom might have one^1, but.../", "obj_ch4_PDC06_slash_Step_0_gml_135_0");
    c_facenext("ralsei", "0");
    c_msgnextloc("\\E0* Are you worried about her...? Undyne?/", "obj_ch4_PDC06_slash_Step_0_gml_137_0");
    c_facenext("susie", 5);
    c_msgnextloc("\\E5* Me? A cop like her? Hell no!/", "obj_ch4_PDC06_slash_Step_0_gml_139_0");
    c_msgnextloc("\\ED* Y'know..^1. It's^1, just that.../", "obj_ch4_PDC06_slash_Step_0_gml_140_0");
    c_facenext("ralsei", "Q");
    c_msgnextloc("\\EQ* Don't worry^1, Susie. Someone strong like her will be OK./", "obj_ch4_PDC06_slash_Step_0_gml_142_0");
    c_msgnextloc("\\EI* I want this place to be a place.../", "obj_ch4_PDC06_slash_Step_0_gml_143_0");
    c_msgnextloc("\\E0* Where you can forget about the real world for a while./", "obj_ch4_PDC06_slash_Step_0_gml_144_0");
    c_msgnextloc("\\E2* Just relax^1, OK...?/", "obj_ch4_PDC06_slash_Step_0_gml_145_0");
    c_msgnextloc("\\EE* And if anything tough happens^1,/", "obj_ch4_PDC06_slash_Step_0_gml_146_0");
    c_msgnextloc("\\EJ* I'll come help you two^1, as fast as I can!/", "obj_ch4_PDC06_slash_Step_0_gml_147_0");
    c_facenext("susie", "D");
    c_msgnextloc("\\ED* ..^1. thanks^1, Ralsei./", "obj_ch4_PDC06_slash_Step_0_gml_149_0");
    c_msgnextloc("\\E0* .../", "obj_ch4_PDC06_slash_Step_0_gml_150_0");
    c_facenext("ralsei", 0);
    c_msgnextloc("\\E0* ..^1. If it's any consolation.../", "obj_ch4_PDC06_slash_Step_0_gml_152_0");
    c_msgnextloc("\\E2* I don't sense any immediate danger./", "obj_ch4_PDC06_slash_Step_0_gml_153_0");
    c_msgnextloc("\\E4* If the Knight's only goal was to hurt people.../", "obj_ch4_PDC06_slash_Step_0_gml_154_0");
    c_msgnextloc("\\EJ* They would have acted sooner^1, right?/", "obj_ch4_PDC06_slash_Step_0_gml_155_0");
    c_msgnextloc("\\EE* For now^1, let's make sure no one else gets taken./", "obj_ch4_PDC06_slash_Step_0_gml_156_0");
    c_facenext("susie", "D");
    c_msgnextloc("\\ED* ..^1. Yeah^1, alright./", "obj_ch4_PDC06_slash_Step_0_gml_158_0");
    c_msgnextloc("\\E9* ..^1. heh^1, what's with you^1, making me feel better?/%", "obj_ch4_PDC06_slash_Step_0_gml_159_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_facing("r");
    c_sel(kr);
    c_facing("r");
    c_sel(su);
    c_walkdirect_wait(810, 1114, 20);
    c_facing("r");
    c_wait_box(4);
    c_sel(su);
    c_walkdirect_wait(794, 1082, 15);
    c_facing("u");
    c_wait_box(6);
    c_facing("l");
    c_wait_box(9);
    c_sel(su);
    c_sprite(spr_susie_surprised_left);
    c_wait_box(10);
    c_sel(su);
    c_facing("u");
    c_wait_box(12);
    c_sel(su);
    c_facing("u");
    c_wait_box(14);
    c_sel(su);
    c_facing("l");
    c_wait_box(15);
    c_sel(ra);
    c_facing("d");
    c_sel(kr);
    c_facing("u");
    c_wait_box(16);
    c_sel(ra);
    c_facing("r");
    c_wait_box(19);
    c_sel(ra);
    c_facing("d");
    c_wait_box(21);
    c_sel(ra);
    c_facing("r");
    c_wait_box(22);
    c_sel(su);
    c_facing("u");
    c_wait_box(28);
    c_sel(ra);
    c_facing("d");
    c_wait_box(30);
    c_sel(su);
    c_sprite(spr_susie_walk_left_dw);
    c_wait_box(31);
    c_sel(ra);
    c_facing("r");
    c_waittalk();
    c_sel(ra);
    c_autowalk(1);
    c_walkdirect_wait(762, 1086, 10);
    c_autowalk(0);
    c_sprite(spr_ralsei_susie_hug);
    c_halt();
    c_sel(su);
    c_visible(0);
    c_sel(ra);
    c_imagespeed(0.2);
    c_wait(4);
    c_soundplay(snd_bump);
    c_wait(9);
    c_imagespeed(0);
    c_wait(15);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EH* I wike you too^1, Suwsie!/", "obj_ch4_PDC06_slash_Step_0_gml_255_0");
    c_facenext("susie", 17);
    c_msgnextloc("\\EH* Yeah^1, alright^1, knock it off with the stupid voice!/", "obj_ch4_PDC06_slash_Step_0_gml_257_0");
    c_facenext("ralsei", "H");
    c_msgnextloc("\\EH* Whwy...? Oo-woo.../%", "obj_ch4_PDC06_slash_Step_0_gml_259_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_ralsei_susie_hug_push);
    c_imagespeed(0.2);
    c_wait_talk();
    c_wait(15);
    c_sel(su);
    c_visible(1);
    c_sprite(spr_susie_shove);
    c_soundplay(snd_noise);
    c_sel(ra);
    c_sprite(spr_ralsei_splat_caterpillar);
    c_setxy(740, 1120);
    c_soundplay(snd_splat);
    c_soundplay(snd_impact);
    c_var_instance(ra_actor, "hspeed", -12);
    c_var_instance(ra_actor, "friction", 1);
    c_wait(30);
    c_sel(su);
    c_facing("l");
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* (I should NOT have taught him that.)/%", "obj_ch4_PDC06_slash_Step_0_gml_292_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 3 && customcon == 1 && !d_ex())
{
    con = 4;
    scr_flag_set(706, 1);
}
if (con == 4 && customcon == 1 && !d_ex())
{
    con = 5;
    customcon = 0;
    c_waitcustom_end();
    c_panobj(kr_actor, 30);
    c_wait(31);
    c_pannable(0);
    c_sel(kr);
    c_facing("d");
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 5 && !i_ex(obj_cutscene_master))
{
    global.interact = 0;
    global.facing = 0;
    con = 99;
}
