dtsprite = spr_tem_sit;
rtsprite = spr_tem_sit_r;
ltsprite = spr_tem_sit_l;
utsprite = spr_tem_sit;
myinteract = 0;
facing = 0;
dfacing = 0;
image_speed = 0;
talked = 0;
ourcase = 0;
eggmake = 0;
egcon = 0;
egtimer = 0;
scr_npcdir();
scr_depth();
song_mode = false;
song_con = 0;
song_index = scr_flag_get(1651);
song_min = 0;
song_max = 3;
