siner++;
draw_sprite_ext(spr_pxwhite, 0, x, y, room_width, room_height, 0, c_black, 1);
var xx = room_width / 2;
var yy = ((room_height / 2) + 40) - 8;
var width = 120;
var height = 40;
var widmod = 2;
var heimod = 2.4;
var myblu = 7347470;
draw_set_color(myblu);
d_ellipse(xx - (width * widmod), yy - (height * heimod), (xx + (width * widmod)) - 1, (yy + (height * heimod)) - 1, 0);
draw_sprite_ext(spr_pxwhite, 0, xx - 40, yy + 80, 80, 220, 0, myblu, 1);
draw_set_color(#364ECF);
d_ellipse(xx - width, yy - height, (xx + width) - 1, (yy + height) - 1, 0);
