scr_bullet_init();
grazepoints = 2;
timer = -16;
gigatimer = -64;
gigachange = 1;
ultratimer = -32;
radius = 0;
damage = 55;
grazepoints = 3;
y_anchor = y;
destroyonhit = 0;
scr_darksize();
depth = obj_growtangle.depth - 2;
scr_lerpvar("y", y, y + 220, 32, 1, "out");
scr_script_delayed(scr_lerpvar, 32, "y", y + 220, y + 196, 16, 2, "inout");
scr_script_delayed(scr_lerpvar, 48, "y", y + 196, y + 204, 8, 2, "inout");
scr_script_delayed(scr_lerpvar, 56, "y", y + 204, y + 200, 8, 1, "in");
intensity = 0;
damage = 55;
element = 5;
target = obj_dbulletcontroller.target;
