scr_depth();
washit = 0;
vspeed = 12;
con = 0;
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
frozen = 0;
hadfrozen = 0;
fliptimer = 15;
touchsprite = spr_diamondm_hurt;
slidesprite = spr_diamondm_idle;
eraser = 0;
encountered = 0;
whichmonster = 0;
