event_inherited();
damage = 1;
init = 0;
myhealth = 2;
hitbuff = 0;
scr_darksize();
con = 1;
timer = 0;
waittime = 8;
active = true;
scr_depth_board();
cury = y + irandom(50) + 10;
image_flipper = irandom(80);
destroyonhit = false;
gravity = 0.7 + random(0.1);
memvspeed = vspeed;
memgravity = gravity;
krisonly = false;
