scr_bullet_init();
timer = 0;
con = 0;
circle1alpha = 0;
circle1radius = 31;
circle1width = 2;
circle1color = c_lime;
circle2alpha = 0;
circle2radius = 75;
circle2width = 4;
depth = obj_heart.depth + 1;
