scr_depth();
init = 0;
startx = x;
starty = y;
endx = x;
endy = y;
jumptime = 10 + irandom(10) + 10;
jumpspeed = 12 + irandom(5);
fakegravity = 0;
jumpy = 0;
timer = 0;
nowy = 0;
drawshadow = 0;
dark = global.darkzone + 1;
usesprites = 0;
usespritestimer = 0;
con = 0;
jumpsprite = sprite_index;
landsprite = sprite_index;
scr_darksize(id);
image_xscale = choose(2, -2);
image_speed = 0;
image_index = irandom(sprite_get_number(spr_dw_tv_rose)) - 1;
fadein = false;
