myinteract = 0;
talked = 0;
tempvar = 0;
image_speed = 0;
depthcancel = 0;
normalanim = 1;
remanimspeed = 0;
dojoFlag = 0;
mode = 0;
con = 0;
noroom = 0;
scr_depth();
fsiner = 0;
dojoPrizeValue = 1;
dojoPrizeType = "money";
dojoPrizeName = "money";
