if (con < 0)
    exit;
scr_populatechars();
if (con == 0 && global.interact == 0 && !d_ex())
{
    var trig = 0;
    with (obj_trigger)
    {
        if (extflag == "enddream")
        {
            if (place_meeting(x, y, obj_mainchara))
                trig = 1;
        }
    }
    if (trig == 1)
        con = 1;
}
if (con == 1)
{
    con = 10;
    global.interact = 1;
    gerson_npc = instance_find(obj_npc_gerson, 0);
    with (obj_dw_gerson_study)
        paper_marker.visible = 0;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    global.facing = 0;
    var actpos = scr_heromarker("kr", "end1");
    var krwalktime = scr_calculate_move_distance(obj_mainchara.x, obj_mainchara.y, actpos[0], actpos[1], 4);
    c_sel(kr);
    c_walkdirect(actpos[0], actpos[1], krwalktime);
    c_sel(su);
    var suwalktime = scr_calculate_move_distance(susie.x, susie.y, actpos[0], actpos[1], 6);
    actpos = scr_heromarker("su", "end1");
    c_walkdirect(actpos[0], actpos[1], suwalktime);
    c_sel(ra);
    var rawalktime = scr_calculate_move_distance(ralsei.x, ralsei.y, actpos[0], actpos[1], 6);
    actpos = scr_heromarker("ra", "end1");
    c_walkdirect(actpos[0], actpos[1], rawalktime);
    c_pannable(1);
    c_pan(160, cameray(), krwalktime);
    c_wait(max(krwalktime, suwalktime, rawalktime) + 1);
    c_sel(kr);
    c_facing("u");
    c_sel(ra);
    c_facing("u");
    c_sel(su);
    c_facing("u");
    c_var_instance(paper_marker, "visible", 1);
    c_var_instance(gerson_npc, "current_state", 9);
    c_var_instance(gerson_npc, "depth", 91641);
    c_wait(20);
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* Alright^1, we're finally almost back to the fountain.../%", "obj_ch4_DCA10_slash_Step_0_gml_92_0");
    c_talk_wait();
    c_wait(15);
    c_sel(kr);
    c_facing("d");
    c_sel(ra);
    c_facing("d");
    c_emote("!", 30);
    c_sel(su);
    c_facing("d");
    c_emote("!", 30);
    c_msgside("top");
    c_speaker("gerson");
    c_msgsetloc(0, "* Wait a second there!/", "obj_ch4_DCA10_slash_Step_0_gml_108_0");
    c_msgnextloc("* I got somethin' for ya.../%", "obj_ch4_DCA10_slash_Step_0_gml_109_0");
    c_talk_wait();
    c_wait(15);
    c_pannable(1);
    c_pan_wait(160, 560, 60);
    c_wait(30);
    c_sel(su);
    c_autodepth(0);
    c_depth(89000);
    c_setxy(80, 574);
    c_walkdirect_wait(140, 574, 15);
    c_walkdirect_wait(290, 690, 30);
    c_walkdirect_wait(290, 776, 20);
    c_walkdirect_wait(404, 776, 30);
    c_facing("u");
    c_wait(30);
    c_sel(kr);
    c_setxy(462, 230);
    c_sel(ra);
    c_setxy(508, 218);
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_susie_head_scratch_dw);
    c_imagespeed(0.2);
    c_flip("x");
    c_addxy(0, -6);
    c_msgside("bottom");
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* Hey^1, we're about to go end this dream^1, so.../", "obj_ch4_DCA10_slash_Step_0_gml_148_0");
    c_facenext("gerson", 0);
    c_msgnextloc("* Good timing^1! I just about finished my letter./", "obj_ch4_DCA10_slash_Step_0_gml_150_0");
    c_msgnextloc("* Ya mind deliverin' it for me?/%", "obj_ch4_DCA10_slash_Step_0_gml_151_0");
    c_talk();
    c_wait_box(2);
    c_snd_play(snd_gerlaugh);
    c_var_instance(gerson_npc, "current_state", 5);
    c_sel(su);
    c_halt();
    c_facing("u");
    c_autowalk(1);
    c_flip("x");
    c_addxy(0, 6);
    c_wait_box(3);
    c_var_instance(gerson_npc, "current_state", 2);
    c_wait_talk();
    c_var_instance(gerson_npc, "current_state", 9);
    c_sel(su);
    c_emote("?", 30);
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\E6* ..^1. deliver it?/", "obj_ch4_DCA10_slash_Step_0_gml_178_0");
    c_msgnextloc("\\ED* Like I said^1, when we wake up^1, it'll be gone^1, so.../", "obj_ch4_DCA10_slash_Step_0_gml_179_0");
    c_facenext("gerson", 0);
    c_msgnextloc("* Yep^1, that's what I mean./", "obj_ch4_DCA10_slash_Step_0_gml_181_0");
    c_msgnextloc("* This letter..^1. just have a read of it for me./", "obj_ch4_DCA10_slash_Step_0_gml_182_0");
    c_msgnextloc("* Then^1, when you wake up.../", "obj_ch4_DCA10_slash_Step_0_gml_183_0");
    c_msgnextloc("* ..^1. write it all back down^1, okay?/", "obj_ch4_DCA10_slash_Step_0_gml_184_0");
    c_facenext("susie", "6");
    c_msgnextloc("\\E6* Me? Rewrite ALL of it? Why don't you just.../", "obj_ch4_DCA10_slash_Step_0_gml_186_0");
    c_facenext("gerson", 0);
    c_msgnextloc("* This old mind's gotta get some help remembering it./%", "obj_ch4_DCA10_slash_Step_0_gml_188_0");
    c_talk();
    c_wait_box(1);
    c_sel(su);
    c_halt();
    c_facing("r");
    c_autowalk(1);
    c_wait_box(3);
    c_var_instance(gerson_npc, "current_state", 2);
    c_sel(su);
    c_facing("u");
    c_wait_box(8);
    c_var_instance(gerson_npc, "current_state", 9);
    c_sel(su);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_walk_wait("d", 1, 10);
    c_delaycmd(11, "imagespeed", 0);
    c_wait_box(10);
    c_snd_play(snd_gerlaugh);
    c_var_instance(gerson_npc, "current_state", 5);
    c_wait_talk();
    c_var_instance(gerson_npc, "current_state", 9);
    c_wait(30);
    c_sel(su);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_walk_wait("u", 1, 10);
    c_delaycmd(11, "imagespeed", 0);
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* ..^1. Alright. Fine. I'll take a look./%", "obj_ch4_DCA10_slash_Step_0_gml_229_0");
    c_talk_wait();
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_susie_walk_right_dw);
    c_walkdirect_wait(500, 776, 15);
    c_sprite(spr_susie_up_press);
    c_halt();
    c_wait(6);
    c_var_instance(paper_marker, "visible", 0);
    c_snd_play(snd_wing);
    c_wait(15);
    c_autowalk(0);
    c_sprite(spr_susie_walk_down_paper_look_left);
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* .../", "obj_ch4_DCA10_slash_Step_0_gml_257_0");
    c_msgnextloc("\\ED* .../", "obj_ch4_DCA10_slash_Step_0_gml_258_0");
    c_msgnextloc("\\E1* Okay. Got it./", "obj_ch4_DCA10_slash_Step_0_gml_259_0");
    c_msgnextloc("\\EK* I^1, uh^1, might..^1. miss a few things./", "obj_ch4_DCA10_slash_Step_0_gml_260_0");
    c_msgnextloc("\\EC* ..^1. You sure you want ME to do it?/", "obj_ch4_DCA10_slash_Step_0_gml_261_0");
    c_facenext("gerson", 0);
    c_msgnextloc("* Long as you got the point^1, the words don't matter./", "obj_ch4_DCA10_slash_Step_0_gml_263_0");
    c_facenext("susie", "D");
    c_msgnextloc("\\ED* ..^1. okay^1, sure./%", "obj_ch4_DCA10_slash_Step_0_gml_265_0");
    c_talk();
    c_wait_box(3);
    c_sel(su);
    c_imageindex(1);
    c_wait_box(4);
    c_sel(su);
    c_imageindex(0);
    c_wait_box(6);
    c_var_instance(gerson_npc, "current_state", 12);
    c_sel(su);
    c_imageindex(1);
    c_wait_box(8);
    c_var_instance(gerson_npc, "current_state", 9);
    c_sel(su);
    c_autowalk(1);
    c_facing("u");
    c_wait_talk();
    c_walkdirect(290, 776, 60);
    c_wait(20);
    if (scr_flag_get(1547) > 0 && scr_flag_get(1629) == 0)
    {
        c_wait(40);
        c_speaker("gerson");
        c_msgsetloc(0, "* By the by.../", "obj_ch4_DCA10_slash_Step_0_gml_301_0");
        c_msgnextloc("* ..^1. mind telling your friend somethin' for me?/", "obj_ch4_DCA10_slash_Step_0_gml_302_0");
        c_facenext("susie", 6);
        c_msgnextloc("\\E6* Huh? Sure./%", "obj_ch4_DCA10_slash_Step_0_gml_304_0");
        c_talk();
        c_wait_box(1);
        c_sel(su);
        c_facing("r");
        c_wait_talk();
        c_panobj(kr_actor, 60);
        c_wait(120);
        c_sel(ra);
        c_facing("l");
        c_sel(kr);
        c_facing("l");
        c_sel(su);
        c_autowalk(1);
        c_setxy(130, 204);
        c_walkdirect_wait(296, 214, 30);
        c_speaker("susie");
        c_msgsetloc(0, "\\E1* Hey^1, Kris^1, he asked if we ever looked at the fireplace.../", "obj_ch4_DCA10_slash_Step_0_gml_330_0");
        c_msgnextloc("\\EK* ..^1. seems like..^1. uh^1, a quest^1, thing? Up to you^1, though./%", "obj_ch4_DCA10_slash_Step_0_gml_331_0");
        c_talk();
        c_wait_box(1);
        c_sel(su);
        c_facing("d");
        c_wait_talk();
        c_sel(su);
        c_facing("r");
        c_walkdirect_wait(404, 214, 20);
    }
    else
    {
        c_panobj(kr_actor, 60);
        c_wait(120);
        c_sel(ra);
        c_facing("l");
        c_sel(kr);
        c_facing("l");
        c_sel(su);
        c_autowalk(1);
        c_setxy(130, 213);
        c_walkdirect_wait(294, 214, 30);
        c_wait(15);
        c_sel(su);
        c_sprite(spr_susie_pose);
        c_sel(ra);
        c_autowalk(0);
        c_sprite(spr_ralsei_wave_down);
        c_addxy(-4, 0);
        c_imagespeed(0.1);
        c_sel(kr);
        c_facing("d");
        c_speaker("susie");
        c_msgsetloc(0, "\\E9* ..^1. see you later^1, old man!/%", "obj_ch4_DCA10_slash_Step_0_gml_374_0");
        c_talk_wait();
        c_wait(30);
        c_sel(ra);
        c_autowalk(1);
        c_facing("l");
        c_addxy(4, 0);
        c_sel(kr);
        c_facing("l");
        c_sel(su);
        c_facing("r");
        c_walkdirect_wait(404, 214, 20);
        c_speaker("susie");
        c_msgsetloc(0, "\\E2* Alright^1, let's go get that fountain./%", "obj_ch4_DCA10_slash_Step_0_gml_392_0");
        c_talk_wait();
    }
    c_wait(11);
    c_pannable(0);
    c_sel(kr);
    c_facing("d");
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 10 && !i_ex(obj_cutscene_master))
{
    con = 0;
    global.interact = 0;
    global.facing = 0;
    global.plot = 190;
    con = 99;
    scr_tempsave();
}
