scr_size(2, 2);
siner = 0;
alpha = 0;
base = instance_create(x, y, obj_solid_temp);
base.extflag = "FLOOR1";
base.negasoliddisable = true;
scr_size(2, 2, base);
con = 0;
timer = 0;
siner = 0;
dir = 0;
config = 0;
init = 0;
block[0] = 0;
edge[0] = 0;
image_speed = 0;
image_index = 0;
scr_depth();
xflag = -4;
yflag = -4;
flagupdate = 0;
resetpos = 0;
active = false;
icon = -1;
