timer = 0;
con = 0;
afterimagecon = 0;
targetx = 0;
targety = 0;
variant = 0;
image_alpha = 0;
scr_bullet_init();
element = 5;
fadetohalftime = 5;
waittime = 10;
fadetofulltime = 20;
flashtime = 4;
len = 120;
lenstart = len;
