event_inherited();
touchflag = 0;
touchsprite = spr_diamondm_hurt;
eraser = 0;
touchflag = 0;
ignoresolid = 0;
scr_depth();
image_xscale = 2;
image_yscale = 2;
hitresult = 1;
washit = 0;
active = 1;
encountered = 0;
whichmonster = 0;
