scr_bullet_init();
event_inherited();
active = true;
element = 5;
width = 24;
grazepoints = 50;
aoe = true;
alarm[0] = 1;
alarm[1] = 3;
image_index = 2;
image_speed = 0;
image_yscale = 0.1;
slashdir = choose(-1, 1);
destroyonhit = false;
