event_inherited();
scr_darksize();
myhealth = 3;
hitbuff = 0;
active = 0;
myinteract = 0;
timer = 0;
mymessage = stringset("* FOUND THE SECRET OF \"MICHAEL.\"&* ALL MICHAELS NOW ADDED TO INVENTORY./%%");
drawblack = 0;
boxy = 0;
buffer = 0;
hitbuffer = 0;
defense = 0;
myhealth = 1;
scr_depth_board();
init = 0;
kr = 0;
su = 0;
ra = 0;
updateDepth = true;
read = 0;
skip = false;
image_speed = 0;
textside = 0;
