var visible_indices = [];
var backface_indices = [];
fall_speed = obj_dw_churchc_insidetitan.fall_speed;
depth = 0;
shader_timer += ((delta_time / 1000) * ((fall_speed * 2.5) + 0.1));
var indent = 0.98;
shader_set(shd_fountaineffect_alt);
shader_set_uniform_f(u_iTime, current_time / 250);
shader_set_uniform_f(u_iFall, shader_timer / 15);
shader_set_uniform_f(u_iPosOffset, tower_angle / 360, cameray() / 480);
shader_set_uniform_f(u_iResolution, 1.5, 1.5);
shader_set_uniform_f(u_uvs, s_uvs[0], s_uvs[1], s_uvs[2] - s_uvs[0], s_uvs[3] - s_uvs[1]);
var col = scr_make_color_hsv(current_time / 400, 50, (sin(current_time / 1600) * 10) + 70);
draw_sprite_ext(bg_fountain1, 0, (camerax() + 320) - 360, (cameray() + 240) - 360, 6, 6, 0, col, 1);
shader_reset();
cover.y -= fall_speed * 20;
