scr_darksize();
image_index = 6;
image_speed = 0;
playerObj = 544;
pointObj = 659;
solidObj = 322;
init = 0;
moveCon = 0;
moveClockwise = 1;
grabbed = 0;
sndbuff = 0;
sndcount = 0;
stuckcount = 0;
stuckbuff = 0;
