myinteract = 0;
talked = 0;
tempvar = 0;
image_speed = 0;
depthcancel = 0;
normalanim = 1;
remanimspeed = 0;
image_index_fake = 0;
image_speed_fake = 0;
mode = 0;
scr_depth();
fsiner = 0;
event_user(6);
