event_inherited();
element = 5;
speed_mult = 0;
top_speed = 0;
image_xscale = 1;
image_yscale = 1;
active = false;
destroy_on_hit = false;
grazepoints = 0;
turn_timer = 0;
turn_dir = 0;
grazed = 1;
turn_start = false;
distance = 0;
anim_timer = 0;
image_speed = 0;
