scr_darksize();
state = 0;
con = 0;
timer = 0;
scon = 0;
stimer = 0;
dir = 0;
image_speed = 0;
image_index = dir;
sarea = instance_create(x, y, obj_triggervolume);
sarea.sprite_index = spr_b3bs_searchzapper_searchlight;
sarea.image_xscale = 2;
sarea.image_yscale = 2;
sarea.image_alpha = 0.2;
sarea.depth = 1000000;
sarea.visible = true;
