cost = 0;
siner = 0;
greenindex = 0;
greensiner = 0;
itemcount = 0;
cost = 20;
mystring = string(cost);
timer = 0;
con = 0;
active = true;
myinteract = 0;
scr_darksize();
scr_depth_board();
haveroom = 1;
makestars = 0;
makestarstimer = 0;
xoff = 0;
yoff = 0;
tempblock = false;
costfree = false;
result = -1;
tvdinnerqty = -1;
