event_inherited();
animindex = 0;
scr_darksize();
depth = 999990;
myhealth = 3;
hitbuff = 0;
active = 0;
myinteract = 0;
timer = 0;
mymessage = stringset("* FOUND THE SECRET OF \"MICHAEL.\"&* ALL MICHAELS NOW ADDED TO INVENTORY./%%");
drawblack = 0;
boxy = 0;
buffer = 0;
hitbuffer = 0;
defense = 0;
myhealth = 1;
init = 0;
kr_mem = 0;
su_mem = 0;
ra_mem = 0;
kr = 0;
su = 0;
ra = 0;
plugged = 0;
watercount = 3;
wither = 0;
image_index = 0;
mysolid = instance_create(x, y, obj_board_solid);
mysolid.sprite_index = sprite_index;
scr_darksize(mysolid);
