event_inherited();
damage = 18;
target = 3;
afterimage_timer = 0;
xoffset = 0;
yoffset = 0;
dir = 0;
timer = 0;
siner = 0;
con = 1;
laser_xscale = 1.6;
position = "below";
hitboxcreated = false;
image_speed = 0;
image_xscale = 2;
image_yscale = 2;
image_index = 0;
image_alpha = 0;
if (!audio_is_playing(snd_spearappear))
    snd_play_pitch(snd_spearappear, 1.6);
