draw_set_halign(fa_center);
draw_set_valign(fa_bottom);
draw_set_font(fnt_8bit);
draw_set_color(color_e1);
draw_text_transformed((camerax() + display_x) - 2, ((cameray() + display_y) - (sin(val) * 48)) + v_off, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e1);
draw_text_transformed((camerax() + display_x) - 2, (((cameray() + display_y) - (sin(val) * 48)) + v_off) - 2, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e1);
draw_text_transformed(camerax() + display_x, (((cameray() + display_y) - (sin(val) * 48)) + v_off) - 2, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e1);
draw_text_transformed(camerax() + display_x + 2, (((cameray() + display_y) - (sin(val) * 48)) + v_off) - 2, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e2);
draw_text_transformed(camerax() + display_x + 2, ((cameray() + display_y) - (sin(val) * 48)) + v_off, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e2);
draw_text_transformed(camerax() + display_x + 2, ((cameray() + display_y) - (sin(val) * 48)) + v_off + 2, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e2);
draw_text_transformed(camerax() + display_x, ((cameray() + display_y) - (sin(val) * 48)) + v_off + 2, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color_e2);
draw_text_transformed((camerax() + display_x) - 2, ((cameray() + display_y) - (sin(val) * 48)) + v_off + 2, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(color);
draw_text_transformed(camerax() + display_x, ((cameray() + display_y) - (sin(val) * 48)) + v_off, letter, 1, image_yscale, sin(global.time * 0.1) * 6);
draw_set_color(c_white);
draw_set_valign(fa_top);
draw_set_halign(fa_left);
