con = 0;
timer = 0;
image_alpha = 0;
init = 0;
ignoreplayer = 0;
scr_darksize();
active = 0;
susie = 0;
ralsei = 0;
kris = 0;
player = 0;
scr_depth_board();
makestars = false;
makestarstimer = 0;
glow = false;
glowsiner = 0;
glowtimer = 0;
active = true;
playerspin = true;
override = -1;
transition = 0;
siner = 0;
xoff = 0;
yoff = 0;
tempblock = false;
pickupname = "noone";
dodeodorant = false;
