scr_bullet_init();
spin = 0;
spinspeed = 0;
image_alpha = 1;
depth = obj_growtangle.depth - 1;
sprite_index = spr_tommygun_bullet;
wall_destroy = 1;
bottomfade = 0;
targetx = 0;
targety = 0;
timer = 0;
timermax = 20;
