myinteract = 0;
image_speed = 0;
active = true;
setxy(324, 158);
image_xscale = 24;
image_yscale = 122;
image_alpha = 0;
sprite_index = spr_whitepx;
timer = 0;
buffer = 0;
photographed = 0;
susiedecline = 0;
