scr_bullet_init();
active = false;
timer = 0;
image_alpha = 0.1;
image_speed = 0;
slash = false;
destroyonhit = false;
thickness = 10;
image_blend = c_gray;
trailthickness = 10;
xdir = 0;
ydir = 0;
xdraw = 250;
ydraw = 250;
init = false;
flip = false;
damage = 50;
timer = 0;
