event_inherited();
scr_darksize();
damage = 1;
mysolid = 0;
init = 0;
myhealth = 3;
hitbuff = 0;
active = true;
kris = 0;
buffer = 0;
defense = 2;
sndbuff = 0;
wither = 0;
destroyonhit = false;
scr_depth_board();
image_speed = 0;
image_index = choose(0, 1);
timer = 0;
spineindex = 0;
krisonly = false;
