scr_board_enemy_init();
show_outline = false;
hurt_sprite = spr_board_flower_hurt;
image_speed = 0;
timer = 0;
homingfactor = 0;
maxhomingfactor = 2.4;
aggressive = false;
hspd = 0;
vspd = 0;
savehspeed = 0;
savevspeed = 0;
onebyone = true;
onebyone_timer = 0;
justgo = false;
wake = false;
waketimer = 0;
