event_inherited();
destroyable = 1;
size = 3;
breaking = 0;
hp = 3;
init = 0;
flash = 1;
shrinksize = 1;
speed = 4;
angle_speed = random_range(-10, 10);
destroyonhit = 0;
image_blend = #00A2E8;
grazepoints = 4;
