event_inherited();
image_xscale = 0.5;
image_yscale = 0.5;
scr_lerpvar("image_xscale", 0.5, 1, 4);
scr_lerpvar("image_yscale", 0.5, 1, 4);
speed = 0.5;
scr_lerpvar("speed", 0.5, 6, 30);
image_speed = 0;
xxprevious = x;
yyprevious = y;
damage = 56;
grazepoints = 4;
