rtimer = 0;
attacked = 0;
turns = 0;
rr = 0;
mytarget = 0;
abletotarget = 0;
elnina_attack = 0;
lanino_attack = 0;
calculated_forecast = false;
forecasts = [];
forecast_alpha = 0;
forecast_turn = 0;
use_celsius = string_lower(os_get_region()) != "us";
sunboost = 0;
digit_alpha = 0;
digit_flash_timer = 0;
digit_flash_duration = 10;
ilovetv = 0;
ilovetv_increase = 0;
ilovetv_increased = false;
ilovetv_pitch = 1;
ilovetvlimit = true;
lastchosen = "";
umbrella = 0;
sunglasses = 0;
intro = 0;
introtimer = 0;
ralseishocked = false;
global.choice = -1;
talked = 0;
talktimer = 0;
balloonorder = 0;
ballooncon = 0;
balloonend = 1;
talkedcon = 0;
ralseitalks = 0;
susietalks = 0;
afterbulletcon = 0;
extratimer = 0;
extimer = 0;
excon = 0;
endcon = 0;
turn2_turns = 0;
tenna = instance_create_depth(camerax() + 330, cameray() - 50, -9999999, obj_actor_tenna);
tenna.bounce = 1;
tenna.preset = 2;
tenna.sprite_index = spr_tenna_point_left;
scr_speaker("tenna");
global.fc = 22;
instafinalattack = false;
if (instafinalattack == true)
    turns = 6;
battleresult = 0;
battlemsg_set = false;
if (!variable_global_exists("elninalosscount"))
    global.elninalosscount = 0;
else
    global.elninalosscount++;
