vertical_pos = 0;
old_pos = 0;
hole_size = 60;
scr_bullet_init();
scr_darksize();
damage = 206;
knightafterimagerange = 1;
image_speed = 0;
timer = 0;
introtimer = 0;
fake_timer = 0;
siner = 0;
con = 0;
fakefire = 0;
first_strike = true;
anchor_x = x;
anchor_y = y;
state = "nothin much tbh";
turn_type = "full";
turn_segment = -1;
next_up = -1;
next_next_up = -1;
local_turntimer = 280;
armpoint = 0;
armpoint_index = 0;
turntimer_limit = 90;
