event_inherited();
scr_bullet_init();
deceleration = 0.1;
minspeed = 1;
timer = 0;
drawtimer = 0;
damage = 1;
element = 5;
lifetime = 60;
difficulty = 0;
con = 0;
tracking = true;
timer = 0;
start_angle = 0;
target_angle = 0;
rotation = 0;
delay = 0;
init = false;
rotatespeed = 10;
ease = 0;
xscale_start = 0;
yscale_start = 0;
xprev = x;
yprev = y;
outline = 0;
accel = 0.5;
sprite_index = spr_knight_starchild_parts;
