event_inherited();
scr_bullet_init();
image_speed = 0;
image_index = 2;
active = false;
destroyonhit = false;
found = -1;
reverse = 12;
rising_sound = -1;
quake_sound = -1;
pull_pitch = 0.25;
damage = 150;
target = 4;
timer = 0;
image_yscale = 0.0125;
image_blend = c_gray;
fount = -1;
quake_sound = -1;
