fun = 0;
functionalfun = 0;
funspeed = 0.1;
scr_darksize(id);
scr_depth();
empty = 0.35;
half = 0.65;
full = 0.95;
maxed = true;
siner = 0;
hope = false;
shaking = false;
shakecon = 0;
cracked = false;
timer = 0;
hue = 0;
rainbow = 0;
image_xscale = 1;
image_yscale = 1;
hope_anim = 0;
hope_flower_active = false;
hope_flower_anim = 0;
