if (con < 0)
    exit;
if (con == 0)
{
    con = 1;
    alarm[0] = 1;
    global.interact = 1;
    scr_lerp_var_instance(_blackall, "image_alpha", 1, 0, 30);
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    te = actor_count + 1;
    te_actor = instance_create(camerax() + 145, 410, obj_actor_tenna);
    scr_actor_setup(te, te_actor, "tenna");
    te_actor.preset = 0;
    te_actor.sprite_index = spr_tenna_communication;
    te_actor.image_xscale = -2;
    te_actor.xscale = -2;
    c_sel(su);
    c_setxy(view_wport[0] + 150, 328);
    c_sel(kr);
    c_visible(0);
    c_sel(ra);
    c_visible(0);
    c_sel(su);
    c_walkdirect_speed(434, 328, 6);
    c_wait(30);
    c_var_instance(te_actor, "communication", 1);
    c_imageindex(0);
    c_speaker("tenna");
    c_msgsetloc(0, "* ..^1. located..^1. in the purple cliffs? Perfect^1! Don't waste any time./", "obj_room_stage_slash_Step_0_gml_44_0");
    c_msgnextloc("* You know what comes next. Assembly^1, air holes^1, soft^1, soothing music.../", "obj_room_stage_slash_Step_0_gml_45_0");
    c_msgnextloc("* Then we just need time./", "obj_room_stage_slash_Step_0_gml_46_0");
    c_msgnextloc("* One more board^1, just ONE more board and then.../", "obj_room_stage_slash_Step_0_gml_47_0");
    c_facenext("susie", "2");
    c_msgnextloc("\\E2* Hey./%", "obj_room_stage_slash_Step_0_gml_49_0");
    c_talk();
    c_wait_box(5);
    c_var_instance(te_actor, "communication", 0);
    c_sel(su);
    c_walk("l", 4, 8);
    c_wait_talk();
    c_snd_play(snd_jump);
    c_sel(te);
    c_sprite(spr_tenna_twirl);
    c_imagespeed(0.4);
    c_jump_in_place(80, 12);
    c_wait(13);
    c_imagespeed(0);
    c_tenna_sprite(spr_tenna_hurt);
    c_tenna_preset(15);
    c_var_instance(te_actor, "reversal", 1);
    c_wait(30);
    c_speaker("tenna");
    c_msgsetloc(0, "* S..^1. SUSIE!!!/", "obj_room_stage_slash_Step_0_gml_77_0");
    c_msgnextloc("* SUSIE^1, sweetheart^1, my STAR contestant^1, hey^1, how can I help you!?/", "obj_room_stage_slash_Step_0_gml_78_0");
    c_msgnextloc("* Free toy ball voucher!? Refreshments!? Lifetime supply of NON-GLOOBY slime?/", "obj_room_stage_slash_Step_0_gml_79_0");
    c_facenext("susie", "A");
    c_msgnextloc("\\EA* Just^1, uh.../", "obj_room_stage_slash_Step_0_gml_81_0");
    c_msgnextloc("\\EN* Wanted to say the games were pretty fun^1, I guess./%", "obj_room_stage_slash_Step_0_gml_82_0");
    c_talk();
    c_wait_box(1);
    c_tenna_preset(22);
    c_wait_box(2);
    c_tenna_preset(-32);
    c_wait_box(4);
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_susie_head_scratch_dw);
    c_imagespeed(0.2);
    c_addxy(0, -2);
    c_wait_box(5);
    c_sel(te);
    c_tenna_preset(0);
    c_addxy(12, 0);
    c_wait_talk();
    c_wait(15);
    c_tenna_sprite(spr_tenna_pose_headraised_nose);
    c_addxy(-12, 0);
    c_sel(su);
    c_halt();
    c_facing("l");
    c_addxy(0, 2);
    c_speaker("tenna");
    c_msgsetloc(0, "* They..^1. they are?/", "obj_room_stage_slash_Step_0_gml_115_0");
    c_facenext("susie", "K");
    c_msgnextloc("\\EK* I mean^1, you SAW when you interrupted us^1, but..^1. Ralsei.../", "obj_room_stage_slash_Step_0_gml_117_0");
    c_msgnextloc("\\ED* He was being kind of..^1.  weird^1, earlier./", "obj_room_stage_slash_Step_0_gml_118_0");
    c_msgnextloc("\\EN* I feel like this cheered him up./", "obj_room_stage_slash_Step_0_gml_119_0");
    c_msgnextloc("\\EL* And..^1. me too./", "obj_room_stage_slash_Step_0_gml_120_0");
    c_msgnextloc("\\EN* It's just been taking my mind off..^1. everything..^1. I guess./", "obj_room_stage_slash_Step_0_gml_121_0");
    c_facenext("tenna", 0);
    c_msgnextloc("* S..^1. Susie...?/%", "obj_room_stage_slash_Step_0_gml_123_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_susie_look_down_left);
    c_wait_box(3);
    c_sel(su);
    c_facing("u");
    c_wait_box(4);
    c_sel(su);
    c_facing("l");
    c_wait_box(5);
    c_sel(su);
    c_sprite(spr_susie_look_down_left);
    c_wait_box(6);
    c_autowalk(0);
    c_sprite(spr_susie_head_scratch_dw);
    c_imagespeed(0.2);
    c_addxy(0, -2);
    c_sel(te);
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_pose_headlowered_nose);
    c_wait_box(8);
    c_tenna_preset(8);
    c_addxy(54, 0);
    c_sel(su);
    c_halt();
    c_facing("l");
    c_addxy(0, 2);
    c_wait_talk();
    c_snd_play(snd_wing);
    c_sel(te);
    c_tenna_preset(-32);
    c_sprite(spr_tenna_hooray);
    c_imagespeed(0.2);
    c_addxy(-54, 0);
    c_delaycmd(15, "imagespeed", 0);
    c_delaycmd(15, "var", te_actor, "xscale", 2);
    c_delaycmd(15, "var", te_actor, "image_xscale", 2);
    c_var_lerp_to("x", 324, 12, 2, "out");
    c_sel(su);
    c_delaycmd(8, "imagespeed", 0.2);
    c_delaywalk(8, "r", 4, 8);
    c_delaycmd(16, "imagespeed", 0);
    c_speaker("tenna");
    c_msgsetloc(0, "* SUSIE!!!!!!!/", "obj_room_stage_slash_Step_0_gml_182_0");
    c_msgnextloc("* I've never wanted to hear ANYTHING more!!!/", "obj_room_stage_slash_Step_0_gml_183_0");
    c_msgnextloc("* I'VE LOVED putting on this SHOW^1! I haven't had this much fun in years!/", "obj_room_stage_slash_Step_0_gml_184_0");
    c_msgnextloc("* Seeing REAL LAUGHS^1! REAL SMILES^1! From an audience of MORE THAN ONE^1! It's a DREAM!/%", "obj_room_stage_slash_Step_0_gml_185_0");
    c_talk();
    c_wait_box(2);
    c_sel(te);
    c_sprite(spr_tenna_sad_turned_b);
    c_tenna_preset(31);
    c_wait_box(3);
    c_sel(te);
    c_tenna_preset(34);
    c_wait_box(4);
    c_tenna_preset(0);
    c_wait_talk();
    c_wait(60);
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_sad_turned_a);
    c_speaker("tenna");
    c_msgsetloc(0, "* I..^1. can't lie. I've been a bit^1, alone^1, until recently./", "obj_room_stage_slash_Step_0_gml_208_0");
    c_facenext("susie", "N");
    c_msgnextloc("\\EN* I..^1. can relate^1, I guess./", "obj_room_stage_slash_Step_0_gml_210_0");
    c_facenext("tenna", 0);
    c_msgnextloc("* But hosting you and lil' Ralsei has been an HONOR^1! Even if you're a tad sassy!/", "obj_room_stage_slash_Step_0_gml_212_0");
    c_facenext("susie", "A");
    c_msgnextloc("\\EA* Umm^1, hey^1, Kris was having fun^1, too./", "obj_room_stage_slash_Step_0_gml_214_0");
    c_facenext("tenna", 0);
    c_msgnextloc("* Oh..^1. yeah^1, Kris!/", "obj_room_stage_slash_Step_0_gml_216_0");
    c_msgnextloc("* Haha^1, Kris^1! Good old Kris^1! What a stinker!/", "obj_room_stage_slash_Step_0_gml_217_0");
    c_facenext("susie", "K");
    c_msgnextloc("\\EK* ..^1. don't you like Kris?/", "obj_room_stage_slash_Step_0_gml_219_0");
    c_facenext("tenna", 0);
    c_msgnextloc("* What the - are you kidding!? I LOVE Kris^1! They were one of my original viewers!/", "obj_room_stage_slash_Step_0_gml_221_0");
    c_msgnextloc("* I'm just not sure if^1, heh^1, they..^1. uhh^1, love TV./", "obj_room_stage_slash_Step_0_gml_222_0");
    c_facenext("susie", "K");
    c_msgnextloc("\\EK* Huh? Why wouldn't they.../%", "obj_room_stage_slash_Step_0_gml_224_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_susie_look_back_left);
    c_wait_box(4);
    c_sel(su);
    c_facing("l");
    c_sel(te);
    c_tenna_sprite(spr_tenna_pose);
    c_wait_box(6);
    c_tenna_preset(0);
    c_wait_box(8);
    c_sel(te);
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_pose_podium);
    c_wait_box(9);
    c_sel(te);
    c_tenna_sprite(spr_tenna_laugh_pose);
    c_sel(su);
    c_sprite(spr_susie_walk_left_dw_unhappy);
    c_wait_box(11);
    c_tenna_preset(0);
    c_wait_box(13);
    c_tenna_sprite(spr_tenna_hurt);
    c_wait_box(14);
    c_tenna_sprite(spr_tenna_tie_adjust_a);
    c_wait_talk();
    c_snd_play(snd_phone);
    c_tenna_sprite(spr_tenna_hurt);
    c_sel(su);
    c_sprite(spr_susie_sheeh);
    c_addxy(-2, 5);
    c_emote("?", 30, 0, -20);
    c_wait(30);
    c_tenna_sprite(spr_tenna_laugh_pose);
    c_tenna_preset(8);
    c_sel(su);
    c_facing("l");
    c_addxy(2, -5);
    c_speaker("tenna");
    c_msgsetloc(0, "* HEY would you look at that!^1! The NEXT BOARD's ready!!!/", "obj_room_stage_slash_Step_0_gml_285_0");
    c_msgnextloc("* It was GREAT talking to you^1, Susie!^1! Good luck out there!!/", "obj_room_stage_slash_Step_0_gml_286_0");
    c_facenext("susie", "7");
    c_msgnextloc("\\E7* Uhh^1, yeah^1! Later!/%", "obj_room_stage_slash_Step_0_gml_288_0");
    c_talk();
    c_wait_box(1);
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_point_left);
    c_wait_box(3);
    c_sel(su);
    c_imagespeed(0.2);
    c_walk("r", 4, 8);
    c_delaycmd(8, "imagespeed", 0);
    c_wait_talk();
    c_wait(15);
    c_sel(su);
    c_autowalk(1);
    c_walkdirect_speed(view_wport[0] + 150, 328, 6);
    c_var_lerp_to_instance(_blackall, "image_alpha", 1, 30);
    c_wait(60);
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 2 && !i_ex(obj_cutscene_master))
{
    con = -1;
    customcon = 0;
    scr_flag_set(1199, 1);
    room_goto(room_dw_b3bs_interstitial);
}
if (con == 10)
{
    con = 11;
    alarm[0] = 30;
    global.interact = 1;
    scr_lerp_var_instance(_blackall, "image_alpha", 1, 0, 30);
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    te = actor_count + 1;
    te_actor = instance_create(camerax() + 144, 410, obj_actor_tenna);
    scr_actor_setup(te, te_actor, "tenna");
    te_actor.preset = 0;
    te_actor.sprite_index = spr_tenna_communication;
    te_actor.image_xscale = -2;
    te_actor.xscale = -2;
    c_sel(su);
    c_setxy(view_wport[0] + 150, 326);
    c_sel(kr);
    c_setxy(view_wport[0] + 150, 343);
    c_sel(ra);
    c_setxy(view_wport[0] + 150, 334);
    c_sel(su);
    c_walkdirect_speed(382, 326, 6);
    c_wait(15);
    c_sel(kr);
    c_walkdirect_speed(470, 343, 6);
    c_wait(15);
    c_sel(ra);
    c_walkdirect_speed(538, 334, 6);
    c_wait(15);
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* Hey^1, Tenna.../%", "obj_room_stage_slash_Step_0_gml_377_0");
    c_talk_wait();
    c_sel(te);
    c_var_instance(te_actor, "communication", 1);
    c_imageindex(0);
    c_speaker("tenna");
    c_msgsetloc(0, "* What do you MEAN!? Then MAKE. The AIRHOLES. BIGGER!/", "obj_room_stage_slash_Step_0_gml_390_0");
    c_msgnextloc("* What do you think I'M PAYING your ELECTRICITY BILL FOR!?/", "obj_room_stage_slash_Step_0_gml_391_0");
    c_msgnextloc("* And HOW are they not HERE YET!? The LIGHTNERS are gonna get BORED!/%", "obj_room_stage_slash_Step_0_gml_392_0");
    c_talk();
    c_wait_box(1);
    c_imageindex(1);
    c_wait_box(2);
    c_sel(te);
    c_tenna_sprite(spr_tenna_sad_turned_b);
    c_wait_talk();
    c_sel(te);
    c_tenna_sprite(spr_tenna_communication);
    c_imageindex(0);
    c_wait(5);
    c_sel(su);
    c_sprite(spr_susie_surprised_left);
    c_speaker("tenna");
    c_msgsetloc(0, "* If that purple girl finds out about this^1, it's ALL OVER!/%", "obj_room_stage_slash_Step_0_gml_419_0");
    c_talk_wait();
    c_wait(30);
    c_sel(te);
    c_var_instance(te_actor, "communication", 0);
    c_speaker("susie");
    c_msgsetloc(0, "\\E1* ..^1. what are you talking about?/%", "obj_room_stage_slash_Step_0_gml_429_0");
    c_talk_wait();
    c_snd_play(snd_jump);
    c_sel(te);
    c_sprite(spr_tenna_twirl);
    c_imagespeed(0.4);
    c_jump_in_place(80, 12);
    c_wait(13);
    c_imagespeed(0);
    c_tenna_sprite(spr_tenna_frightened);
    c_shakeobj();
    c_wait(15);
    c_imageindex(4);
    c_shakeobj();
    c_speaker("tenna");
    c_msgsetloc(0, "* S-Susie!? Kris!? Uh^1, Susie^1, I.../%", "obj_room_stage_slash_Step_0_gml_452_0");
    c_talk_wait();
    c_tenna_sprite(spr_tenna_pose);
    c_var_instance(te_actor, "reversal", 1);
    c_snd_play(snd_wing);
    c_lerp_var_instance(te_actor, "x", te_actor.x, te_actor.x + 160, 15, 2, "out");
    c_tenna_preset(9);
    c_speaker("tenna");
    c_msgsetloc(0, "* Susie^1, sweetHEART^1! Hey^1, what's the trouble?/%", "obj_room_stage_slash_Step_0_gml_466_0");
    c_talk_wait();
    c_wait(30);
    c_sel(su);
    c_sprite(spr_susie_look_down_left);
    c_wait(30);
    c_tenna_preset(0);
    c_sel(te);
    c_addxy(12, 0);
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* ..^1. what was with that phone call?/%", "obj_room_stage_slash_Step_0_gml_482_0");
    c_talk_wait();
    c_tenna_sprite(spr_tenna_tie_adjust_a);
    c_sel(te);
    c_addxy(-12, 0);
    c_speaker("tenna");
    c_msgsetloc(0, "* Oh^1, THAT^1! Oh^1, NO I can't believe you^1, uh^1, HEARD!/%", "obj_room_stage_slash_Step_0_gml_491_0");
    c_talk_wait();
    c_sel(te);
    c_tenna_preset(-32);
    c_sprite(spr_tenna_hooray);
    c_addxy(-4, -4);
    c_imagespeed(0.2);
    c_delaycmd(15, "imagespeed", 0);
    c_speaker("tenna");
    c_msgsetloc(0, "* We were^1, uh^1, just planning a SPECIAL SURPRISE GAME for you.../", "obj_room_stage_slash_Step_0_gml_503_0");
    c_msgnextloc("* You^1, uh^1, didn't hear what it WAS^1, did you?/%", "obj_room_stage_slash_Step_0_gml_504_0");
    c_talk();
    c_wait_box(1);
    c_sel(te);
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_pose_podium);
    c_addxy(4, 4);
    c_imageindex(1);
    c_wait_talk();
    c_sel(su);
    c_facing("l");
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* ..^1. nah. Uh.../%", "obj_room_stage_slash_Step_0_gml_522_0");
    c_talk_wait();
    c_sel(te);
    c_tenna_sprite(spr_tenna_shocked);
    c_addxy(-4, -16);
    c_sel(su);
    c_walk("r", 4, 8);
    c_speaker("susie");
    c_msgsetloc(0, "\\ER* ..^1. I gotta^1, go^1, actually./%", "obj_room_stage_slash_Step_0_gml_534_0");
    c_talk();
    c_wait(8);
    c_wait_talk();
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_susie_walk_right_look_down_dw);
    c_imagespeed(0.2);
    c_walkdirect_speed(view_wport[0] + 150, 326, 6);
    c_sel(kr);
    c_facing("d");
    c_autowalk(0);
    c_imagespeed(0.2);
    c_walk("u", 4, 8);
    c_delaycmd(9, "imagespeed", 0);
    c_wait(4);
    c_sel(ra);
    c_facing("d");
    c_autowalk(0);
    c_imagespeed(0.2);
    c_walk("u", 4, 8);
    c_delaycmd(9, "imagespeed", 0);
    c_wait(15);
    c_sel(te);
    c_tenna_sprite(spr_tenna_pose_headlowered_nose);
    c_addxy(4, 16);
    c_sel(kr);
    c_autowalk(1);
    c_walk("d", 4, 8);
    c_delaywalkdirect(9, view_wport[0] + 150, 342, 40);
    c_wait(15);
    c_sel(ra);
    c_autowalk(1);
    c_walk("d", 4, 8);
    c_delaywalkdirect(9, view_wport[0] + 150, 334, 40);
    c_var_lerp_to_instance(_blackall, "image_alpha", 1, 30);
    c_wait(60);
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 12 && !i_ex(obj_cutscene_master))
{
    con = -1;
    customcon = 0;
    scr_flag_set(1208, 1);
    room_goto(room_dw_b3bs_interstitial);
}
if (con == 20)
{
    con = 21;
    alarm[0] = 1;
    global.interact = 1;
    global.facing = 0;
    with (obj_caterpillarchara)
    {
        follow = 0;
        fun = 1;
        visible = 0;
    }
}
if (con == 22)
{
    con = 23;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    te = actor_count + 1;
    te_actor = instance_create(camerax() + (view_wport[0] / 2), 410, obj_actor_tenna);
    scr_actor_setup(te, te_actor, "tenna");
    te_actor.preset = 0;
    te_actor.sprite_index = spr_tenna_sad_turned_a;
    if (scr_debug() && keyboard_check(ord("F")))
    {
        scr_debug_print("save/load enabled");
        saveload = true;
    }
    if (saveload)
    {
    }
}
if (con == 23 || scr_cutscene_loaded())
{
    con = 24;
    c_sel(te);
    c_flip("x");
    c_sel(su);
    c_visible(0);
    c_sel(ra);
    c_visible(0);
    c_var_lerp_instance(_blackall, "image_alpha", 1, 0, 30);
    c_sel(kr);
    c_setxy(camerax() + view_wport[0] + 40, 354);
    c_walkdirect_speed_wait((camerax() + view_wport[0]) - 120, 354, 4);
    c_wait(30);
    c_speaker("tenna");
    c_msgsetloc(0, "* Keep it TOGETHER^1, Tenna^1! They..^1. they're STILL loving it^1! They have to be!/", "obj_room_stage_slash_Step_0_gml_675_0");
    c_msgnextloc("* CLASSIC TV NEVER GETS OLD!!^1! And Susie^1! Susie^1, she was so excited.../%", "obj_room_stage_slash_Step_0_gml_676_0");
    c_talk();
    c_wait_box(1);
    c_sel(te);
    c_tenna_sprite(spr_tenna_sad_turned_b);
    c_var_lerp_instance(te_actor, "wobbleamt", 6, 0, 20, 1, "out");
    c_wait(3);
    c_var_lerp_instance(te_actor, "yscale", 2, 1, 3, 1, "out");
    c_sprite(spr_tenna_sad_turned_a);
    c_wait(3);
    c_tenna_sprite(spr_tenna_sad_turned_b);
    c_wait(3);
    c_sprite(spr_tenna_sad_turned_a);
    c_wait(5);
    c_tenna_sprite(spr_tenna_sad_turned_b);
    c_wait_talk();
    c_wait(16);
    c_sel(te);
    c_tenna_sprite(spr_tenna_sad);
    c_tenna_preset(0);
    c_var_instance(te_actor, "image_xscale", 2);
    c_wait(15);
    c_var_lerp_instance(te_actor, "image_yscale", 2, 2.1, 20, 3);
    c_var_lerp_instance(te_actor, "image_xscale", 2, 1.9, 20, 3, "in");
    c_wait(30);
    c_var_lerp_instance(te_actor, "image_yscale", 2.1, 1.95, 10, 3, "in");
    c_var_lerp_instance(te_actor, "image_xscale", 1.9, 2.1, 10, 3, "in");
    c_wait(10);
    c_var_lerp_instance(te_actor, "image_yscale", 1.85, 2, 10, -1, "out");
    c_var_lerp_instance(te_actor, "image_xscale", 2.1, 2, 10, -1, "out");
    c_wait(30);
    c_var_instance(te_actor, "image_xscale", -2);
    c_wait(6);
    c_sprite(spr_tenna_hooray);
    c_var_instance(te_actor, "image_index", 2);
    c_wait(3);
    c_tenna_sprite(spr_tenna_shocked_alt);
    c_shakeobj(te_actor);
    c_addxy(0, -16);
    c_wait(5);
    c_tenna_preset(30);
    c_addxy(0, 26);
    c_wait(10);
    c_tenna_preset(0);
    c_var_instance(te_actor, "yscale", 2);
    c_tenna_sprite(spr_tenna_tie_adjust_c);
    c_addxy(0, -14);
    c_wait(9);
    c_sprite(spr_tenna_tie_adjust_a);
    c_wait(3);
    c_sprite(spr_tenna_tie_adjust_b);
    c_wait(3);
    c_sprite(spr_tenna_tie_adjust_a);
    c_wait(3);
    c_sprite(spr_tenna_tie_adjust_b);
    c_wait(3);
    c_sprite(spr_tenna_tie_adjust_a);
    c_wait(10);
    c_sel(te);
    c_tenna_sprite(spr_tenna_tie_adjust_a);
    c_speaker("tenna");
    c_msgsetloc(0, "* K..^1. Kris^1! Hey^1, Kris^1! Kris ol' buddy^1, ol' pal^1! How's it going!/", "obj_ch3_GSC04A_slash_Step_0_gml_164_0");
    c_msgnextloc("* It's uh^1, it's uh^1, it's goin' great^1, isn't it!? Everything's^1, just hunky doody!/", "obj_ch3_GSC04A_slash_Step_0_gml_165_0");
    c_msgnextloc("* Haha..^1. Uh^1, heheh..^1. Where are your^1, uh^1, buddies? Your pals?/", "obj_ch3_GSC04A_slash_Step_0_gml_166_0");
    c_msgnextloc("* By yourself^1, huh? Don't you wanna^1, y'know^1, heheh^1, keep 'em company? Heheh.../%", "obj_ch3_GSC04A_slash_Step_0_gml_167_0");
    c_talk();
    c_wait_box(1);
    c_tenna_sprite(spr_tenna_pose_podium);
    c_tenna_preset(8);
    c_var_instance(te_actor, "image_index", 1);
    c_addxy(-4, 8);
    c_addxy(-16, 0);
    c_wait_box(2);
    c_tenna_sprite(spr_tenna_salute_a);
    c_var_instance(te_actor, "xscale", -2);
    c_addxy(4, 0);
    c_addxy(-16, 0);
    c_wait_box(3);
    c_tenna_preset(9);
    c_tenna_sprite(spr_tenna_pose_podium);
    c_var_instance(te_actor, "xscale", 2);
    c_addxy(-16, 4);
    c_wait_talk();
    c_wait(10);
    c_sel(te);
    c_autowalk(0);
    c_var_lerp_to("x", 260, 30, 1, "out");
    c_wait(31);
    c_addxy(-60, 0);
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_bulletin);
    c_flip("x");
    c_addxy(0, -10);
    c_wait(8);
    c_speaker("tenna");
    c_msgsetloc(0, "* Oh^1, uh^1, hey^1, would you look at that^1! My^1, uh^1, my beeper's going!/%", "obj_ch3_GSC04A_slash_Step_0_gml_219_0");
    c_talk_wait();
    c_tenna_sprite(spr_tenna_laugh_pose);
    c_wait(5);
    c_tenna_preset(8);
    c_var_lerp_instance(te_actor, "wobbleamt", 0, 1, 15);
    c_flip("x");
    c_addxy(-40, 0);
    c_wait(10);
    c_speaker("tenna");
    c_msgsetloc(0, "* You know^1, my silent beeper^1! Haha^1, it's a new one^1! I..^1. I gotta be goin' now!/%", "obj_ch3_GSC04A_slash_Step_0_gml_233_0");
    c_talk_wait();
    c_wait(6);
    c_var_instance(te_actor, "wobbleamt", 0);
    c_addxy(20, 0);
    c_tenna_sprite(spr_tenna_bow);
    c_var_instance(te_actor, "xscale", -2);
    c_var_instance(te_actor, "image_speed", 0.25);
    c_wait(30);
    c_var_instance(te_actor, "xscale", 2);
    c_tenna_sprite(spr_tenna_pose_headraised_nose);
    c_var_lerp_to_instance(te_actor, "x", 160, 20);
    c_wait(20);
    c_var_lerp_to_instance(te_actor, "x", 140, 10, 2, "out");
    c_wait(40);
    c_sprite(spr_tenna_pose_headlowered_nose);
    c_wait(30);
    c_tenna_preset(0);
    c_wait(5);
    c_saveload_s(saveload);
    c_speaker("tenna");
    c_msgsetloc(0, "* By the way..^1. Seen your father recently? Your brother?/", "obj_ch3_GSC04A_slash_Step_0_gml_268_0");
    c_msgnextloc("* You know^1, we still got that cowboy program..^1. The one your dad likes.../%", "obj_ch3_GSC04A_slash_Step_0_gml_269_0");
    c_talk();
    c_wait_box(1);
    c_tenna_sprite(spr_tenna_pose_headraised_nose);
    c_wait_talk();
    c_wait(15);
    c_tenna_preset(30);
    c_addxy(20, 20);
    c_var_lerp_to("x", 300, 15);
    c_var_lerp_instance(te_actor, "image_yscale", 2, 1.5, 7.5, 2, "out");
    c_var_lerp_instance(te_actor, "image_xscale", 2, 2.5, 7.5, 2, "out");
    c_wait(7.5);
    c_var_lerp_instance(te_actor, "image_yscale", 1.5, 2, 7.5, 2, "in");
    c_var_lerp_instance(te_actor, "image_xscale", 2.5, 2, 7.5, 2, "in");
    c_wait(8);
    c_var_instance(te_actor, "xscale", -2);
    c_tenna_preset(32);
    c_tenna_sprite(spr_tenna_pose);
    c_addxy(-20, -20);
    c_addxy(50, 0);
    c_speaker("tenna");
    c_msgsetloc(0, "* He was^1, heh^1, bouncin' you on your knee as you watched it together.../%", "obj_ch3_GSC04A_slash_Step_0_gml_309_0");
    c_talk_wait();
    c_wait(9);
    c_var_lerp_instance(te_actor, "wobbleamt", 6, 0, 9);
    c_wait(20);
    c_tenna_sprite(spr_tenna_shocked);
    c_addxy(-20, -20);
    c_wait(1);
    c_shakeobj(te_actor);
    c_wait(30);
    c_tenna_sprite(spr_tenna_hooray_alt);
    c_addxy(0, 6);
    c_var_instance(te_actor, "image_index", 2);
    c_wait(10);
    c_speaker("tenna");
    c_msgsetloc(0, "* Sorry^1, Kris^1! Sorry^1! I gotta.../", "obj_ch3_GSC04A_slash_Step_0_gml_342_0");
    c_msgnextloc("* I have to go!/%", "obj_ch3_GSC04A_slash_Step_0_gml_343_0");
    c_talk();
    c_wait_box(1);
    c_tenna_sprite(spr_tenna_tie_adjust_b);
    c_wait_talk();
    c_var_lerp_to("x", -300, 20);
    c_tenna_sprite(spr_tenna_hooray_alt);
    c_var_instance(te_actor, "image_index", 2);
    c_saveload_l(saveload);
    c_var_instance(id, "adjust_caterpillar", true);
    c_wait(60);
    c_sel(kr);
    c_facing("d");
    c_actortokris();
    c_terminatekillactors();
}
if (con == 24 && !i_ex(obj_cutscene_master))
{
    global.interact = 0;
    global.facing = 0;
    scr_flag_set(1056, 1);
    con = -1;
}
