event_inherited();
active = false;
image_speed = 0.25;
frozen = false;
frozemem = false;
freezesprite = 4680;
mem_speed = speed;
mem_image_speed = image_speed;
mem_sprite_index = sprite_index;
mem_direction = direction;
mem_hspeed = hspeed;
mem_vspeed = vspeed;
mem_friction = friction;
mem_image_index = image_index;
