scr_darksize(id);
image_speed = 0;
myblock = instance_create(x, y, obj_solidblock);
myblock.sprite_index = sprite_index;
myblock.image_xscale = image_xscale;
myblock.image_yscale = image_yscale;
myblock.image_speed = image_speed;
myblock.visible = false;
myblock2 = instance_create(1200, 424, obj_overworld_lanternflame_wall);
myblock2.image_xscale = 4;
myblock2.image_yscale = 5.1;
scr_depth();
