scr_darksize();
scr_depth_board();
active = true;
myspeed = 0;
chasetype = 0;
daddy = 0;
freeze = 0;
image_speed = 0;
image_index = 0;
facing = 0;
triggered = 0;
pacecon = 0;
pacetimer = 0;
alertradius = 120;
triggeredonstart = true;
extflag = "";
init = 0;
quizno = 0;
camerasettle = 0;
