interact_event = false;
interacting = false;
movecourse = 0;
movetimer = 0;
myinteract = 0;
movespeed = 8;
movetimertarget = 5;
wd = sprite_get_bbox_left(sprite_index) - sprite_get_bbox_right(sprite_index);
ht = sprite_get_bbox_bottom(sprite_index) - sprite_get_bbox_top(sprite_index);
scr_depth();
moveit = false;
against_wall = false;
can_push = !collision_rectangle(x, y, x + sprite_width + 2, y + 5, obj_solidblock, false, true);
shake = false;
auto_depth = true;
