event_inherited();
damage = 18;
target = 3;
timer = 0;
siner = 0;
con = 0;
init = 0;
laser_xscale = 0;
position = "above";
yrange = irandom(400);
laser = -1;
image_xscale = 0.1;
image_yscale = 0.1;
spd = 1 + irandom(5);
lifetime = 30 + irandom(60);
