var count = 0;
var space = 10;
var border = 8;
var _cx = camerax();
var _cy = cameray();
showval(_cx + border, _cy + border + (count * space), "con");
count++;
showval(_cx + border, _cy + border + (count * space), "timer");
count++;
showval(_cx + border, _cy + border + (count * space), "proptrig");
count++;
