var x_base = x + 440;
var x_width = 120;
draw_set_alpha(0.5);
draw_set_color(c_black);
ossafe_fill_rectangle(camerax(), cameray(), camerax() + view_wport[0], cameray() + view_hport[0], false);
draw_set_color(c_white);
draw_set_alpha(1);
gpu_set_blendenable(false);
gpu_set_colorwriteenable(false, false, false, true);
draw_set_alpha(0);
draw_triangle_color(x_base, cameray() - 620, x_base - x_width, cameray() + 280, x_base + x_width, cameray() + 280, c_white, 0, 0, false);
draw_ellipse(x_base - x_width, cameray() + 250, x_base + x_width, cameray() + 310, false);
draw_set_alpha(1);
gpu_set_blendenable(true);
gpu_set_colorwriteenable(true, true, true, true);
gpu_set_blendmode_ext(bm_src_alpha, bm_inv_dest_alpha);
gpu_set_blendmode(bm_normal);
gpu_set_blendmode(bm_add);
draw_set_alpha(1);
draw_triangle_color(x_base, cameray() - 620, x_base - x_width, cameray() + 280, x_base + x_width, cameray() + 280, c_white, 0, 0, false);
draw_set_alpha(0.25);
draw_ellipse(x_base - x_width, cameray() + 250, x_base + x_width, cameray() + 310, false);
draw_set_alpha(1);
gpu_set_blendmode(bm_normal);
