timer = irandom_range(-20, 10);
con = 0;
minspeed = 1;
maxspeed = 5;
special = 0;
boss = 0;
activetarg = 60;
inactivetarg = 60;
image_alpha = 0;
image_index = 0;
image_speed = 0;
scr_darksize();
init = 0;
memspeed = 0;
photod = 0;
hide = 0;
nospecialsanymore = 0;
