active = true;
activedraw = 0;
boarddepth = 999995;
mycolor = hexcolor(#0D0D0D);
drawarray[0] = instance_create_depth(0, 0, boarddepth, obj_board_marker);
drawarray[0].sprite_index = spr_board_erasermarker;
drawarray[0].image_blend = mycolor;
scr_darksize();
wavy = true;
timer = 0;
eraserate = 2;
eraseall = false;
depth = -99;
wavyrate = 6;
