subcon = 0;
con = 0;
schoose = 0;
rchoose = 0;
ralseicoord = 0;
susiecoord = 0;
myanswer = -1;
rtimer = 0;
stimer = 0;
stimer2 = 0;
choicepitch = 0.9;
commenttimer = 0;
commentqueue = 20;
endtimer = 60;
susbuffer = 0;
ralbuffer = 0;
rsel = false;
ssel = false;
menucoord[0] = 0;
ra_wait = 300;
su_wait = 300;
rtarget = 0;
starget = 0;
sCon = 0;
rCon = 0;
teambuffer = 0;
bufferedcoord = 0;
turntimer = 0;
commentshown = 0;
flashtimer = 0;
buffer = 0;
ktimer = 0;
sprite = -4;
postcomment = 0;
with (quizzler)
    event_user(0);
quizno = quizQs[quiz_index];
scr_quiztext(quizno);
var _correct_pose = q_correct >= 2 || correct;
scr_createquizcomment(stringsetloc("Next question!", "obj_quizsequence_slash_Other_12_gml_39_0"), 0, 30, quizzler.tenna_podium, _correct_pose ? 2 : 4);
tenna_timer = 50;
q_correct = 0;
