gpu_set_blendenable(false);
gpu_set_colorwriteenable(false, false, false, true);
draw_set_alpha(overlay_alpha);
draw_set_color(c_black);
ossafe_fill_rectangle(-10, -10, room_width + 10, room_height + 10);
draw_set_color(c_white);
draw_set_alpha(1);
draw_set_alpha(0);
draw_triangle_color(x, y_pos - 620, x - 140, y_pos + 270, x + 140, y_pos + 270, c_white, 0, 0, false);
draw_ellipse(x - 140, y_pos + 240, x + 140, y_pos + 300, false);
draw_set_alpha(1);
gpu_set_blendenable(true);
gpu_set_colorwriteenable(true, true, true, true);
gpu_set_blendmode_ext(bm_src_alpha, bm_inv_dest_alpha);
draw_set_alpha(0);
draw_set_color(c_black);
ossafe_fill_rectangle(-10, -10, room_width + 10, room_height + 10);
draw_set_color(c_white);
draw_set_alpha(1);
gpu_set_blendmode(bm_normal);
gpu_set_blendmode(bm_add);
draw_set_alpha(0.5);
draw_triangle_color(x, y_pos - 620, x - 140, y_pos + 270, x + 140, y_pos + 270, c_white, 0, 0, false);
draw_set_alpha(1);
gpu_set_blendmode(bm_normal);
