scr_depth();
siner = 0;
image_xscale = 2;
image_yscale = 2;
siner = random(600);
blocktimer = 0;
image_speed = 0;
spec = 0;
remdepth = depth;
myinteract = 0;
con = 0;
here = true;
buffer = 0;
_yes = stringsetloc("YES", "obj_blocktree_dmg_slash_Create_0_gml_17_0");
_no = stringsetloc("NO", "obj_blocktree_dmg_slash_Create_0_gml_18_0");
_fail = stringsetloc("WHO ARE YOU TALKING TO?/%", "obj_blocktree_dmg_slash_Create_0_gml_19_0");
boxtimer = 0;
