scr_darksize(id);
myinteract = 0;
image_speed = 0;
scr_depth();
extflag = 0;
init = 0;
myblock[0] = instance_create(x, y + 80, obj_solid_temp);
myblock[0].image_xscale = 3;
myblock[0].image_yscale = 3;
myblock[0].extflag = "FLOOR1";
myblock[0].active = true;
upstairs[0] = 0;
con = 0;
mydir = -1;
timer = 0;
maxDistance = 16;
moveamount = 0;
timeend = 30;
ladder = 0;
climbpoint = 0;
resetblocks = false;
movetype = 0;
