if (con < 0)
    exit;
if (con == 0 && !i_ex(obj_cutscene_master))
{
    con = 3;
    alarm[0] = 30;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    te = actor_count + 1;
    te_actor = instance_create(camerax() + 720, cameray() + 237, obj_actor_tenna);
    scr_actor_setup(te, te_actor, "tenna");
    te_actor.sprite_index = spr_tenna_laugh_pose;
    te_actor.preset = -1;
    c_var_instance(kris_marker, "visible", 0);
    c_var_instance(susie_marker, "visible", 0);
    c_var_instance(ralsei_marker, "visible", 0);
    c_sel(kr);
    c_sprite(spr_kris_rock_2);
    c_setxy(280, 316);
    c_autodepth(0);
    c_depth(97020);
    c_sel(su);
    c_sprite(spr_susie_drum);
    c_setxy(56, 281);
    c_autodepth(0);
    c_depth(97020);
    c_sel(ra);
    c_sprite(spr_ralsei_rock_1);
    c_setxy(486, 304);
    c_autodepth(0);
    c_depth(97020);
    c_sel(te);
    c_autodepth(0);
    c_depth(97500);
    c_mus2("initloop", "berdly_audience.ogg", 0);
    c_var_instance(audience_cheer, "audience_show", true);
    c_var_instance(audience_cheer, "rose_throw", true);
    c_wait(30);
    c_sel(ra);
    c_sprite(spr_ralsei_rock_pose);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EH* Wow^1, they loved it^1! I'm starting to feel like a real rocker!/", "obj_victory_rhythm_slash_Step_0_gml_20_0");
    c_facenext("susie", "9");
    c_msgnextloc("\\E9* Yeah^1, that was sick^1! Though^1, uh.../", "obj_victory_rhythm_slash_Step_0_gml_22_0");
    c_msgnextloc("\\EL* Lucky I was carrying you guys. We barely passed./%", "obj_victory_rhythm_slash_Step_0_gml_23_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_susie_drum_ready);
    c_wait_box(3);
    c_sel(su);
    c_sprite(spr_susie_drum);
    c_sel(ra);
    c_sprite(spr_ralsei_rock_surprise);
    c_wait_talk();
    c_wait(30);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EK* S-Susie...? Are you serious right now...?/%", "obj_victory_rhythm_slash_Step_0_gml_29_0");
    c_talk_wait();
    c_sel(ra);
    c_sprite(spr_ralsei_rock_1);
    c_sel(te);
    c_var_lerp_to_instance(te_actor, "x", 334, 10, 2, "out");
    c_speaker("tenna");
    c_msgsetloc(0, "* Wow^1, looks like the band's already splitting up due to drama!/%", "obj_victory_rhythm_slash_Step_0_gml_35_0");
    c_talk_wait();
    c_tenna_preset(21);
    c_speaker("tenna");
    c_msgsetloc(0, "* That's how you know we've got a REAL winner on our hands^1, folks!/", "obj_victory_rhythm_slash_Step_0_gml_41_0");
    c_msgnextloc("* Anyway^1, BOARD'S OVER^1! So without further ado.../", "obj_victory_rhythm_slash_Step_0_gml_42_0");
    c_msgnextloc("* Let's see those RESULTS!!!/%", "obj_victory_rhythm_slash_Step_0_gml_43_0");
    c_talk();
    c_wait_box(1);
    c_tenna_preset(-1);
    c_tenna_sprite(spr_tenna_laugh_pose);
    c_mus2("volume", 0, 30);
    c_var_instance(audience_cheer, "rose_throw", false);
    c_var_instance(audience_cheer, "audience_hide", true);
    c_wait_box(2);
    c_snd_play(snd_jump);
    c_tenna_preset(0);
    c_sel(te);
    c_sprite(spr_tenna_attack);
    c_var_instance(te_actor, "x", 407);
    c_var_instance(te_actor, "scaled_bounce", true);
    c_var_lerp_to_instance(te_actor, "image_xscale", 3, 16);
    c_var_lerp_to_instance(te_actor, "image_yscale", 3, 16);
    c_var_lerp_to_instance(te_actor, "x", 333, 16);
    c_var_lerp_to_instance(te_actor, "y", 200, 8, 1, "out");
    c_wait(9);
    c_sel(te);
    c_depth(95000);
    c_var_lerp_to_instance(te_actor, "y", 440, 8, 1, "in");
    c_tenna_preset(0);
    c_tenna_sprite(spr_tenna_point_at_screen);
    c_wait_talk();
    c_waitcustom();
}
if (con == 4 && !d_ex() && customcon == 1)
{
    con = -1;
    global.plot = 140;
    scr_script_delayed(snd_free_all, 30);
    instance_create(0, 100, obj_round_evaluation);
}
