scr_darksize();
image_speed = 0.25;
x = obj_susiezilla_statue.x;
y = obj_susiezilla_statue.y - 120 - 1200;
anchor_x = x;
anchor_y = y;
angle = 240;
anglechange = 0.75;
DESTROY = false;
snd_play_x(snd_drive, 1, 0.75);
