scr_darksize();
image_speed = 0;
image_index = choose(0, 1);
con = 0;
boatsolid = instance_create(x, y, obj_board_boatsolid);
scr_darksize(boatsolid);
boatsolid.sprite_index = sprite_index;
buffer = 0;
grabbed = false;
decor = false;
updatedepth = true;
makesolid = false;
siner = 0 + irandom(5);
depth = 999990;
active = false;
