event_inherited();
timer = 0;
active = 1;
damage = 1;
timermax = 37;
anglespeed = 0;
image_speed = 1;
sprite_index = spr_gerson_star7;
image_angle = irandom(360);
image_xscale = 0;
image_yscale = 0;
var aa = choose(5, 6, 7, 8, 9, 10);
scr_script_delayed(scr_lerpvar, 1, "image_xscale", 0, 1.5, aa);
scr_script_delayed(scr_lerpvar, 1, "image_yscale", 0, 1.5, aa);
