init = 0;
siner = 0;
active = 0;
image_alpha = 0;
church = 1;
relx = x;
rely = y;
xx = camerax() + relx;
yy = cameray() + rely;
depth = 699990;
angle = 0;
surf0 = -4;
surf1 = -4;
surf2 = -4;
destroy = 0;
destroykind = 1;
text_sprite = -4;
prophecy_text = instance_create(0, 0, obj_dw_church_prophecy_custom);
icon_sprite = -4;
prophecy_icon = instance_create(0, 0, obj_dw_church_prophecy_custom);
musickind = 0;
extflag = "initial2";
falltest = false;
hitstop = 2;
drawback = false;
notext = false;
textonly = false;
alwaysactive = false;
noback = false;
fade_edges = false;
nodestroysound = false;
nodestroysecondsound = false;
nodestroysparkles = false;
breakdelay = -1;
if (scr_debug() && room == room_darkness_example)
{
    destroykind = 2;
    hitstop = 10;
}
notearray = [];
array_push(notearray, "a");
array_push(notearray, "i");
array_push(notearray, "b");
array_push(notearray, "j");
array_push(notearray, "c");
array_push(notearray, "k");
array_push(notearray, "d");
array_push(notearray, "l");
array_push(notearray, "e");
array_push(notearray, "m");
array_push(notearray, "f");
array_push(notearray, "n");
array_push(notearray, "g");
array_push(notearray, "o");
array_push(notearray, "h");
pitcharray = [];
array_push(pitcharray, 1);
array_push(pitcharray, 0.5);
array_push(pitcharray, 1.125);
array_push(pitcharray, 0.5625);
array_push(pitcharray, 1.25);
array_push(pitcharray, 0.625);
array_push(pitcharray, 4/3);
array_push(pitcharray, 2/3);
array_push(pitcharray, 1.5);
array_push(pitcharray, 0.75);
array_push(pitcharray, 1.6666666666666667);
array_push(pitcharray, 0.8333333333333334);
array_push(pitcharray, 1.875);
array_push(pitcharray, 0.9375);
array_push(pitcharray, 2);
dirarray = [];
array_push(dirarray, 0);
array_push(dirarray, 0);
array_push(dirarray, 1);
array_push(dirarray, 1);
array_push(dirarray, 0);
array_push(dirarray, 0);
array_push(dirarray, 0);
array_push(dirarray, 0);
array_push(dirarray, 3);
array_push(dirarray, 3);
array_push(dirarray, 3);
array_push(dirarray, 3);
array_push(dirarray, 2);
array_push(dirarray, 2);
array_push(dirarray, 2);
indarray = [];
array_push(indarray, 2);
array_push(indarray, 5);
array_push(indarray, 0);
array_push(indarray, 3);
array_push(indarray, 1);
array_push(indarray, 4);
array_push(indarray, 0);
array_push(indarray, 3);
array_push(indarray, 1);
array_push(indarray, 4);
array_push(indarray, 0);
array_push(indarray, 3);
array_push(indarray, 1);
array_push(indarray, 4);
array_push(indarray, 0);
actuallyactive = false;
