if (con < 0)
    exit;
if (con == 1)
{
    con = 10;
    global.interact = 1;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    su = actor_count + 1;
    su_actor = instance_create(402, 510, obj_actor);
    scr_actor_setup(su, su_actor, "susie");
    su_actor.sprite_index = spr_susie_guitar_oops;
    no = actor_count + 2;
    no_actor = instance_create(450, 515, obj_actor);
    scr_actor_setup(no, no_actor, "noelle");
    no_actor.sprite_index = spr_noelle_sit_expressions;
    as = actor_count + 3;
    as_actor = instance_create(610, 485, obj_actor);
    scr_actor_setup(as, as_actor, "asgore");
    as_actor.sprite_index = spr_asgore_walk_left_housekeeper_gloveless;
    ca = actor_count + 4;
    ca_actor = instance_create(610, 485, obj_actor);
    scr_actor_setup(ca, ca_actor, "asgore");
    ca_actor.sprite_index = spr_carol_walk_left;
    c_sel(ca);
    c_visible(0);
    if (scr_debug())
    {
        if (global.tempflag[90] == 1)
        {
            con = 20;
            c_pannable(1);
            c_pan(320, 420, 1);
            c_wait(1);
            c_sel(kr);
            c_setxy(430, 346);
            c_visible(1);
            c_halt();
            c_sel(as);
            c_autowalk(0);
            c_autodepth(0);
            c_depth(81000);
            c_sprite(spr_asgore_housekeeper_eating);
            c_imagespeed(0.2);
            c_setxy(455, 503);
            c_sel(no);
            c_autodepth(0);
            c_autowalk(0);
            c_depth(80000);
            c_sprite(spr_noelle_stressed);
            c_halt();
            c_setxy(434, 523);
            c_sel(su);
            c_autodepth(0);
            c_depth(80000);
            c_sprite(spr_susie_guitar_look_right_neutral);
            c_setxy(402, 510);
            c_var_instance(blackall, "image_alpha", 0);
            c_var_instance(snacktray_marker, "visible", 0);
        }
        if (global.tempflag[90] == 2)
        {
            con = 30;
            c_sel(kr);
            c_setxy(565, 485);
            c_visible(1);
            c_halt();
            c_var_instance(blackall, "image_alpha", 0);
            c_pannable(1);
            c_panobj(kr_actor, 1);
            c_wait(1);
            c_pannable(0);
            c_actortokris();
            c_terminatekillactors();
        }
    }
    c_waitcustom();
}
if (con == 10 && customcon == 1)
{
    con = 20;
    customcon = 0;
    c_waitcustom_end();
    c_sel(su);
    c_autodepth(0);
    c_depth(couch_marker.depth - 10);
    c_sel(no);
    c_autodepth(0);
    c_depth(couch_marker.depth - 20);
    c_pannable(1);
    c_pan(282, 233, 1);
    c_sel(kr);
    c_setxy(430, 325);
    c_visible(0);
    c_halt();
    c_wait(1);
    c_var_lerp_instance(blackall, "image_alpha", 1, 0.5, 14);
    c_wait(30);
    c_visible(1);
    c_soundplay(snd_dooropen);
    c_var_instance(door_marker, "image_index", 1);
    c_wait(5);
    c_soundplay(snd_doorclose);
    c_var_instance(door_marker, "image_index", 0);
    c_sel(kr);
    c_walkdirect_wait(430, 346, 15);
    c_snd_play(snd_susie_strum_01);
    c_wait(15);
    c_speaker("susie");
    c_fefc(0, 0);
    c_msgsetloc(0, "* Hey^1, just so you know^1, me and Kris were in a band.../", "obj_ch4_PDC14C_slash_Step_0_gml_150_0");
    c_msgnextloc("* So don't be surprised if I'm pretty good./%", "obj_ch4_PDC14C_slash_Step_0_gml_151_0");
    c_talk_wait();
    c_pan_wait(282, 420, 90);
    c_wait(30);
    c_snd_play(snd_susie_strum_mistake);
    c_sel(su);
    c_autowalk(0);
    c_lerpvar_instance(su_actor, "image_index", 0, 3, 8);
    c_wait(9);
    c_wait(30);
    c_sprite(spr_susie_guitar_look_away);
    c_speaker("susie");
    c_msgsetloc(0, "\\EE* Oops./%", "obj_ch4_PDC14C_slash_Step_0_gml_180_0");
    c_talk_wait();
    c_sel(no);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_noelle_sit_chuckle);
    c_wait(60);
    c_sprite(spr_noelle_sit_expressions);
    c_halt();
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right_neutral);
    c_msgside("top");
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* ..^1. sure you wanna hear this?/", "obj_ch4_PDC14C_slash_Step_0_gml_197_0");
    c_facenext("noelle", "2");
    c_msgnextloc("\\E2* Huh? Yeah^1, of course^1! I.../", "obj_ch4_PDC14C_slash_Step_0_gml_199_0");
    c_msgnextloc("\\E9* I just always liked..^1. listening to someone play./", "obj_ch4_PDC14C_slash_Step_0_gml_200_0");
    c_facenext("susie", "7");
    c_msgnextloc("\\E7* Heh^1, okay. Then check this out./%", "obj_ch4_PDC14C_slash_Step_0_gml_202_0");
    c_talk();
    c_wait_box(2);
    c_sel(no);
    c_sprite(spr_noelle_sit_blush_expressions);
    c_halt();
    c_wait_box(3);
    c_sel(no);
    c_sprite(spr_noelle_sit_expressions);
    c_imageindex(8);
    c_wait_box(5);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right);
    c_sel(no);
    c_sprite(spr_noelle_sit_blush_expressions);
    c_imageindex(2);
    c_wait_talk();
    c_snd_play(snd_susie_strum_02);
    c_sel(su);
    c_sprite(spr_susie_guitar_strum);
    c_halt();
    c_lerpvar_instance(su_actor, "image_index", 0, 4, 12);
    c_wait(60);
    c_sel(su);
    c_sprite(spr_susie_guitar_proud);
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* Dude^1, I actually kind of kicked ass with that one./", "obj_ch4_PDC14C_slash_Step_0_gml_239_0");
    c_facenext("noelle", 26);
    c_msgnextloc("\\EQ* Faha^1! Can we get an encore?/", "obj_ch4_PDC14C_slash_Step_0_gml_241_0");
    c_facenext("susie", 2);
    c_msgnextloc("\\E2* Heh. Just for my fans./%", "obj_ch4_PDC14C_slash_Step_0_gml_243_0");
    c_talk();
    c_wait_box(2);
    c_sel(no);
    c_sprite(spr_noelle_sit_chuckle);
    c_imagespeed(0.2);
    c_wait_box(4);
    c_sel(no);
    c_halt();
    c_sprite(spr_noelle_sit_expressions);
    c_halt();
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right);
    c_wait_talk();
    c_snd_play(snd_susie_strum_mistake);
    c_sel(su);
    c_sprite(spr_susie_guitar_oops);
    c_halt();
    c_lerpvar_instance(su_actor, "image_index", 0, 3, 8);
    c_wait(9);
    c_sel(no);
    c_autowalk(0);
    c_sprite(spr_noelle_sit_surprise_down);
    c_imageindex(0);
    c_wait(6);
    c_imageindex(1);
    c_sel(su);
    c_sprite(spr_susie_guitar_oops_look);
    c_wait(30);
    c_sel(no);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_noelle_sit_chuckle);
    c_wait(30);
    c_speaker("noelle");
    c_msgsetloc(0, "\\ER* Fahaha!/", "obj_ch4_PDC14C_slash_Step_0_gml_290_0");
    c_facenext("susie", 20);
    c_msgnextloc("\\EK* Shut up. That was the remix./%", "obj_ch4_PDC14C_slash_Step_0_gml_292_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right_neutral);
    c_halt();
    c_wait_talk();
    c_sel(no);
    c_sprite(spr_noelle_sit_expressions);
    c_halt();
    c_wait(15);
    c_snd_play(snd_susie_strum_01);
    c_sel(su);
    c_sprite(spr_susie_guitar_strum);
    c_halt();
    c_lerpvar_instance(su_actor, "image_index", 0, 4, 12);
    c_wait(30);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right);
    c_speaker("susie");
    c_msgsetloc(0, "\\EA* Man^1, today's been awesome./%", "obj_ch4_PDC14C_slash_Step_0_gml_321_0");
    c_talk_wait();
    c_sel(su);
    c_sprite(spr_susie_guitar_look_away);
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* ..^1. Not to^1, be weird. Or anything./%", "obj_ch4_PDC14C_slash_Step_0_gml_334_0");
    c_talk_wait();
    c_wait(30);
    c_sel(no);
    c_imageindex(1);
    c_var_instance(id, "susie_play_loop", true);
    c_sel(su);
    c_halt();
    c_imagespeed(0.2);
    c_sprite(spr_susie_guitar_strum);
    c_speaker("noelle");
    c_msgsetloc(0, "\\E3* Umm^1, it's..^1. It's not weird at all!/", "obj_ch4_PDC14C_slash_Step_0_gml_352_0");
    c_msgnextloc("\\E6* I..^1. really like hanging out with you^1, too^1, Susie./%", "obj_ch4_PDC14C_slash_Step_0_gml_353_0");
    c_talk();
    c_wait_box(1);
    c_sel(no);
    c_sprite(spr_noelle_sit_blush_expressions);
    c_imageindex(2);
    c_wait_talk();
    c_wait(15);
    c_var_instance(id, "susie_play_loop", false);
    c_sel(su);
    c_halt();
    c_sprite(spr_susie_guitar_look_right);
    c_speaker("susie");
    c_msgsetloc(0, "\\EA* Sweet. Maybe we could like..^1. I dunno./%", "obj_ch4_PDC14C_slash_Step_0_gml_373_0");
    c_talk_wait();
    c_sel(su);
    c_sprite(spr_susie_guitar_look_away);
    c_sel(no);
    c_imageindex(0);
    c_speaker("susie");
    c_msgsetloc(0, "\\EL* Hang out again tomorrow or something./%", "obj_ch4_PDC14C_slash_Step_0_gml_389_0");
    c_talk_wait();
    c_sel(no);
    c_shakeobj();
    c_imageindex(3);
    c_wait(6);
    c_imageindex(4);
    c_wait(30);
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise);
    c_imageindex(1);
    c_wait(30);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_away);
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* Uhh..^1. unless you're busy?/", "obj_ch4_PDC14C_slash_Step_0_gml_411_0");
    c_facenext("noelle", 26);
    c_msgnextloc("\\EQ* Umm^1, no^1! I'm not busy^1, it's just.../", "obj_ch4_PDC14C_slash_Step_0_gml_413_0");
    c_msgnextloc("\\E6* Tomorrow is..^1. well..^1. it's the festival^1, Susie./", "obj_ch4_PDC14C_slash_Step_0_gml_414_0");
    c_facenext("susie", "6");
    c_msgnextloc("\\E6* Oh. Yeah^1, I.../%", "obj_ch4_PDC14C_slash_Step_0_gml_416_0");
    c_talk();
    c_wait_box(2);
    c_sel(no);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_noelle_sit_chuckle);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right);
    c_wait_box(3);
    c_sel(no);
    c_sprite(spr_noelle_sit_expressions);
    c_halt();
    c_wait_box(5);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_away);
    c_wait_talk();
    c_sel(no);
    c_sprite(spr_noelle_sit_expressions);
    c_imageindex(7);
    c_wait(60);
    c_sel(no);
    c_imageindex(1);
    c_wait(4);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right_neutral);
    c_sel(no);
    c_imageindex(0);
    c_speaker("noelle");
    c_msgsetloc(0, "\\EO* Would you.../", "obj_ch4_PDC14C_slash_Step_0_gml_458_0");
    c_msgnextloc("\\ES* Would you want to go..^1. together...?/", "obj_ch4_PDC14C_slash_Step_0_gml_459_0");
    c_facenext("susie", 6);
    c_msgnextloc("\\E6* I.../%", "obj_ch4_PDC14C_slash_Step_0_gml_461_0");
    c_talk();
    c_wait_box(1);
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise);
    c_imageindex(1);
    c_wait_box(3);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_away);
    c_wait_talk();
    c_wait(30);
    c_snd_play(snd_noise);
    c_var_instance(blackall, "image_alpha", 0);
    c_sel(su);
    c_emote("!", 30, 10, 1);
    c_sprite(spr_susie_guitar_surprise_down);
    c_sel(no);
    c_emote("!", 30);
    c_autowalk(0);
    c_sprite(spr_noelle_sit_surprise_down);
    c_imageindex(0);
    c_wait(6);
    c_imageindex(1);
    c_wait(30);
    c_speaker("noelle");
    c_msgsetloc(0, "\\EG* ...?/", "obj_ch4_PDC14C_slash_Step_0_gml_501_0");
    c_msgnextloc("\\EF* The lights...?/%", "obj_ch4_PDC14C_slash_Step_0_gml_502_0");
    c_talk_wait();
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise);
    c_sel(no);
    c_sprite(spr_noelle_sit_strangleface);
    c_imageindex(1);
    c_speaker("asgore");
    c_msgsetloc(0, "\\E5* Oh^1, yes^1, someone had turned them off!/%", "obj_ch4_PDC14C_slash_Step_0_gml_513_0");
    c_talk_wait();
    c_pan_wait(320, 420, 30);
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise);
    c_sel(no);
    c_sprite(spr_noelle_sit_strangleface);
    c_imageindex(1);
    c_sel(as);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_walkdirect_wait(557, as_actor.y, 30);
    c_sprite(spr_asgore_walk_down_housekeeper_gloveless);
    c_walkdirect_wait(557, 515, 30);
    c_sprite(spr_asgore_walk_left_housekeeper_gloveless);
    c_halt();
    c_sel(no);
    c_sprite(spr_noelle_sit_strangleface_forward);
    c_imageindex(2);
    c_speaker("noelle");
    c_msgsetloc(0, "\\EI* Umm..^1. hello^1, Mr. Dreemurr!/", "obj_ch4_PDC14C_slash_Step_0_gml_541_0");
    c_facenext("asgore", 1);
    c_msgnextloc("\\E1* I don't mean to interrupt your schoolwork^1, but.../%", "obj_ch4_PDC14C_slash_Step_0_gml_543_0");
    c_talk_wait();
    c_sel(as);
    c_imagespeed(0.2);
    c_walkdirect_wait(492, 515, 30);
    c_sprite(spr_asgore_walk_down_housekeeper_gloveless);
    c_halt();
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise_down);
    c_sel(no);
    c_sprite(spr_noelle_sit_expressions);
    c_imageindex(6);
    c_speaker("asgore");
    c_msgsetloc(0, "\\E3* Is that..^1. a snack tray...?/", "obj_ch4_PDC14C_slash_Step_0_gml_560_0");
    c_facenext("noelle", "H");
    c_msgnextloc("\\EH* Um..^1. yes. Feel free to..^1. have some./", "obj_ch4_PDC14C_slash_Step_0_gml_562_0");
    c_facenext("asgore", 5);
    c_msgnextloc("\\E5* Don't mind if I do!/%", "obj_ch4_PDC14C_slash_Step_0_gml_564_0");
    c_talk();
    c_wait_box(2);
    c_wait_talk();
    c_sel(as);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_asgore_walk_down_housekeeper_gloveless);
    c_imagespeed(0.25);
    c_walkdirect_wait(455, 540, 15);
    c_halt();
    c_wait(15);
    c_sprite(spr_asgore_housekeeper_snacktray_grab_ready);
    c_autodepth(0);
    c_depth(0);
    c_imageindex(0);
    c_addxy(0, 8);
    c_wait(6);
    c_imageindex(1);
    c_wait(6);
    c_imageindex(2);
    c_addxy(0, -8);
    c_soundplay(snd_noise);
    c_var_instance(snacktray_marker, "visible", 0);
    c_wait(6);
    c_imageindex(3);
    c_wait(6);
    c_imageindex(4);
    c_wait(6);
    c_imageindex(5);
    c_walkdirect(455, 531, 8);
    c_wait(7);
    c_depth(94000);
    c_sprite(spr_asgore_housekeeper_snacktray_down);
    c_snd_play(snd_jump);
    c_jump(455, 503, 12, 12);
    c_wait(2);
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise);
    c_sel(no);
    c_sprite(spr_noelle_sit_strangleface);
    c_imageindex(1);
    c_wait(4);
    c_imageindex(0);
    c_wait(4);
    c_sprite(spr_noelle_sit_nudge);
    c_halt();
    c_var_lerp_to("image_index", 2, 6);
    c_var_lerp_to_instance(no_actor, "x", 428, 12, 3, "out");
    c_wait(2);
    c_sel(as);
    c_autodepth(0);
    c_depth(81000);
    c_sprite(spr_asgore_housekeeper_snacktray_sit);
    c_halt();
    c_wait(15);
    c_sprite(spr_asgore_housekeeper_eating);
    c_imagespeed(0.25);
    c_script_instance(id, snd_play, 15, snd_swallow);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_away);
    c_wait(60);
    c_speaker("asgore");
    c_msgsetloc(0, "\\E0* Phew^1, cleaning sure does work up an appetite!/", "obj_ch4_PDC14C_slash_Step_0_gml_676_0");
    c_msgnextloc("\\E6* Figured I'd get in a bite before your mother's home./", "obj_ch4_PDC14C_slash_Step_0_gml_677_0");
    c_facenext("noelle", 4);
    c_msgnextloc("\\E4* Oh^1, well..^1. umm^1, there's no rush^1, you know./", "obj_ch4_PDC14C_slash_Step_0_gml_679_0");
    c_msgnextloc("\\E4* She has work. She's not going to be home for hours./%", "obj_ch4_PDC14C_slash_Step_0_gml_680_0");
    c_talk();
    c_wait_box(3);
    c_sel(no);
    c_imageindex(5);
    c_wait_talk();
    c_script_instance_stop(id, snd_play);
    c_sel(as);
    c_halt();
    c_wait(30);
    c_sprite(spr_asgore_housekeeper_eating_look_left);
    c_speaker("asgore");
    c_msgsetloc(0, "\\E2* What do you mean?/", "obj_ch4_PDC14C_slash_Step_0_gml_701_0");
    c_msgnextloc("\\E1* I just saw her outside the window./%", "obj_ch4_PDC14C_slash_Step_0_gml_702_0");
    c_talk_wait();
    c_sel(no);
    c_imageindex(3);
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise);
    c_wait(30);
    c_sel(no);
    c_sprite(spr_noelle_sit_stressed);
    c_halt();
    c_wait(30);
    c_sel(no);
    c_imageindex(1);
    c_speaker("noelle");
    c_msgsetloc(0, "\\EB* Mom.. Mom is...?/%", "obj_ch4_PDC14C_slash_Step_0_gml_722_0");
    c_talk_wait();
    c_sel(no);
    c_autodepth(0);
    c_depth(80990);
    c_halt();
    c_sprite(spr_noelle_walk_down_lw);
    c_soundplay(snd_wing);
    c_sprite(spr_noelle_walk_up_lw);
    c_walkdirect_wait(434, 523, 5);
    c_shakeobj();
    c_sprite(spr_noelle_stressed);
    c_halt();
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise_down);
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_eating);
    c_imagespeed(0.2);
    c_sel(no);
    c_var_lerp_to("image_index", 2, 8);
    c_msgside("top");
    c_speaker("noelle");
    c_msgsetloc(0, "\\EB* Susie^1, I.../%", "obj_ch4_PDC14C_slash_Step_0_gml_763_0");
    c_talk_wait();
    c_sel(no);
    c_var_lerp_to("image_index", 5, 8);
    c_speaker("noelle");
    c_msgsetloc(0, "\\EC* Susie^1, I'm sorry^1, I think you should--/%", "obj_ch4_PDC14C_slash_Step_0_gml_771_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 20 && customcon == 1 && !d_ex())
{
    con = 21;
    customcon = 0;
    c_waitcustom_end();
    c_snd_play(snd_dooropen);
    c_wait(15);
    c_soundplay_x(snd_step1, 0.5, 1);
    c_wait(10);
    c_soundplay_x(snd_step2, 0.5, 1);
    c_wait(10);
    c_soundplay_x(snd_step1, 1, 1);
    c_wait(10);
    c_soundplay_x(snd_step2, 1, 1);
    c_wait(10);
    c_soundplay_x(snd_step1, 1.5, 1);
    c_wait(10);
    c_soundplay_x(snd_step2, 1.5, 1);
    c_sel(no);
    c_imageindex(5);
    c_sel(su);
    c_sprite(spr_susie_guitar_surprise_more);
    c_sel(ca);
    c_setxy(640, 500);
    c_autowalk(0);
    c_visible(1);
    c_wait(30);
    c_pan(360, 420, 60);
    c_wait(75);
    c_sprite(spr_carol_walk_left);
    c_imagespeed(0.2);
    c_walkdirect(614, 500, 40);
    c_delaycmd(41, "imagespeed", 0);
    c_wait(10);
    c_soundplay_x(snd_step1, 1.5, 1);
    c_wait(10);
    c_soundplay_x(snd_step2, 1.5, 1);
    c_wait(10);
    c_soundplay_x(snd_step1, 1.5, 1);
    c_wait(10);
    c_soundplay_x(snd_step2, 1.5, 1);
    c_halt();
    c_mus2("initloop", "carol_appeared.ogg", 0);
    c_wait(30);
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_eating_shocked);
    c_halt();
    c_wait(60);
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_snacktray_sit_right);
    c_msgside("bottom");
    c_speaker("asgore");
    c_msgsetloc(0, "\\E5* Hello^1, Carol!/%", "obj_ch4_PDC14C_slash_Step_0_gml_866_0");
    c_talk_wait();
    c_wait(15);
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_eating);
    c_imagespeed(0.2);
    c_sel(no);
    c_autowalk(0);
    c_sprite(spr_noelle_walk_right_stressed);
    c_halt();
    c_wait(5);
    c_imagespeed(0.2);
    c_walkdirect(553, 523, 40);
    c_delaycmd(41, "imagespeed", 0);
    c_delaycmd(41, "imageindex", 0);
    c_sel(ca);
    c_autodepth(0);
    c_depth(70000);
    c_imagespeed(0.2);
    c_walkdirect_wait(580, 500, 30);
    c_sprite(spr_carol_walk_down);
    c_walkdirect_wait(580, 518, 15);
    c_sprite(spr_carol_walk_left);
    c_halt();
    c_sel(no);
    c_sprite(spr_noelle_walk_right_stressed);
    c_speaker("noelle");
    c_msgsetloc(0, "\\ED* Mom^1, I--%%", "obj_ch4_PDC14C_slash_Step_0_gml_901_0");
    c_talk_wait();
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_eating_shocked);
    c_halt();
    c_sel(ca);
    c_sprite(spr_carol_walk_left_mad);
    c_sel(no);
    c_sprite(spr_noelle_head_down_shoulders_raised);
    c_speaker("carol");
    c_msgsetloc(0, "\\E4* You./%", "obj_ch4_PDC14C_slash_Step_0_gml_916_0");
    c_talk_wait();
    c_sel(no);
    c_imageindex(1);
    c_sel(su);
    c_sprite(spr_susie_guitar_look_right_neutral);
    c_sel(ca);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_walkdirect_wait(434, 518, 60);
    c_halt();
    c_speaker("carol");
    c_msgsetloc(0, "\\E5* Get^1. Your hands^1. Off^1. That guitar^1./%", "obj_ch4_PDC14C_slash_Step_0_gml_937_0");
    c_talk_wait();
    var _speed = 4;
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_susie_guitar_grab);
    c_imageindex(1);
    c_delaycmd(4 + _speed, "imageindex", 2);
    c_delaycmd(4 + (_speed * 2), "imageindex", 3);
    c_delaycmd(4 + (_speed * 3), "imageindex", 4);
    c_delaycmd(4 + (_speed * 4), "imageindex", 5);
    c_sel(ca);
    c_autowalk(0);
    c_sprite(spr_carol_guitar_grab);
    c_imageindex(1);
    c_delaycmd(4 + _speed, "imageindex", 2);
    c_delaycmd(4 + (_speed * 2), "imageindex", 3);
    c_delaycmd(4 + (_speed * 3), "imageindex", 4);
    c_delaycmd(4 + (_speed * 4), "imageindex", 5);
    c_wait(5);
    c_snd_play(snd_grab);
    c_wait(25);
    c_sel(ca);
    c_sprite(spr_carol_walk_left_mad_guitar);
    c_wait(30);
    c_sprite(spr_carol_guitar_hold);
    c_wait(60);
    c_sprite(spr_carol_walk_left_mad_guitar);
    c_wait(30);
    c_snd_play(snd_wing);
    c_sel(su);
    c_sprite(spr_susie_walk_down_lw_unhappy);
    c_walkdirect(404, 526, 5);
    c_delaycmd(6, "sprite", spr_susie_walk_right_lw_unhappy);
    c_sel(no);
    c_delaycmd(16, "sprite", spr_noelle_walk_left_unhappy);
    c_delaycmd(16, "imageindex", 0);
    c_sel(ca);
    c_sprite(spr_carol_walk_right_guitar);
    c_imagespeed(0.2);
    c_walkdirect_wait(514, 518, 60);
    c_halt();
    c_sel(su);
    c_imagespeed(0.2);
    c_walkdirect(424, 526, 8);
    c_delaycmd(9, "imagespeed", 0);
    c_delaycmd(9, "imageindex", 0);
    c_speaker("susie");
    c_msgsetloc(0, "\\EZ* H-hey^1, what's your.../%", "obj_ch4_PDC14C_slash_Step_0_gml_1002_0");
    c_talk_wait();
    c_sel(no);
    c_imagespeed(0.2);
    c_walk_wait("l", 4, 4);
    c_halt();
    c_sprite(spr_noelle_left_sad_smile);
    c_speaker("noelle");
    c_msgsetloc(0, "\\EC* She^1, she didn't know^1, mom!%%", "obj_ch4_PDC14C_slash_Step_0_gml_1012_0");
    c_talk_wait();
    c_speaker("noelle");
    c_msgsetloc(0, "\\ED* I..^1. I was the one who gave her the guitar...%%", "obj_ch4_PDC14C_slash_Step_0_gml_1016_0");
    c_talk_wait();
    c_speaker("noelle");
    c_msgsetloc(0, "\\EF* I..^1. I told her to play it^1, I just...%%", "obj_ch4_PDC14C_slash_Step_0_gml_1020_0");
    c_talk_wait();
    c_speaker("noelle");
    c_msgsetloc(0, "\\ED* I just wanted to hear it again^1, and...%%", "obj_ch4_PDC14C_slash_Step_0_gml_1024_0");
    c_talk_wait();
    c_sel(ca);
    c_sprite(spr_carol_walk_right_mad_guitar);
    c_speaker("noelle");
    c_msgsetloc(0, "\\ED* She's not a bad person mom^1, I...%%", "obj_ch4_PDC14C_slash_Step_0_gml_1031_0");
    c_talk_wait();
    c_sel(no);
    c_sprite(spr_noelle_walk_left_lw_neutral);
    c_speaker("carol");
    c_msgsetloc(0, "\\E0* Noelle./%", "obj_ch4_PDC14C_slash_Step_0_gml_1038_0");
    c_talk_wait();
    c_wait(30);
    c_sel(ca);
    c_sprite(spr_carol_walk_right_guitar);
    c_sel(no);
    c_sprite(spr_noelle_left_sad_shock);
    c_speaker("carol");
    c_msgsetloc(0, "\\E6* Kitchen. Now./%", "obj_ch4_PDC14C_slash_Step_0_gml_1050_0");
    c_talk_wait();
    c_wait(30);
    c_sel(no);
    c_sprite(spr_noelle_walk_left_unhappy);
    c_autowalk(0);
    c_walkdirect(552, 523, 12);
    c_imageindex(0);
    c_wait(4);
    c_imageindex(1);
    c_wait(4);
    c_imageindex(0);
    c_wait(4);
    c_sprite(spr_noelle_walk_left_unhappy);
    c_wait(30);
    c_sprite(spr_noelle_walk_up_lw);
    c_wait(15);
    c_sprite(spr_noelle_walk_up_unhappy);
    c_wait(30);
    c_imagespeed(0.2);
    c_walkdirect(545, 460, 60);
    c_delaycmd(61, "imagespeed", 0);
    c_wait(10);
    c_sel(ca);
    c_sprite(spr_carol_walk_right_guitar);
    c_imagespeed(0.2);
    c_walkdirect_wait(564, 518, 30);
    c_sprite(spr_carol_walk_up_mad_guitar);
    c_walkdirect(564, 466, 30);
    c_delaycmd(31, "imagespeed", 0);
    c_delaycmd(31, "imageindex", 0);
    c_sel(su);
    c_autodepth(0);
    c_depth(60000);
    c_sprite(spr_susie_walk_right_lw);
    c_imagespeed(0.4);
    c_walkdirect_wait(562, 528, 30);
    c_sprite(spr_susie_walk_up_lw);
    c_walkdirect_wait(562, 507, 15);
    c_halt();
    c_sel(no);
    c_sprite(spr_noelle_walk_up_lw);
    c_msgside("bottom");
    c_speaker("susie");
    c_msgsetloc(0, "\\ED* Hey^1, listen..^1. Noelle didn't do anything wrong./", "obj_ch4_PDC14C_slash_Step_0_gml_1108_0");
    c_msgnextloc("\\EU* It's my fault. I took the guitar^1, and.../", "obj_ch4_PDC14C_slash_Step_0_gml_1109_0");
    c_facenext("carol", "0");
    c_msgnextloc("\\E0* Leave./", "obj_ch4_PDC14C_slash_Step_0_gml_1111_0");
    c_facenext("susie", "U");
    c_msgnextloc("\\EU* What?/%", "obj_ch4_PDC14C_slash_Step_0_gml_1113_0");
    c_talk();
    c_wait_box(3);
    c_sel(no);
    c_sprite(spr_noelle_walk_up_unhappy);
    c_wait_talk();
    c_sel(ca);
    c_sprite(spr_carol_walk_left_mad_guitar);
    c_wait(15);
    c_sprite(spr_carol_walk_down_mad_guitar);
    c_wait(30);
    c_imagespeed(0.2);
    c_walkdirect(564, 492, 20);
    c_delaycmd(21, "sprite", spr_carol_walk_right_mad_guitar);
    c_delaycmd(21, "imagespeed", 0);
    c_delaycmd(21, "imageindex", 0);
    c_wait(5);
    c_sel(su);
    c_sprite(spr_susie_walk_left_lw_unhappy);
    c_imagespeed(0.2);
    c_walkdirect(600, 500, 20);
    c_delaycmd(21, "imagespeed", 0);
    c_delaycmd(21, "imageindex", 0);
    c_wait(45);
    c_speaker("carol");
    c_msgsetloc(0, "\\E0* You. Are not. Welcome. Leave./%", "obj_ch4_PDC14C_slash_Step_0_gml_1147_0");
    c_talk_wait();
    c_sel(ca);
    c_imagespeed(0.2);
    c_walkdirect_wait(575, 492, 12);
    c_halt();
    c_wait(15);
    c_speaker("carol");
    c_msgsetloc(0, "\\E6* ..^1. And. Don't. Talk. To my daughter. Again./%", "obj_ch4_PDC14C_slash_Step_0_gml_1159_0");
    c_talk_wait();
    c_wait(30);
    c_sel(ca);
    c_imagespeed(0.2);
    c_walkdirect_wait(564, 492, 12);
    c_halt();
    c_wait(15);
    c_imagespeed(0.2);
    c_sprite(spr_carol_walk_up_mad_guitar);
    c_walkdirect(564, 466, 30);
    c_delaycmd(31, "imagespeed", 0);
    c_delaycmd(31, "imageindex", 0);
    c_sel(su);
    c_imagespeed(0.2);
    c_walkdirect_wait(562, 500, 20);
    c_sprite(spr_susie_walk_up_lw);
    c_halt();
    c_speaker("susie");
    c_msgsetloc(0, "\\EV* Hey^1, I can.../", "obj_ch4_PDC14C_slash_Step_0_gml_1182_0");
    c_facenext("noelle", "e");
    c_msgnextloc("\\Ee* Susie^1, just..^1. just go./%", "obj_ch4_PDC14C_slash_Step_0_gml_1184_0");
    c_talk_wait();
    c_sel(su);
    c_shakeobj();
    c_wait(15);
    c_sel(su);
    c_autowalk(0);
    c_wait(1);
    c_sprite(spr_susie_walk_up_lw);
    c_walkdirect(562, 510, 8);
    c_imageindex(1);
    c_wait(4);
    c_imageindex(0);
    c_wait(60);
    c_sprite(spr_susie_walk_right_lw_head_down);
    c_wait(30);
    c_imagespeed(0.2);
    c_walkdirect_wait(583, 510, 30);
    c_halt();
    c_wait(60);
    c_sprite(spr_susie_walk_up_lw);
    c_speaker("susie");
    c_msgsetloc(0, "\\EV* Well..^1. guess who's taking your daughter.../", "obj_ch4_PDC14C_slash_Step_0_gml_1214_0");
    c_msgnextloc("\\EY* To the FESTIVAL tomorrow^1, jerk!?/%", "obj_ch4_PDC14C_slash_Step_0_gml_1215_0");
    c_talk();
    c_wait_box(1);
    c_mus("free_all");
    c_sel(ca);
    c_sprite(spr_carol_guitar_look_back);
    c_delaycmd(4, "imageindex", 1);
    c_sel(su);
    c_sprite(spr_susie_mad_face_up);
    c_imageindex(0);
    c_wait(6);
    c_imageindex(1);
    c_shakeobj();
    c_sel(no);
    c_sprite(spr_noelle_surprise_blush_down);
    c_shakeobj();
    c_wait_talk();
    c_sel(su);
    c_facing("susielight");
    c_autowalk(1);
    c_walkdirect_wait(740, 510, 20);
    c_snd_play(snd_escaped);
    c_wait(30);
    c_sel(ca);
    c_sprite(spr_carol_walk_up_mad_guitar);
    c_halt();
    c_speaker("carol");
    c_msgsetloc(0, "\\E4* .../", "obj_ch4_PDC14C_slash_Step_0_gml_1258_0");
    c_facenext("noelle", 22);
    c_msgnextloc("\\EM* Umm^1, I'll be in the kitchen!/%", "obj_ch4_PDC14C_slash_Step_0_gml_1260_0");
    c_talk_wait();
    c_snd_play(snd_dooropen);
    c_var_instance(kitchen_door_marker, "image_index", 1);
    c_sel(no);
    c_sprite(spr_noelle_walk_up_lw);
    c_imagespeed(0.2);
    c_walkdirect_wait(545, 455, 6);
    c_delaycmd(4, "visible", 0);
    c_wait(5);
    c_snd_play(snd_doorclose);
    c_var_instance(kitchen_door_marker, "image_index", 0);
    c_wait(30);
    c_sel(ca);
    c_sprite(spr_carol_walk_up_mad_guitar);
    c_imagespeed(0.2);
    c_walkdirect(545, 455, 30);
    c_delaycmd(31, "imagespeed", 0);
    c_delaycmd(31, "imageindex", 0);
    c_delaycmd(31, "sprite", spr_carol_walk_up_mad_guitar);
    c_sel(as);
    c_autowalk(0);
    c_sprite(spr_asgore_housekeeper_snacktray_sit_look);
    c_imagespeed(0.1);
    c_wait(60);
    c_wait_if(as_actor, "image_index", "<=", 0);
    c_halt();
    c_speaker("carol");
    c_msgsetloc(0, "\\E0* ..^1. Asgore./", "obj_ch4_PDC14C_slash_Step_0_gml_1298_0");
    c_msgnextloc("\\E6* If you're going to eat the snack tray^1, do it outside./", "obj_ch4_PDC14C_slash_Step_0_gml_1299_0");
    c_facenext("asgore", 5);
    c_msgnextloc("\\E5* Yes^1, Carol!/%", "obj_ch4_PDC14C_slash_Step_0_gml_1301_0");
    c_talk();
    c_wait_box(3);
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_snacktray_sit_right);
    c_wait_talk();
    c_snd_play(snd_dooropen);
    c_var_instance(kitchen_door_marker, "image_index", 1);
    c_sel(ca);
    c_sprite(spr_carol_walk_up_mad_guitar);
    c_imagespeed(0.2);
    c_walkdirect(545, 450, 15);
    c_delaycmd(12, "visible", 0);
    c_wait(13);
    c_snd_play(snd_doorclose);
    c_var_instance(kitchen_door_marker, "image_index", 0);
    c_soundplay(snd_wing);
    c_sel(as);
    c_sprite(spr_asgore_housekeeper_snacktray_down);
    c_walk_wait("u", 2, 2);
    c_wait(5);
    c_imagespeed(0.25);
    c_walkdirect_wait(455, 520, 15);
    c_halt();
    c_wait(5);
    c_sprite(spr_asgore_housekeeper_snacktray_right);
    c_imagespeed(0.25);
    c_walkdirect(558, 520, 20);
    c_delaycmd(21, "sprite", spr_asgore_housekeeper_snacktray_up);
    c_delaywalkdirect(21, 558, 485, 20);
    c_delaycmd(42, "sprite", spr_asgore_housekeeper_snacktray_right);
    c_delaywalkdirect(42, 845, 485, 50);
    c_delaycmd(93, "visible", 0);
    c_delaycmd(93, "soundplay", snd_escaped);
    c_waitcustom();
}
if (con == 21 && !d_ex() && customcon == 1)
{
    con = 23;
    customcon = 0;
    c_waitcustom_end();
    c_pan_wait(282, 420, 90);
    c_panobj(kr_actor, 60);
    c_wait(61);
    c_pannable(0);
    c_actortokris();
    c_terminatekillactors();
}
if (con == 23 && !i_ex(obj_cutscene_master))
    con = 30;
if (susie_play_loop)
{
    susie_play_timer++;
    if (susie_play_timer == 1)
    {
        snd_play(susie_play_tracks[susie_play_index]);
        susie_play_index = scr_wrap(susie_play_index + 1, 0, array_length(susie_play_tracks) - 1);
    }
    if (susie_play_timer >= 26)
        susie_play_timer = 0;
}
if (con == 30)
{
    con = 31;
    global.interact = 0;
    block_doors();
}
if (con == 31 && obj_mainchara.x >= 720 && obj_mainchara.y >= 460)
{
    con = 50;
    global.interact = 1;
}
if (con == 50)
{
    con = 51;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    ca = actor_count + 1;
    ca_actor = instance_create(544, -100, obj_actor);
    scr_actor_setup(ca, ca_actor, "carol");
    ca_actor.sprite_index = spr_carol_walk_down;
    c_pannable(1);
    c_pan(camerax() + 54, cameray(), 60);
    var kris_target_x = 774;
    c_sel(kr);
    c_sprite(spr_krisr);
    c_autowalk(0);
    c_imageindex(1);
    c_imagespeed(0.14);
    c_walkdirect_wait(kris_target_x, 495, 60);
    c_halt();
    c_wait(30);
    c_sel(ca);
    c_autodepth(0);
    c_depth(kr_actor.depth - 10);
    c_autowalk(0);
    c_sprite(spr_carol_walk_down);
    c_setxy(554, 481);
    c_imagespeed(0.2);
    c_sprite(spr_carol_walk_right);
    c_walkdirect_wait(kris_target_x - 24, 481, 120);
    c_halt();
    c_wait(30);
    c_sprite(spr_carol_kris_shoulder);
    var speed_offset = 2;
    c_sel(ca);
    c_wait(2 + speed_offset);
    c_imageindex(1);
    c_wait(2 + speed_offset);
    c_imageindex(2);
    c_wait(2 + speed_offset);
    c_sel(kr);
    c_visible(0);
    c_sel(ca);
    c_imageindex(3);
    c_wait(2 + speed_offset);
    c_imageindex(4);
    c_soundplay(snd_bump);
    c_wait(30);
    var santa_active = false;
    with (obj_homealone_dancing_santa)
    {
        if (!santa_active)
            santa_active = is_active;
    }
    c_speaker("no_name");
    c_msgsetloc(0, "* (You felt something like ice on your shoulder...)/", "obj_ch4_PDC14C_slash_Step_0_gml_1495_0");
    if (santa_active)
    {
        c_facenext("carol", 0);
        c_msgnextloc("\\E0* Kris.../", "obj_ch4_PDC14C_slash_Step_0_gml_1500_0");
        c_msgnextloc("\\E0* .../", "obj_ch4_PDC14C_slash_Step_0_gml_1501_0");
        c_msgnextloc("\\E0* .../", "obj_ch4_PDC14C_slash_Step_0_gml_1502_0");
        c_msgnextloc("\\E0* .../", "obj_ch4_PDC14C_slash_Step_0_gml_1503_0");
        c_msgnextloc("\\E1* Before you leave.../", "obj_ch4_PDC14C_slash_Step_0_gml_1504_0");
        c_msgnextloc("\\E6* Turn that thing off./", "obj_ch4_PDC14C_slash_Step_0_gml_1505_0");
        c_msgnextloc("\\E1* It saves batteries./%", "obj_ch4_PDC14C_slash_Step_0_gml_1506_0");
        c_talk_wait();
    }
    else
    {
        c_facenext("carol", "2");
        c_msgnextloc("\\E2* My apologies about just now^1, Kris./", "obj_ch4_PDC14C_slash_Step_0_gml_1511_0");
        c_msgnextloc("\\E3* As you know^1, \\cRYOU\\cW are welcome here any time./%", "obj_ch4_PDC14C_slash_Step_0_gml_1512_0");
        c_talk_wait();
    }
    c_wait(15);
    c_sel(ca);
    c_sprite(spr_carol_walk_right);
    c_var_lerp_instance(blackall, "image_alpha", 0, 1, 60);
    c_sel(kr);
    c_visible(1);
    c_wait(10);
    if (!santa_active)
    {
        c_autowalk(0);
        c_imageindex(1);
        c_imagespeed(0.14);
        c_walkdirect_wait(790, 494, 50);
        c_wait(15);
        c_snd_play(snd_dooropen);
        c_wait(30);
    }
    else
    {
        c_wait(90);
    }
    c_waitcustom();
}
if (carol_bgm)
{
    carol_bgm = false;
    carol_bgm_file = audio_play_sound(mus_undynescary, 1, 1);
    audio_sound_gain(mus_undynescary, 1, 0);
}
if (con == 51 && customcon == 1)
{
    con = 52;
    customcon = 0;
    alarm[0] = 30;
    c_waitcustom_end();
    var fadeout = instance_create(0, 0, obj_fadeout);
    fadeout.fadespeed = 0.06;
    if (snd_is_playing(global.currentsong[1]))
        mus_volume(global.currentsong[1], 0, 14);
    if (carol_bgm_file != -4)
        audio_sound_gain(carol_bgm_file, 0, 14);
    c_wait(30);
    c_pannable(0);
    c_terminatekillactors();
}
if (con == 53 && !i_ex(obj_cutscene_master))
{
    con = -1;
    global.plot = 68;
    global.interact = 3;
    global.entrance = (ord(string_upper("A")) - 65) + 1;
    global.plot = 90;
    con = 99;
    snd_free_all();
    instance_create(0, 0, obj_persistentfadein);
    room_goto(room_town_noellehouse);
}
