hookdaddy = 0;
timer = 0;
con = 0;
init = 0;
lastposx = x;
lastposy = y;
scr_darksize();
hookedobj = 0;
xoffset = 0;
yoffset = 0;
hookablelist[0] = 438;
array_insert(hookablelist, array_length(hookablelist), 361);
array_insert(hookablelist, array_length(hookablelist), 1410);
array_insert(hookablelist, array_length(hookablelist), 777);
