image_alpha = 0;
active = false;
init = 0;
con = 0;
timer = 0;
kris = 0;
susie = 0;
ralsei = 0;
kr_real = 0;
su_real = 0;
ra_real = 0;
tenna = 0;
suwalk = 0;
suwalktimer = 0;
visit = 0;
made = false;
kx = 999;
ky = 999;
tenna = scr_board_marker(x, y, spr_board_npc_tenna_back, 0, 999990, 2, false);
with (tenna)
    setxy_board(3904, 1440);
sndpause = 0;
dungosound = 0;
dungoinit = snd_init("ch3_south_of_the_border.ogg");
