scr_darksize(id);
image_speed = 0;
idealPositionProgress = 0;
positionProgressB = 0;
idealX = x;
idealY = y;
stickToKris = true;
active = 0;
pos = "up";
prevpos = "down";
mycater = 0;
upcon = 0;
newdesy = 0;
