surf = surface_create(room_width, room_height);
surface_set_target(surf);
draw_clear(c_black);
surface_reset_target();
zoomtime = 2400;
zoomtimer = 0;
startradius = 600;
endradius = 50;
radius = 200;
con = 0;
lerpamount = 0;
siner = 0;
type = 3;
finish = 0;
init = 0;
