event_inherited();
image_xscale = 1;
image_yscale = 1;
damage = 18;
target = 3;
grav = 0;
parenttarget_x = -1;
parenttarget_y = -1;
parenttarget_xscale = -1;
parenttarget_yscale = -1;
image_blend = make_color_rgb(68, 140, 203);
