event_inherited();
damage = 18;
target = 3;
dir = choose(-1, 1);
timer = 0;
siner = 0;
con = 0;
laser_xscale = 0;
position = "above";
yrange = irandom(400);
parenttarget = -1;
bulletspeed = 0;
image_yscale = 0;
