if (con < 0)
    exit;
if (con == 0)
{
    con = 1;
    alarm[0] = 30;
    global.interact = 1;
    global.facing = 1;
    gerson_npc = instance_create(760, 433, obj_npc_gerson);
    with (gerson_npc)
    {
        current_state = 3;
        scr_depth();
    }
}
if (con == 2 && !d_ex())
{
    con = 5;
    global.facing = 0;
    with (obj_caterpillarchara)
    {
        if (name == "susie")
            fun = 0;
        else if (name == "ralsei")
            fun = 0;
    }
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    c_wait(30);
    c_speaker("gerson");
    c_msgsetloc(0, "* What are we running from?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_81_0");
    c_facenext("susie", 20);
    c_msgnextloc("\\EK* There was..^1. that thing..^1. you know.../%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_83_0");
    c_talk();
    c_wait_box(2);
    c_var_instance(gerson_npc, "current_state", 2);
    c_sel(su);
    c_facing("r");
    c_wait_talk();
    c_wait(30);
    c_sel(ra);
    c_facing("r");
    c_snd_play(snd_suslaugh);
    c_sel(su);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_susie_laugh_dw);
    c_flip("x");
    c_var_instance(gerson_npc, "current_state", 5);
    c_sndplay(snd_gerlaugh);
    c_wait(60);
    c_sel(su);
    c_facing("r");
    c_halt();
    c_flip("x");
    c_var_instance(gerson_npc, "current_state", 9);
    c_wait(30);
    c_speaker("gerson");
    c_msgsetloc(0, "* Y'know^1, I was just about to have some tea./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_124_0");
    c_msgnextloc("* Feel free to join me if you like!/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_125_0");
    c_facenext("susie", 7);
    c_msgnextloc("\\E7* Uhh^1, sure!/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_127_0");
    c_talk();
    c_wait_box(1);
    c_var_instance(gerson_npc, "facing_right", true);
    c_wait_box(3);
    c_var_instance(gerson_npc, "current_state", 1);
    c_var_lerp_to_instance(gerson_npc, "x", 1242, 60);
    c_wait_talk();
    c_wait(60);
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 5 && !i_ex(obj_cutscene_master) && !d_ex())
{
    con = 6;
    global.interact = 0;
    global.facing = 0;
    gerson_npc.x = 1312;
    gerson_npc.y = 466;
    gerson_npc.depth = table_marker.depth - 40;
    gerson_npc.current_state = 9;
    gerson_npc.facing_right = false;
    with (obj_caterpillarchara)
    {
        if (name == "susie")
            fun = 0;
        else if (name == "ralsei")
            fun = 0;
    }
}
if (con == 6 && obj_mainchara.x >= 1010 && global.interact == 0)
{
    snd_free_all();
    con = -1;
    global.interact = 1;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    c_sel(kr);
    c_walkdirect(1090, 468, 30);
    c_sel(su);
    c_delaywalkdirect(5, 1038, 451, 30);
    c_sel(ra);
    c_delaywalkdirect(10, 990, 455, 30);
    c_pannable(1);
    c_pan(950, 260, 60);
    c_wait(90);
    c_msc(1413);
    c_talk_wait();
    c_waitcustom();
}
if (con == 10 && !d_ex() && customcon == 1)
{
    con = 40;
    customcon = 0;
    c_waitcustom_end();
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* Sure^1, why the hell not./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_215_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 20 && !d_ex() && customcon == 1)
{
    con = -1;
    customcon = 0;
    c_waitcustom_end();
    c_var_instance(gerson_npc, "current_state", 0);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_beard_thinking_neutral);
    c_msc(1417);
    c_talk_wait();
    c_waitcustom();
}
if (con == 25 && !d_ex() && customcon == 1)
{
    con = 26;
    customcon = 0;
    c_waitcustom_end();
    c_sel(su);
    c_sprite(spr_susie_look_down_right_dw);
    c_speaker("susie");
    c_msgsetloc(0, "\\EC* Yeah^1, it would be cool but we got stuff to do./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_253_0");
    c_talk_wait();
    c_sel(su);
    c_facing("r");
    c_var_instance(gerson_npc, "current_state", 5);
    c_sndplay(snd_gerlaugh);
    c_wait(60);
    c_var_instance(gerson_npc, "current_state", 9);
    c_speaker("gerson");
    c_msgsetloc(0, "* Geh heh^1, alright^1! Guess I won't have any either!/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_264_0");
    c_talk_wait();
    c_var_instance(gerson_npc, "current_state", 1);
    c_var_lerp_to_instance(gerson_npc, "y", 760, 70);
    c_wait(90);
    c_pannable(1);
    c_panobj(kr_actor, 30);
    c_wait(31);
    c_pannable(0);
    c_sel(kr);
    c_facing("d");
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 26 && !i_ex(obj_cutscene_master) && !d_ex())
{
    con = -1;
    global.facing = 0;
    global.interact = 0;
    clean_up();
}
if (con == 28 && !d_ex() && customcon == 1)
{
    con = 40;
    customcon = 0;
    c_waitcustom_end();
    c_var_instance(gerson_npc, "current_state", 9);
    c_speaker("gerson");
    c_msgsetloc(0, "* Good^1! Geh heh heh.../%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_306_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 30 && !d_ex() && customcon == 1)
{
    con = 40;
    customcon = 0;
    c_waitcustom_end();
    c_var_instance(gerson_npc, "current_state", 0);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_beard_thinking_neutral);
    c_speaker("susie");
    c_msgsetloc(0, "\\EK* We already had tea. This afternoon./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_327_0");
    c_talk_wait();
    c_var_instance(gerson_npc, "current_state", 0);
    c_wait(15);
    c_speaker("gerson");
    c_msgsetloc(0, "* Right. That was the afternoon tea. The relaxation tea./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_335_0");
    c_msgnextloc("* This is the midnight tea. That stuff that sets your heart and mind afire.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_336_0");
    c_msgnextloc("* Ready for a long night's journey sittin' at your desk./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_337_0");
    c_msgnextloc("* ..^1. it ain't for the faint of heart./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_338_0");
    c_facenext("ralsei", "d");
    c_msgnextloc("\\Ed* Umm^1, what's..^1. in it?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_340_0");
    c_talk();
    c_wait_box(1);
    c_var_instance(gerson_npc, "current_state", 6);
    c_wait_box(2);
    c_var_instance(gerson_npc, "current_state", 0);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_look_diagonal);
    c_wait_box(3);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_outfit_walk_cane_look_side);
    c_sel(ra);
    c_sprite(spr_ralsei_surprised_right);
    c_wait_box(5);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_right_head_down);
    c_wait_talk();
    c_var_instance(gerson_npc, "current_state", 2);
    c_wait(30);
    c_speaker("gerson");
    c_msgsetloc(0, "* Chamomile^1, mostly. ..^1. And what else^1, what else./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_366_0");
    c_msgnextloc("* Oh right. Water./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_367_0");
    c_msgnextloc("* Geheheheh eheheh!!!/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_368_0");
    c_facenext("ralsei", 20);
    c_msgnextloc("\\EK* (Well^1, at least it seems safe to drink...)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_370_0");
    c_talk();
    c_wait_box(1);
    c_var_instance(gerson_npc, "current_state", 0);
    c_wait_box(2);
    c_var_instance(gerson_npc, "current_state", 5);
    c_sndplay(snd_gerlaugh);
    c_wait_box(4);
    c_sel(ra);
    c_facing("r");
    c_wait_talk();
    c_var_instance(gerson_npc, "current_state", 9);
    c_wait(5);
    c_waitcustom();
}
if (con == 40 && !d_ex() && customcon == 1)
{
    con = 41;
    customcon = 0;
    c_waitcustom_end();
    c_sel(kr);
    c_autodepth(0);
    c_depth(chair_left_marker.depth + 2);
    c_walkdirect(kr_actor.x, 392, 30);
    c_delaywalkdirect(31, 1223, 392, 30);
    c_delayfacing(62, "d");
    c_delaywalkdirect(62, 1223, 398, 6);
    c_delaycmd4(62, "var", id, "play_noise", true);
    c_sel(su);
    c_walkdirect(1374, su_actor.y, 65);
    c_delaywalkdirect(66, 1374, 429, 20);
    c_delaycmd4(87, "var", id, "play_noise", true);
    c_delaycmd(87, "sprite", spr_tea_party_susie_sit);
    c_delaycmd(87, "autodepth", 0);
    c_delaycmd(87, "depth", 93000);
    c_delaycmd4(87, "setxy", 1356, 420);
    c_delaycmd4(87, "var", chair_right_marker, "visible", 0);
    c_delaycmd4(97, "var", id, "current_noise", 214);
    c_delaycmd(97, "autowalk", 0);
    c_delaycmd(97, "sprite", spr_tea_party_susie_grab);
    c_delaycmd(103, "sprite", spr_tea_party_susie_cup_hold);
    c_delaycmd4(103, "var", cup_susie_marker, "visible", 0);
    c_delaycmd(103, "imageindex", 1);
    c_sel(ra);
    c_autodepth(0);
    c_depth(chair_left_marker.depth - 2);
    c_walkdirect(1135, ra_actor.y, 60);
    c_delaywalkdirect(61, 1142, 432, 20);
    c_delaycmd4(82, "var", id, "play_noise", true);
    c_delaycmd(82, "sprite", spr_tea_party_ralsei_sit);
    c_delaycmd(82, "autodepth", 0);
    c_delaycmd(82, "depth", 93000);
    c_delaycmd4(82, "setxy", 1142, 424);
    c_var_instance(gerson_npc, "facing_right", true);
    c_wait(15);
    c_var_instance(gerson_npc, "current_state", 1);
    c_var_lerp_to_instance(gerson_npc, "x", 1520, 60);
    c_wait(61);
    c_var_instance(gerson_npc, "depth", table_marker.depth + 10);
    c_var_instance(gerson_npc, "facing_right", false);
    c_var_instance(gerson_npc, "facing_up", true);
    c_var_lerp_to_instance(gerson_npc, "y", 385, 40);
    c_wait(41);
    c_var_instance(gerson_npc, "facing_up", false);
    c_var_lerp_to_instance(gerson_npc, "x", 1286, 40);
    c_wait(40);
    c_var_instance(gerson_npc, "current_state", 0);
    c_snd_play(snd_wing);
    c_var_lerp_to_instance(gerson_npc, "y", 392, 6);
    c_wait(5);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_sit);
    c_var_instance(gerson_npc, "x", 1288);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip_normal);
    c_wait(30);
    c_sprite(spr_tea_party_susie_sip_surprised);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_sit_look);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_mus2("initloop", "church_dark_study.ogg", 0);
    c_mus2("pitch", 0.95, 0);
    c_mus2("volume", 0, 0);
    c_mus2("volume", 1, 30);
    c_speaker("gerson");
    c_msgsetloc(0, "* So^1, you three have had a mighty journey so far^1, have you?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_480_0");
    c_facenext("susie", "2");
    c_msgnextloc("\\E2* Uh..^1. Yeah. I guess you could say that./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_482_0");
    c_talk();
    c_wait_box(2);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_smile);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_imageindex(1);
    c_wait_talk();
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_wait(30);
    c_var_instance(gerson_npc, "anim_index", 2);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold_surprised);
    c_speaker("gerson");
    c_msgsetloc(0, "* Well now^1, how about telling me about your adventures?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_508_0");
    c_facenext("susie", "D");
    c_msgnextloc("\\ED* Uh.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_510_0");
    c_msgnextloc("\\E3* (Hey Ralsei^1, would it be okay to tell him that...?)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_511_0");
    c_facenext("ralsei", "Q");
    c_msgnextloc("\\EQ* (I don't see why not...)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_513_0");
    c_facenext("susie", 9);
    c_msgnextloc("\\E9* Sure^1, all right then^1, listen up!/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_515_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold_look_away);
    c_wait_box(3);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold_neutral);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_wait_box(5);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_box(7);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_sel(su);
    c_sprite(spr_tea_party_susie_put);
    c_imageindex(0);
    c_delaycmd(6, "imageindex", 1);
    c_delaycmd4(6, "var", cup_susie_marker, "visible", 1);
    c_wait(6);
    c_snd_play(snd_bump);
    c_wait_talk();
    c_wait(30);
    c_var_lerp_to_instance(blackall, "image_alpha", 1, 60);
    c_wait(90);
    c_speaker("no_name");
    c_msgsetloc(0, "* (Susie animatedly explained all of your adventures so far...)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_553_0");
    c_talk_wait();
    c_var_instance(utensils_susie_marker, "sprite_index", spr_tea_party_utensils_messy);
    c_var_instance(utensils_gerson_marker, "sprite_index", spr_tea_party_utensils_messy);
    c_var_instance(utensils_gerson_marker, "y", utensils_gerson_marker.y + 16);
    c_wait(30);
    c_var_lerp_to_instance(blackall, "image_alpha", 0, 60);
    c_wait(90);
    c_speaker("susie");
    c_msgsetloc(0, "\\E7* ..^1. and now we're here^1! Pretty awesome^1, huh!?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_567_0");
    c_talk_wait();
    c_snd_play(snd_gerlaugh);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_sit_laugh);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_var_instance(gerson_npc, "anim_speed", 0.2);
    c_wait(60);
    c_speaker("gerson");
    c_msgsetloc(0, "* Geheheh^1! Yes^1, what an excellent tale./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_578_0");
    c_facenext("ralsei", 20);
    c_msgnextloc("\\EK* I especially liked the part where you acted out the battles.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_580_0");
    c_msgnextloc("\\E2* ...using the silverware and sugar cubes./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_581_0");
    c_facenext("susie", 2);
    c_msgnextloc("\\E2* Hey^1, how else is he gonna know how cool we were?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_583_0");
    c_talk();
    c_wait_box(2);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_sit_look);
    c_var_instance(gerson_npc, "anim_speed", 0);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_smile);
    c_wait_box(3);
    c_sel(ra);
    c_autowalk(0);
    c_sprite(spr_tea_party_ralsei_laugh);
    c_imagespeed(0.2);
    c_wait_box(5);
    c_var_instance(gerson_npc, "anim_index", 2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_wait_talk();
    c_snd_play(snd_suslaugh);
    c_sel(su);
    c_sprite(spr_tea_party_susie_laugh);
    c_imagespeed(0.2);
    c_sel(ra);
    c_autowalk(0);
    c_sprite(spr_tea_party_ralsei_laugh);
    c_imagespeed(0.2);
    c_snd_play(snd_gerlaugh);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_sit_laugh);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_var_instance(gerson_npc, "anim_speed", 0.2);
    c_wait(60);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_sit_look);
    c_var_instance(gerson_npc, "anim_speed", 0);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_halt();
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_tea_party_susie_grab);
    c_wait(6);
    c_snd_play(snd_noise);
    c_var_instance(cup_susie_marker, "visible", 0);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_halt();
    c_wait(6);
    c_imageindex(1);
    c_wait(30);
    c_sprite(spr_tea_party_susie_sip);
    c_wait(30);
    c_sel(su);
    c_sprite(spr_tea_party_susie_put);
    c_imageindex(0);
    c_delaycmd(6, "imageindex", 1);
    c_delaycmd4(6, "var", cup_susie_marker, "visible", 1);
    c_wait(6);
    c_snd_play(snd_bump);
    c_var_instance(gerson_npc, "anim_index", 2);
    c_speaker("susie");
    c_msgsetloc(0, "\\E9* ..^1. Well^1, thanks for the tea^1, old man./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_662_0");
    c_talk_wait();
    c_var_instance(chair_right_marker, "visible", 1);
    c_sel(su);
    c_snd_play(snd_wing);
    c_autowalk(0);
    c_facing("d");
    c_halt();
    c_setxy(1355, 429);
    c_shakeobj();
    c_wait(15);
    c_autowalk(1);
    c_walkdirect_wait(1354, 453, 15);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_walkdirect_wait(1251, 453, 20);
    c_facing("d");
    c_wait(15);
    c_sprite(spr_susie_carry_pose);
    c_speaker("susie");
    c_msgsetloc(0, "\\EA* We gotta go get back to our hero stuff./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_684_0");
    c_talk_wait();
    c_sel(su);
    c_facing("u");
    c_wait(5);
    c_speaker("gerson");
    c_msgsetloc(0, "* Will ya come by my study later?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_693_0");
    c_facenext("susie", "9");
    c_msgnextloc("\\E9* Yeah^1, sure. Not like we got a choice./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_695_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_susie_head_scratch_dw);
    c_addxy(0, -6);
    c_imagespeed(0.2);
    c_wait_talk();
    c_sel(su);
    c_facing("d");
    c_halt();
    c_addxy(0, 6);
    c_wait(15);
    c_autowalk(1);
    c_walkdirect_wait(1252, 757, 60);
    c_waitcustom();
}
if (temp_noise != current_noise)
{
    temp_noise = current_noise;
    play_noise = true;
}
if (play_noise)
{
    play_noise = false;
    snd_play(current_noise);
}
if (con == 41 && !d_ex() && customcon == 1)
{
    con = 42;
    customcon = 0;
    c_waitcustom_end();
    c_wait(30);
    c_var_instance(gerson_npc, "anim_index", 2);
    c_speaker("gerson");
    c_msgsetloc(0, "* .../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_745_0");
    c_msgnextloc("* Ain't no better story than one told with sparkling eyes./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_746_0");
    c_msgnextloc("* She ain't got no fear^1, that one. Doubt^1, irony^1, that's what poisons your story.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_747_0");
    c_msgnextloc("* That^1, and too much predictability./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_748_0");
    c_talk();
    c_wait_box(1);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_wait_box(2);
    c_var_instance(gerson_npc, "anim_index", 2);
    c_wait_box(3);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_wait_talk();
    c_wait(30);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_speaker("gerson");
    c_msgsetloc(0, "* So^1, young man..^1. What do you think happens next?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_770_0");
    c_facenext("ralsei", "C");
    c_msgnextloc("\\EC* H..^1. huh?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_772_0");
    c_msgnextloc("\\EQ* I..^1. I guess we'll..^1. just have to see./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_773_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_box(3);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_head_down);
    c_wait_talk();
    c_wait(30);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_neutral);
    c_speaker("gerson");
    c_msgsetloc(0, "* Hmm^1, hmm./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_794_0");
    c_talk_wait();
    c_snd_play(snd_wing);
    c_var_lerp_to_instance(gerson_npc, "y", gerson_npc.y - 8, 16);
    c_var_lerp_to_instance(gerson_npc, "x", gerson_npc.x - 44, 16);
    c_wait(12);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_tea_pour);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_wait(10);
    c_var_instance(gerson_npc, "anim_index", 1);
    c_wait(6);
    c_snd_play(snd_noise);
    c_var_instance(gerson_npc, "anim_index", 2);
    c_var_instance(pot_marker, "visible", 0);
    c_wait(12);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_tea_walk);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_var_instance(gerson_npc, "anim_speed", 0.1);
    c_var_lerp_to_instance(gerson_npc, "y", gerson_npc.y - 8 - 20, 16);
    c_wait(4);
    c_var_instance(gerson_npc, "depth", chair_top_left_marker.depth + 60);
    c_wait(16);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_var_lerp_to_instance(gerson_npc, "x", gerson_npc.x - 44 - 70, 30);
    c_wait(30);
    c_var_instance(gerson_npc, "anim_speed", 0);
    c_wait(5);
    c_var_lerp_to_instance(gerson_npc, "y", gerson_npc.y - 10, 16);
    c_var_instance(gerson_npc, "anim_speed", 0.1);
    c_wait(16);
    c_var_instance(gerson_npc, "anim_speed", 0);
    c_wait(14);
    c_var_instance(gerson_npc, "anim_speed", 0);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_tea_pour);
    c_var_instance(gerson_npc, "anim_index", 3);
    c_wait(6);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_var_instance(gerson_npc, "anim_index", 4);
    c_var_instance(cup_ralsei_marker, "visible", 0);
    c_snd_play(snd_noise);
    c_wait(6);
    c_var_instance(gerson_npc, "anim_index", 5);
    c_wait(6);
    c_var_instance(gerson_npc, "anim_index", 6);
    c_snd_play(snd_paper_surf);
    c_wait(30);
    c_var_instance(gerson_npc, "anim_index", 7);
    c_wait(6);
    c_var_instance(gerson_npc, "anim_index", 8);
    c_wait(6);
    c_var_instance(gerson_npc, "anim_index", 9);
    c_wait(6);
    c_var_instance(gerson_npc, "anim_index", 10);
    c_var_instance(cup_ralsei_marker, "visible", 1);
    c_var_lerp_to_instance(cup_ralsei_marker, "y", cup_ralsei_marker.y + 10, 4);
    c_var_lerp_to_instance(cup_ralsei_marker, "x", cup_ralsei_marker.x - 6, 4);
    c_snd_play(snd_bump);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_speaker("gerson");
    c_msgsetloc(0, "* Drink up. It's still hot now./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_860_0");
    c_facenext("ralsei", "Q");
    c_msgnextloc("\\EQ* ..^1. thank you./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_862_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_wait_talk();
    c_sel(ra);
    c_autowalk(0);
    c_sprite(spr_tea_party_ralsei_reach);
    c_halt();
    c_wait(6);
    c_imageindex(1);
    c_var_instance(cup_ralsei_marker, "visible", 0);
    c_wait(6);
    c_imageindex(2);
    c_wait(15);
    c_sprite(spr_tea_party_ralsei_sip);
    c_imageindex(1);
    c_delaycmd(30, "imageindex", 0);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_tea_look);
    c_var_instance(gerson_npc, "anim_index", 0);
    c_speaker("gerson");
    c_msgsetloc(0, "* You^1, I noticed you haven't touched your tea yet./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_891_0");
    c_msgnextloc("* ..^1. Close your eyes./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_892_0");
    c_talk();
    c_wait_box(1);
    c_var_instance(gerson_npc, "current_sprite_index", spr_gerson_tea_bow);
    c_wait_talk();
    c_wait(30);
    c_sel(ra);
    c_imageindex(1);
    c_delaycmd(30, "imageindex", 0);
    c_customfunc(function()
    {
        with (obj_border_controller)
            hide_border(0.025);
    });
    c_var_lerp_to_instance(blackall, "image_alpha", 1, 60);
    c_wait(90);
    if (scr_sideb_active())
    {
        c_speaker("gerson");
        c_msgsetloc(0, "* ..^1. You're really just going through the motions^1, huh?/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_917_0");
        c_msgnextloc("* Something tough's going on with you. ..^1. I can tell that sorta thing./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_918_0");
        c_msgnextloc("* And now^1, you still gotta go through your day. Still gotta talk^1, fight^1, do homework.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_919_0");
        c_msgnextloc("* I bet it all feels pointless^1, don't it. It's almost an insult that the earth's still turnin'./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_920_0");
        c_msgnextloc("* ..^1. but don't you give up. Even if you gotta do those motions.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_921_0");
        c_msgnextloc("* Trying to find something^1, anything in them^1, that means a little something..^1. ya hear?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_922_0");
        c_talk_wait();
        c_wait(30);
    }
    c_snd_play(snd_bump);
    c_msc(1415);
    c_talk_wait();
    c_waitcustom();
}
if (con == 50 && !d_ex() && customcon == 1)
{
    con = 80;
    customcon = 0;
    c_waitcustom_end();
    c_speaker("no_name");
    c_msgsetloc(0, "* (You sipped the tea. ..^1. it's very sweet.)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_947_0");
    c_msgnextloc("* (You drank it slowly^1, feeling a warmth spread across your body...)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_948_0");
    c_msgnextloc("* (Until^1, only a thin^1, sickly syrup was left cold at the bottom.)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_949_0");
    c_talk_wait();
    c_wait(30);
    c_speaker("gerson");
    c_fefc(0, 0);
    c_msgsetloc(0, "* That's the nice thing about tea. You can always count on it^1, geheheh.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_956_0");
    c_msgnextloc("* Right^1, young man?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_957_0");
    c_talk_wait();
    c_wait(30);
    c_speaker("ralsei");
    c_fefc(0, 0);
    c_msgsetloc(0, "* Yes..^1. Yes^1, that's right./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_964_0");
    c_msgnextloc("* Kris^1, whenever you want^1, I can make you tea as well^1, with lots of sugar.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_965_0");
    c_msgnextloc("* No^1, even..^1. I mean^1, even if you don't especially ask for it...!/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_966_0");
    c_msgnextloc("* And.../%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_967_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 60 && !d_ex() && customcon == 1)
{
    con = 80;
    customcon = 0;
    c_waitcustom_end();
    c_speaker("gerson");
    c_fefc(0, 0);
    c_msgsetloc(0, "* ..^1. Well^1, if tea's not your fancy^1, how about.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_984_0");
    c_msgnextloc("* (Shine..^1. shine...)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_985_0");
    c_msgnextloc("* How about an apple?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_986_0");
    c_talk_wait();
    c_wait(30);
    c_snd_play(snd_bump);
    c_speaker("no_name");
    c_msgsetloc(0, "* (..^1. You heard something being placed in front of you.)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_994_0");
    c_msgnextloc("* (...)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_995_0");
    c_msgnextloc("* (...)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_996_0");
    c_talk_wait();
    c_wait(30);
    c_speaker("ralsei");
    c_fefc(0, 0);
    c_msgsetloc(0, "* Umm^1, Kris...? Here^1, um..^1. I'll..^1. I'll help!/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1003_0");
    c_msgnextloc("* Here^1, umm^1, I'm holding it in front of your.../%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1004_0");
    c_talk_wait();
    c_snd_play(snd_bite);
    c_speaker("no_name");
    c_msgsetloc(0, "* (Your teeth lurched forward to bite the apple.)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1011_0");
    c_msgnextloc("* (A sweet sensation spread through your mouth...)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1012_0");
    c_talk_wait();
    c_wait(30);
    c_speaker("ralsei");
    c_fefc(0, 0);
    c_msgsetloc(0, "* That's right^1! Just take a bite^1, Kris.../%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1019_0");
    c_talk_wait();
    if (!scr_sideb_active())
    {
        c_var_instance(apple_marker, "visible", 1);
        c_speaker("no_name");
        c_msgsetloc(0, "* (Each time you felt a new piece of the apple^1, your teeth would bite it...)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1028_0");
        c_talk_wait();
        c_snd_play(snd_bite);
        c_wait(60);
        c_snd_play(snd_bite);
        c_wait(30);
        c_snd_play(snd_bite);
        c_wait(15);
        c_snd_play(snd_bite);
        c_wait(30);
        c_speaker("no_name");
        c_msgsetloc(0, "* (..^1. until nothing was left but the core.)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1043_0");
        c_talk_wait();
    }
    else
    {
        c_mus("free_all");
        c_wait(30);
        c_snd_play(snd_bite);
        c_wait(30);
        c_snd_play(snd_bite);
        c_wait(15);
        c_snd_play(snd_bite);
        c_wait(8);
        c_snd_play(snd_bite);
        c_wait(15);
        c_speaker("ralsei");
        c_fefc(0, 0);
        c_msgsetloc(0, "* Ahh^1, Kris^1! D-Don't eat so fast...!/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1068_0");
        c_talk_wait();
        c_snd_play(snd_bite);
        c_wait(8);
        c_snd_play(snd_bite);
        c_wait(8);
        c_snd_play(snd_bite);
        c_wait(8);
        c_snd_play(snd_bite);
        c_speaker("ralsei");
        c_fefc(0, 0);
        c_msgsetloc(0, "* Kris^1, don't eat the--%%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1083_0");
        c_talk_wait();
        c_snd_play(snd_bite);
        c_wait(4);
        c_snd_play(snd_hurt1);
        c_wait(30);
        c_speaker("no_name");
        c_msgsetloc(0, "* (Your teeth clenched into something small and hard..^1. crack!)/", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1093_0");
        c_msgnextloc("* (..^1.  A bitter taste spread through your mouth.)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1094_0");
        c_talk_wait();
        c_wait(15);
        c_speaker("ralsei");
        c_fefc(0, 0);
        c_msgsetloc(0, "* ..^1. don't^1, eat the core^1, Kris..^1. haha./", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1101_0");
        c_facenext("no_name", 0);
        c_msgnextloc("* (..^1. You felt a handkerchief wiping your face.)/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1103_0");
        c_talk_wait();
        c_wait(30);
        c_speaker("ralsei");
        c_fefc(0, 0);
        c_msgsetloc(0, "* ..^1. Kris.../", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1110_0");
        c_msgnextloc("* You can^1, um^1, open your eyes..^1. you know./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1111_0");
        c_talk_wait();
    }
    c_waitcustom();
}
if (con == 80 && !d_ex() && customcon == 1)
{
    con = 100;
    customcon = 0;
    global.facing = 0;
    pot_marker.x = table_marker.x + 80;
    pot_marker.y = table_marker.y - 4;
    pot_marker.visible = 1;
    c_waitcustom_end();
    c_var_instance(gerson_npc, "visible", 0);
    c_var_instance(gerson_npc, "visible", 0);
    c_var_instance(cup_ralsei_marker, "visible", 1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_wait(30);
    c_mus2("volume", 0, 60);
    c_customfunc(function()
    {
        with (obj_border_controller)
            show_border();
    });
    c_var_lerp_to_instance(blackall, "image_alpha", 0, 60);
    c_wait(90);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EL* Huh? When did^1, um^1, the old man leave?/%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1153_0");
    c_talk_wait();
    c_snd_play(snd_wing);
    c_sel(kr);
    c_autodepth(0);
    c_depth(chair_left_marker.depth + 10);
    c_autowalk(0);
    c_walkdirect_wait(kr_actor.x, kr_actor.y - 10, 4);
    c_autowalk(1);
    c_walkdirect(kr_actor.x - 150, kr_actor.y - 10, 40);
    c_facing("l");
    c_wait(20);
    c_sel(ra);
    c_autodepth(0);
    c_depth(chair_left_marker.depth + 5);
    c_snd_play(snd_wing);
    c_autowalk(1);
    c_walkdirect(ra_actor.x, ra_actor.y - 42, 15);
    c_delaycmd(16, "autodepth", 0);
    c_delaycmd(16, "depth", 98000);
    c_delayfacing(16, "l");
    c_delaywalkdirect(16, ra_actor.x - 10, ra_actor.y - 42, 15);
    c_wait(30);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EQ* Anyway^1, let's go^1, Kris./%", "obj_dw_church_waterfalltearoom_slash_Step_0_gml_1184_0");
    c_talk_wait();
    c_sel(kr);
    c_walkdirect(1080, 532, 30);
    c_delaycmd(16, "depth", 8000);
    c_delaywalkdirect(31, 1257, 532, 30);
    c_delaywalkdirect(62, 1257, 748, 30);
    c_sel(ra);
    c_walkdirect(1076, ra_actor.y - 42, 15);
    c_delaycmd(16, "depth", 9000);
    c_delaywalkdirect(16, 1076, 525, 30);
    c_delaywalkdirect(47, 1260, 525, 30);
    c_delaywalkdirect(78, 1260, 740, 30);
    c_wait(78);
    c_var_lerp_to_instance(blackall, "image_alpha", 1, 60);
    c_wait(90);
    c_waitcustom();
}
if (con == 100 && !d_ex() && customcon == 1)
{
    con = -1;
    scr_flag_set(1503, 1);
    scr_tempsave();
    snd_free_all();
    global.interact = 3;
    global.entrance = 9;
    instance_create(0, 0, obj_persistentfadein);
    room_goto(room_dw_church_moneyfountain);
}
