function scr_board_enemy_init()
{
    image_speed = 0.1;
    scr_darksize();
    scr_depth_board();
    init = 0;
    damage = 1;
    hp = 1;
    maxhp = hp;
    xp_given = 1;
    state = "init";
    timer = 0;
    updatetimer = 0;
    drop_candy = true;
    show_outline = false;
    sword_immunity_lv = 1;
    savex = x;
    savey = y;
    spawnerid = -1;
    dontmoveduringhurt = false;
    aggressive = obj_board_controller.violence;
    active = true;
    active_hitbox = aggressive;
    damagecon = 0;
    damagetimer = 0;
    hurttimer = 0;
    hitdir = -1;
    path = path_add();
    is_moving = false;
    is_moving_timer = 0;
    move_type = 0;
    distance_to_become_aggressive = 90;
    movecon = 0;
    movetimer = 0;
    movedir = 1;
    spd = 3;
    damage_hitbox = instance_create(x + 16, y + 16, obj_board_enemy_contact_hitbox);
    damage_hitbox.parentid = id;
    damage_hitbox.active_hitbox = active_hitbox;
    idle_sprite_r = 0;
    idle_sprite_l = 0;
    hurt_sprite = spr_board_monster_hurt;
}
