var xx = obj_growtangle.x - 79;
var yy = obj_growtangle.y - 79;
var tilesize = 9;
var ytile = 1;
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 5), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 9), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 11), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 11), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 6), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 5), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 7), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 9), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 11), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 5), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 11), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 6), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 6), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 7), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 8), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 7), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 8), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst = instance_create(xx + (tilesize * 16), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_xscale = 0.9;
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 5), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 8), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 11), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst = instance_create(xx + (tilesize * 16), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_xscale = 0.9;
ytile++;
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 5), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 6), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 11), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst = instance_create(xx + (tilesize * 16), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_xscale = 0.9;
ytile++;
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 3), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 4), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 7), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 9), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 12), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 13), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 2), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 8), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 14), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
ytile++;
inst = instance_create(xx + (tilesize * 1), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_yscale = 0.9;
inst = instance_create(xx + (tilesize * 6), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_yscale = 0.9;
inst = instance_create(xx + (tilesize * 10), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_yscale = 0.9;
inst = instance_create(xx + (tilesize * 15), yy + (tilesize * ytile), obj_rouxls_yarn_picture_tile);
inst.image_yscale = 0.9;
with (obj_rouxls_yarn_picture_tile)
    depth = obj_growtangle.depth - 1;
