if (con < 0)
    exit;
if (con == 0)
{
    con = 1;
    alarm[0] = 30;
    global.interact = 1;
    global.facing = 0;
}
if (con == 2)
{
    con = -1;
    cutscene_master = scr_cutscene_make();
    scr_maincharacters_actors();
    if (global.entrance == 1)
    {
        c_sel(kr);
        c_facing("u");
        c_setxy(280, 490);
        c_walkdirect(kr_actor.x, 322, 30);
        c_delaywalkdirect(31, 367, 322, 20);
        c_delayfacing(52, "u");
        c_sel(su);
        c_facing("u");
        c_setxy(280, 560);
        c_delaywalkdirect(10, su_actor.x, 306, 36);
        c_delaywalkdirect(48, 500, 306, 36);
        c_delayfacing(85, "u");
        c_sel(ra);
        c_facing("u");
        c_setxy(280, 610);
        c_delaywalkdirect(20, ra_actor.x, 309, 36);
        c_delaywalkdirect(58, 434, 309, 30);
        c_delayfacing(89, "u");
    }
    else
    {
        c_sel(kr);
        c_facing("u");
        c_setxy(604, 490);
        c_walkdirect(kr_actor.x, 322, 36);
        c_delaywalkdirect(37, 367, 322, 36);
        c_delayfacing(74, "u");
        c_sel(su);
        c_facing("u");
        c_setxy(604, 560);
        c_delaywalkdirect(10, su_actor.x, 306, 36);
        c_delaywalkdirect(48, 500, 306, 30);
        c_delayfacing(79, "u");
        c_sel(ra);
        c_facing("u");
        c_setxy(604, 610);
        c_delaywalkdirect(20, ra_actor.x, 309, 36);
        c_delaywalkdirect(58, 434, 309, 30);
        c_delayfacing(89, "u");
    }
    c_var_lerp_instance(blackall, "image_alpha", 1, 0, 30);
    c_wait(119);
    c_sel(su);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_susie_head_scratch_dw);
    c_addxy(0, -6);
    c_speaker("susie");
    c_msgsetloc(0, "\\E6* ..^1. H-huh? Our rooms..^1. they're..^1. combined?/", "obj_room_castle_kris_susie_slash_Step_0_gml_85_0");
    c_facenext("ralsei", 1);
    c_msgnextloc("\\E1* Umm^1, just for today^1! I thought we could use the space.../%", "obj_room_castle_kris_susie_slash_Step_0_gml_87_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_autowalk(1);
    c_facing("u");
    c_halt();
    c_addxy(0, 6);
    c_sel(ra);
    c_walk("u", 2, 8);
    c_delayfacing(10, "d");
    c_wait_talk();
    c_mus2("volume", 0, 60);
    c_pannable(1);
    c_pan(143, cameray(), 60);
    c_wait(75);
    c_sel(ra);
    c_sprite(spr_ralsei_pose);
    c_addxy(-2, 0);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\EP* ..^1. For a tea party!/%", "obj_room_castle_kris_susie_slash_Step_0_gml_119_0");
    c_talk_wait();
    c_mus("free_all");
    c_mus2("initloop", "home.ogg", 0);
    c_sel(ra);
    c_facing("d");
    c_addxy(2, 0);
    c_sel(su);
    c_facing("l");
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* Heh^1, a tea party?/%", "obj_room_castle_kris_susie_slash_Step_0_gml_138_0");
    c_talk_wait();
    c_wait(15);
    c_sel(ra);
    c_delayfacing(20, "u");
    c_sel(kr);
    c_walkdirect(286, 274, 20);
    c_delaywalkdirect(21, 286, 183, 20);
    c_delaywalkdirect(42, 444, 183, 20);
    c_delayfacing(63, "d");
    c_delaycmd(63, "imagespeed", 0);
    c_delaycmd(63, "imageindex", 0);
    c_delaycmd(63, "autowalk", 0);
    c_delaywalkdirect(63, 444, 196, 8);
    c_sel(su);
    c_walkdirect_wait(535, 306, 10);
    c_walkdirect_wait(535, 219, 30);
    c_wait(2);
    c_snd_play(snd_wing);
    c_sprite(spr_tea_party_susie_sit);
    c_setxy(516, 219);
    c_var_instance(chair_right_marker, "visible", 0);
    c_shakeobj();
    c_wait(22);
    c_snd_play(snd_bump);
    c_wait(60);
    c_speaker("susie");
    c_msgsetloc(0, "\\EL* Hit me^1, I guess./%", "obj_room_castle_kris_susie_slash_Step_0_gml_181_0");
    c_talk_wait();
    c_sel(ra);
    c_walkdirect_wait(418, 258, 12);
    c_wait(15);
    c_snd_play(snd_noise);
    c_var_instance(pot_marker, "visible", 0);
    c_autowalk(0);
    c_sprite(spr_ralsei_walk_up_tea);
    c_halt();
    c_wait(15);
    c_imagespeed(0.2);
    c_sprite(spr_ralsei_walk_right_tea);
    c_walkdirect_wait(613, 258, 30);
    c_sprite(spr_ralsei_walk_up_tea);
    c_walkdirect_wait(613, 174, 15);
    c_sprite(spr_ralsei_walk_left_tea);
    c_walkdirect_wait(504, 174, 15);
    c_sprite(spr_tea_party_ralsei_pour);
    c_halt();
    c_wait(6);
    c_imageindex(1);
    c_wait(6);
    c_imageindex(2);
    c_snd_play(snd_noise);
    c_var_instance(cup_susie_marker, "visible", 0);
    c_wait(6);
    c_imageindex(3);
    c_wait(6);
    c_imageindex(4);
    c_snd_play_x(snd_paper_surf, 0.7, 1.2);
    c_wait(30);
    c_imageindex(5);
    c_wait(6);
    c_imageindex(6);
    c_wait(6);
    c_imageindex(7);
    c_snd_play(snd_noise);
    c_var_instance(cup_susie_marker, "visible", 1);
    c_wait(6);
    c_imageindex(8);
    c_wait(30);
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_tea_party_susie_grab);
    c_wait(6);
    c_snd_play(snd_noise);
    c_var_instance(cup_susie_marker, "visible", 0);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_halt();
    c_wait(6);
    c_imageindex(1);
    c_wait(30);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip_normal);
    c_wait(15);
    c_snd_play(snd_swallow);
    c_wait(15);
    c_sprite(spr_tea_party_susie_sip_surprised);
    c_wait(30);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_imageindex(1);
    c_speaker("susie");
    c_msgsetloc(0, "\\E7* Hey^1, this is pretty good!/", "obj_room_castle_kris_susie_slash_Step_0_gml_251_0");
    c_facenext("ralsei", "2");
    c_msgnextloc("\\E2* Thanks^1! I got help from Swatch.../%", "obj_room_castle_kris_susie_slash_Step_0_gml_253_0");
    c_talk();
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip);
    c_sel(ra);
    c_sprite(spr_ralsei_walk_down_tea);
    c_wait_talk();
    c_sel(su);
    c_sprite(spr_tea_party_susie_put);
    c_imageindex(0);
    c_delaycmd(6, "imageindex", 1);
    c_delaycmd4(6, "var", cup_susie_marker, "visible", 1);
    c_wait(6);
    c_snd_play(snd_bump);
    c_wait(15);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_look_left);
    c_msc(1409);
    c_talk_wait();
    c_waitcustom();
}
if (con == 10 && !d_ex() && customcon == 1)
{
    con = 40;
    customcon = 0;
    c_waitcustom_end();
    c_sel(ra);
    c_sprite(spr_ralsei_walk_down_tea_blush);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\E1* Umm^1, okay^1! There's still cake^1, too^1, if you'd fancy some.../%", "obj_room_castle_kris_susie_slash_Step_0_gml_297_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 20 && !d_ex() && customcon == 1)
{
    con = 35;
    customcon = 0;
    c_waitcustom_end();
    c_speaker("ralsei");
    c_msgsetloc(0, "\\E2* Umm^1, okay^1! Here you go.../%", "obj_room_castle_kris_susie_slash_Step_0_gml_311_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 30 && !d_ex() && customcon == 1)
{
    con = 35;
    customcon = 0;
    c_waitcustom_end();
    c_sel(su);
    c_autodepth(0);
    c_depth(sugar_marker.depth - 2);
    c_sprite(spr_tea_party_susie_flick);
    c_imageindex(0);
    c_wait(6);
    c_imageindex(1);
    c_wait(6);
    c_snd_play(snd_bump);
    c_imageindex(2);
    c_var_instance(id, "sugar_flick", true);
    c_wait_if(id, "sugar_flick", "=", false);
    c_sel(su);
    c_sprite(spr_tea_party_susie_flick);
    c_imageindex(0);
    c_wait(6);
    c_imageindex(1);
    c_wait(6);
    c_snd_play(snd_bump);
    c_imageindex(2);
    c_var_instance(id, "sugar_flick", true);
    c_wait_if(id, "sugar_flick", "=", false);
    c_wait(30);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sit);
    c_speaker("susie");
    c_msgsetloc(0, "\\EA* There./", "obj_room_castle_kris_susie_slash_Step_0_gml_359_0");
    c_facenext("ralsei", 20);
    c_msgnextloc("\\EK* Umm^1, and here's the tea./%", "obj_room_castle_kris_susie_slash_Step_0_gml_361_0");
    c_talk_wait();
    c_waitcustom();
}
if (con == 35 && !d_ex() && customcon == 1)
{
    con = 40;
    customcon = 0;
    c_waitcustom_end();
    c_sel(ra);
    c_sprite(spr_ralsei_walk_down_tea);
    c_imagespeed(0.2);
    c_walkdirect_wait(484, ra_actor.y, 8);
    c_halt();
    c_wait(6);
    c_sprite(spr_tea_party_ralsei_pour);
    c_halt();
    c_wait(6);
    c_imageindex(1);
    c_wait(6);
    c_imageindex(2);
    c_snd_play(snd_noise);
    c_var_instance(cup_kris_marker, "visible", 0);
    c_wait(6);
    c_imageindex(3);
    c_wait(6);
    c_imageindex(4);
    c_snd_play_x(snd_paper_surf, 0.7, 1.2);
    c_wait(30);
    c_imageindex(5);
    c_wait(6);
    c_imageindex(6);
    c_wait(6);
    c_imageindex(7);
    c_snd_play(snd_noise);
    c_var_instance(cup_kris_marker, "visible", 1);
    c_wait(6);
    c_imageindex(8);
    c_waitcustom();
}
if (con == 40 && !d_ex() && customcon == 1)
{
    con = -1;
    customcon = 0;
    c_waitcustom_end();
    c_sel(su);
    c_autowalk(0);
    c_sprite(spr_tea_party_susie_grab);
    c_delaycmd4(6, "var", cup_susie_marker, "visible", 0);
    c_delaycmd(6, "sprite", spr_tea_party_susie_cup_hold);
    c_delaycmd(6, "imageindex", 0);
    c_delaycmd(6, "imagespeed", 0);
    c_delaycmd(12, "imageindex", 1);
    c_delaycmd(27, "sprite", spr_tea_party_susie_sip);
    c_delaycmd(57, "sprite", spr_tea_party_susie_cup_hold);
    c_delaycmd(57, "imageindex", 1);
    c_sel(ra);
    c_autowalk(0);
    c_sprite(spr_ralsei_walk_left_tea);
    c_imagespeed(0.2);
    c_walkdirect_wait(394, ra_actor.y, 20);
    c_halt();
    c_wait(1);
    c_sprite(spr_tea_party_ralsei_put_down);
    c_halt();
    c_wait(6);
    c_snd_play(snd_noise);
    c_var_instance(pot_marker, "x", 400);
    c_var_instance(pot_marker, "y", 239);
    c_var_instance(pot_marker, "visible", 1);
    c_imageindex(1);
    c_wait(6);
    c_imageindex(2);
    c_wait(8);
    c_facing("d");
    c_autowalk(1);
    c_walkdirect_wait(348, 181, 16);
    c_walkdirect_wait(348, 204, 8);
    c_wait(6);
    c_snd_play(snd_bump);
    c_sprite(spr_tea_party_ralsei_sit);
    c_setxy(347, 219);
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\EN* It's kinda funny..^1. I always thought tea parties were for wimps./", "obj_room_castle_kris_susie_slash_Step_0_gml_464_0");
    c_msgnextloc("\\E4* I mean^1, don't get me wrong. They still are. But.../", "obj_room_castle_kris_susie_slash_Step_0_gml_465_0");
    c_msgnextloc("\\ED* Just feels like when I'm with you guys.../", "obj_room_castle_kris_susie_slash_Step_0_gml_466_0");
    c_msgnextloc("\\EN* I don't even..^1. need to think about that./", "obj_room_castle_kris_susie_slash_Step_0_gml_467_0");
    c_facenext("ralsei", 2);
    c_msgnextloc("\\E2* Aww^1, Susie!/", "obj_room_castle_kris_susie_slash_Step_0_gml_469_0");
    c_facenext("susie", "9");
    c_msgnextloc("\\E9* Guess your stupid attitude's been rubbing off on me./", "obj_room_castle_kris_susie_slash_Step_0_gml_471_0");
    c_msgnextloc("\\EY* Like..^1. I don't want to say I've been getting soft. But.../", "obj_room_castle_kris_susie_slash_Step_0_gml_472_0");
    c_msgnextloc("\\ED* I just always..^1. HAD to be tough^1, you know?/", "obj_room_castle_kris_susie_slash_Step_0_gml_473_0");
    c_msgnextloc("\\EN* Now it just..^1. feels like I..^1. have options./", "obj_room_castle_kris_susie_slash_Step_0_gml_474_0");
    c_facenext("ralsei", 2);
    c_msgnextloc("\\E2* Aww^1, Susie!/", "obj_room_castle_kris_susie_slash_Step_0_gml_476_0");
    c_msgnextloc("\\E1* You've changed so tremendously since I met you./", "obj_room_castle_kris_susie_slash_Step_0_gml_477_0");
    c_msgnextloc("\\EJ* No^1, rather^1, you've finally just been able to.../", "obj_room_castle_kris_susie_slash_Step_0_gml_478_0");
    c_msgnextloc("\\E2* Be..^1. yourself./", "obj_room_castle_kris_susie_slash_Step_0_gml_479_0");
    c_msgnextloc("\\E1* I feel..^1. haha^1, I just feel so proud of you^1, Susie./%", "obj_room_castle_kris_susie_slash_Step_0_gml_480_0");
    c_talk();
    c_wait_box(1);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold_look_away);
    c_wait_box(2);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold_neutral);
    c_wait_box(3);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_imageindex(1);
    c_wait_box(5);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip);
    c_sel(ra);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_tea_party_ralsei_laugh);
    c_wait_box(7);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_halt();
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_imageindex(1);
    c_wait_box(8);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold_neutral);
    c_wait_box(10);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_imageindex(1);
    c_wait_box(12);
    c_sel(ra);
    c_imagespeed(0.2);
    c_sprite(spr_tea_party_ralsei_laugh);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip);
    c_wait_box(13);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_halt();
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip_surprised);
    c_wait_box(14);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_box(15);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sip_normal);
    c_wait_box(16);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_smile);
    c_sel(su);
    c_sprite(spr_tea_party_susie_cup_hold);
    c_imageindex(1);
    c_wait_talk();
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_wait(15);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_sel(su);
    c_sprite(spr_tea_party_susie_put);
    c_imageindex(0);
    c_delaycmd(6, "imageindex", 1);
    c_delaycmd4(6, "var", cup_susie_marker, "visible", 1);
    c_wait(6);
    c_snd_play(snd_bump);
    c_speaker("susie");
    c_msgsetloc(0, "\\E9* Hey^1, you've changed too^1, dude./", "obj_room_castle_kris_susie_slash_Step_0_gml_578_0");
    c_facenext("ralsei", "Q");
    c_msgnextloc("\\EQ* I..^1. I have?/", "obj_room_castle_kris_susie_slash_Step_0_gml_580_0");
    c_facenext("susie", "0");
    c_msgnextloc("\\E0* Before..^1. you were all stuck up about being good^1, right?/", "obj_room_castle_kris_susie_slash_Step_0_gml_582_0");
    c_msgnextloc("\\E2* Now..^1. you're actually kinda normal sometimes./", "obj_room_castle_kris_susie_slash_Step_0_gml_583_0");
    c_facenext("ralsei", "1");
    c_msgnextloc("\\E1* I suppose I just..^1. started appreciating you more^1, Susie./", "obj_room_castle_kris_susie_slash_Step_0_gml_585_0");
    c_msgnextloc("\\E9* For example^1, I thought your Rude Buster was scary before.../", "obj_room_castle_kris_susie_slash_Step_0_gml_586_0");
    c_msgnextloc("\\E1* But now^1, I think it's really b--/", "obj_room_castle_kris_susie_slash_Step_0_gml_587_0");
    c_msgnextloc("\\EK* Umm^1, bad-bum!/", "obj_room_castle_kris_susie_slash_Step_0_gml_588_0");
    c_facenext("susie", "9");
    c_msgnextloc("\\E9* Just say \"bad ass\"^1, idiot!/%", "obj_room_castle_kris_susie_slash_Step_0_gml_590_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_box(4);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_box(8);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_wait_box(9);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_box(10);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_smile);
    c_wait_box(12);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_wait_talk();
    c_sel(ra);
    c_autowalk(0);
    c_imagespeed(0.2);
    c_sprite(spr_tea_party_ralsei_laugh);
    c_snd_play(snd_suslaugh);
    c_sel(su);
    c_imagespeed(0.2);
    c_sprite(spr_tea_party_susie_laugh);
    c_wait(60);
    c_sprite(spr_tea_party_susie_sit);
    c_halt();
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_halt();
    c_wait(30);
    c_speaker("susie");
    c_msgsetloc(0, "\\EA* You gonna eat a piece or what?/", "obj_room_castle_kris_susie_slash_Step_0_gml_644_0");
    c_facenext("ralsei", "J");
    c_msgnextloc("\\EJ* Huh? No^1, that's for you two^1, haha./%", "obj_room_castle_kris_susie_slash_Step_0_gml_646_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_talk();
    c_sel(su);
    c_autodepth(0);
    c_depth(96500);
    c_sprite(spr_tea_party_susie_push);
    c_imageindex(0);
    c_delaycmd(6, "imageindex", 1);
    c_delaycmd(30, "sprite", spr_tea_party_susie_sit);
    c_delaycmd(30, "imageindex", 0);
    c_snd_play(snd_wing);
    c_var_lerp_to_instance(slice_marker, "x", slice_marker.x - 106, 12, 3, "out");
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_surprised);
    c_wait(60);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* Dude^1, you made it. You should have some./", "obj_room_castle_kris_susie_slash_Step_0_gml_676_0");
    c_facenext("ralsei", "Q");
    c_msgnextloc("\\EQ* Umm..^1. okay!/%", "obj_room_castle_kris_susie_slash_Step_0_gml_678_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_talk();
    c_wait(30);
    c_sel(ra);
    c_autodepth(0);
    c_depth(96655);
    c_sprite(spr_tea_party_ralsei_cake_eat);
    c_halt();
    c_wait(6);
    c_imageindex(1);
    c_var_instance(slice_marker, "image_index", 1);
    c_wait(6);
    c_imageindex(2);
    c_wait(6);
    c_imageindex(3);
    c_snd_play(snd_swallow);
    c_wait(6);
    c_imageindex(4);
    c_wait(20);
    c_emote("!", 30);
    c_sprite(spr_tea_party_ralsei_cake_shock);
    c_halt();
    c_wait(30);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\ED* ...!/", "obj_room_castle_kris_susie_slash_Step_0_gml_715_0");
    c_msgnextloc("\\EH* Oh^1! Th..^1. this is really yummy!/", "obj_room_castle_kris_susie_slash_Step_0_gml_716_0");
    c_facenext("susie", "6");
    c_msgnextloc("\\E6* Why the heck are you so surprised?/%", "obj_room_castle_kris_susie_slash_Step_0_gml_718_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_cake_smile);
    c_wait_talk();
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_cake_smile);
    c_wait(12);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_halt();
    c_speaker("ralsei");
    c_msgsetloc(0, "\\ED* I..^1. I've actually never eaten cake before.../", "obj_room_castle_kris_susie_slash_Step_0_gml_737_0");
    c_msgnextloc("\\E1* Since^1, I was making it for you two^1, after all./", "obj_room_castle_kris_susie_slash_Step_0_gml_738_0");
    c_msgnextloc("\\E2* ..^1. I can't believe it tastes this good!/", "obj_room_castle_kris_susie_slash_Step_0_gml_739_0");
    c_facenext("susie", "9");
    c_msgnextloc("\\E9* Haha^1, dude^1, you're such a weirdo sometimes./", "obj_room_castle_kris_susie_slash_Step_0_gml_741_0");
    c_msgnextloc("\\E2* Just have the rest./", "obj_room_castle_kris_susie_slash_Step_0_gml_742_0");
    c_facenext("ralsei", "D");
    c_msgnextloc("\\ED* N-no^1, I couldn't.../%", "obj_room_castle_kris_susie_slash_Step_0_gml_744_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_blush);
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_smile);
    c_wait_box(3);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_wait_box(7);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_wait_talk();
    c_msc(1411);
    c_talk_wait();
    c_waitcustom();
}
if (con == 50 && !d_ex() && customcon == 1)
{
    con = 70;
    customcon = 0;
    c_waitcustom_end();
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_surprised);
    c_speaker("ralsei");
    c_msgsetloc(0, "\\E2* Umm^1, okay^1! Just^1, um..^1. later./", "obj_room_castle_kris_susie_slash_Step_0_gml_784_0");
    c_msgnextloc("\\E1* (I'm^1, a bit embarrassed how much I liked it...)/%", "obj_room_castle_kris_susie_slash_Step_0_gml_785_0");
    c_talk();
    c_wait_box(1);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_blush);
    c_wait_talk();
    c_waitcustom();
}
if (con == 60 && !d_ex() && customcon == 1)
{
    con = 70;
    customcon = 0;
    c_waitcustom_end();
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_look_away);
    c_sel(su);
    c_sprite(spr_tea_party_susie_sit_neutral);
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* Haha^1, Kris^1, chill. He'll make you more later./", "obj_room_castle_kris_susie_slash_Step_0_gml_811_0");
    c_facenext("ralsei", 19);
    c_msgnextloc("\\EJ* Umm^1, I'd be happy to!/%", "obj_room_castle_kris_susie_slash_Step_0_gml_813_0");
    c_talk();
    c_wait_box(2);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit_smile);
    c_wait_talk();
    c_waitcustom();
}
if (con == 70 && !d_ex() && customcon == 1)
{
    con = 80;
    customcon = 0;
    c_waitcustom_end();
    c_sel(su);
    c_autodepth(1);
    c_sprite(spr_tea_party_susie_sit);
    c_sel(ra);
    c_sprite(spr_tea_party_ralsei_sit);
    c_speaker("susie");
    c_msgsetloc(0, "\\E9* Anyways^1, that was kinda fun. Thanks Ralsei./%", "obj_room_castle_kris_susie_slash_Step_0_gml_843_0");
    c_talk_wait();
    c_mus2("volume", 0, 60);
    c_snd_play(snd_wing);
    c_sel(kr);
    c_autowalk(0);
    c_walkdirect_wait(kr_actor.x, 192, 4);
    c_autowalk(1);
    c_walkdirect(647, 192, 30);
    c_wait(10);
    c_sel(ra);
    c_snd_play(snd_wing);
    c_autowalk(1);
    c_walkdirect(343, 182, 15);
    c_delaycmd(16, "autodepth", 0);
    c_delaycmd(16, "depth", 98000);
    c_delaywalkdirect(16, 546, 182, 30);
    c_var_instance(chair_right_marker, "visible", 1);
    c_sel(su);
    c_snd_play(snd_wing);
    c_autowalk(1);
    c_facing("u");
    c_walkdirect_wait(514, 177, 15);
    c_walkdirect_wait(596, 177, 15);
    c_wait(30);
    c_mus("free_all");
    c_speaker("susie");
    c_msgsetloc(0, "\\E2* (Kris^1, we should do something for Ralsei sometime...)/%", "obj_room_castle_kris_susie_slash_Step_0_gml_879_0");
    c_talk_wait();
    c_mus2("initloop", audio_file, 0);
    c_mus2("volume", 0, 0);
    c_mus2("volume", 1, 120);
    c_pannable(1);
    c_panobj(kr_actor, 30);
    c_wait(31);
    c_sel(kr);
    c_facing("d");
    c_pannable(0);
    c_actortokris();
    c_actortocaterpillar();
    c_terminatekillactors();
}
if (con == 80 && !d_ex() && !i_ex(obj_cutscene_master))
{
    con = -1;
    global.interact = 0;
    if (global.plot >= 45 && global.plot < 50)
    {
        if (scr_flag_get(1559) == 0)
            scr_flag_set(1559, 1);
    }
    clean_up();
}
if (sugar_flick)
{
    sugar_flick_timer++;
    if (sugar_flick_timer == 1)
    {
        var sugar = scr_marker(sugar_marker.x + 4, sugar_marker.y, spr_pixel_white);
        with (sugar)
        {
            hspeed = -10;
            vspeed = -8;
            scr_var_delay("hspeed", 0, 6);
            scr_var_delay("vspeed", 0, 6);
            scr_script_delayed(scr_jump_to_point, 7, 410, 250, 15, 12);
            scr_doom(id, 20);
        }
    }
    if (sugar_flick_timer >= 5)
    {
        sugar_flick_timer = 0;
        sugar_flick = false;
    }
}
