scr_bullet_init();
scr_darksize();
image_index = 8;
image_speed = 0;
timer = 0;
spin = 2;
angle = 0;
amount = 1;
init_start = 4;
init = 8;
circle_val = 0;
circle_goal = 5;
circle_distance = 120;
circle_list = ds_list_create();
endme = false;
alarm[0] = 16;
center_x = scr_get_box(4);
center_y = scr_get_box(3) + 43;
anchor_x = x;
anchor_y = y;
difficulty = 0;
turn_type = "full";
turn_segment = -1;
next_up = -999;
next_next_up = -1;
local_turntimer = 340;
